### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by delboy1978uk** [MPOS/php-mpos#2373]
A project of this size should have all its classes tested, and test code coverage reports should be generated.

I propose hooking this repository up to travis-ci.org which will automatically try and run any tests and do any build tasks. 

In order for that to be of any use, I also propose the repository is hooked up with scrutinizer-ci.com, which analyses your classes, rates your code, and can even automatically offer code fixes via git pull requests.

I you look at https://github.com/delboy1978uk/bone you can see how I have hooked up that repository to work in this way. I will send a pull request when my dev branch has all the changes, but first you'll need to sign up to travis and scrutinizer (free for all github foss software)

**Comment by TheSerapher** [comment]
Closing this, lack of time to do this on my own and apparently not too much public interest to get them added. Thanks a lot for the PR though, should I ever have the time to go back to this I will use it as a base to get started!
