### ISSUE TITLE
PSR Namespaced Autoloading through Composer

### ISSUE THREAD

**Issue by delboy1978uk** [MPOS/php-mpos#2374]
Every new package these days user Composer to take care of autoloading. 
Once we have loads of unit tests in place we should start to remove all the old fashioned includes and requires everywhere, and rename the classes to be PSR-4 compliant, allowing them to be autoloaded by Composer without the need to include the class files.

**Comment by TheSerapher** [comment]
Closing this, lack of time to do this on my own and apparently not too much public interest to get them added. Thanks a lot for the PR though, should I ever have the time to go back to this I will use it as a base to get started! (Shameless copy and paste)
