### ISSUE TITLE
Determining Pool Hash Rate

### ISSUE THREAD

**Issue by jjj092353** [MPOS/php-mpos#2381]
I have a need to determine the hash rate of the pool through php and wondered what table I should query to determine the current hash rate of the pool (and optionally how many workers are currently mining in the pool)

thanks in advance.

**Comment by TheSerapher** [comment]
Shares table. Hash rate is derived from shares inserted.

**Comment by jjj092353** [comment]
can you give me for formula in terms of a query to calculate it?

**Comment by TheSerapher** [comment]
This one fetches the data for all user account using the cronjob:

https://github.com/MPOS/php-mpos/blob/development/include/classes/statistics.class.php#L468-L494
