### ISSUE TITLE
Round shares overflowing / maxing out at 4,294,967,295

### ISSUE THREAD

**Issue by hashfaster** [MPOS/php-mpos#2382]
When I have a round with more than 4,294,967,295 shares submitted, the round always reports in Blocks as a max of 4,294,967,295.   I am not sure if it impacts being paid out, etc, but it surely messes up blocks page.

**Comment by hashfaster** [comment]
I am wondering if the blocks table needs shares col changed from int(255) to bigint, like the shares table once needed to store the large id's

**Comment by TheSerapher** [comment]
That may be the case, I will check.

**Comment by TheSerapher** [comment]
Hey @daygle,

I have committed the change into a branch called `bigint-blocks-shares`. I have not tested if the upgrade script works, but if you could give it a try (in a non-active pool maybe), let me know if it works for you!

I will setup a pool in virtual box sometime so I have a place to test changes myself.

**Comment by TheSerapher** [comment]
I went ahead and updated all files to version 1.0.0 - kinda like releasing it ;-)

**Comment by TheSerapher** [comment]
@hashfaster - any news on this? Would like to start merging if this works for you. Use branch mentioned above to test this upgrade.

**Comment by hashfaster** [comment]
I didnt end up using this branch, but I did alter the database in the same way the same day I opened this issue and it did infact fix the problem, rounds now report correctly with over int(255) limit by using bigint

**Comment by TheSerapher** [comment]
Merged into dev and master, thanks @hashfaster
