### ISSUE TITLE
PPCOIN stratum error

### ISSUE THREAD

**Issue by Minersworld** [MPOS/php-mpos#2383]
Hello all,

I got my own stratum pool running ( mw-hosting.com ),
Recently i added PPCOIN to it, but for some reason i'm getting this error:  We tried to poke your Stratum server using your $config['gettingstarted'] settings but it didn't respond - Connection refused 

I double checked the stratum settings, tried different ports and rebuilded the wallet twice to be sure.
Now i found something that ppcoin need some kind of addon / module to use it in NOMP.
Not realy sure about this.
My firewall is not blocking anything and the wallet is fully synced and online.
So it's not an actual connection error.

Anyone here that knows this issue?

**Comment by TheSerapher** [comment]
Port is not open. Ensure telnet to the port works and it's listed in netstat -plan shows it as listening.

Refused means MPOS opened the socket but wasn't able to connect. Does not look like an MPOS issue.

If stratum isn't working and check NOMP channels for more help.

**Comment by Minersworld** [comment]
the port is 100% open, i even tried a port from a working coin.

but will try the nomp channel.

**Comment by TheSerapher** [comment]
Then try telnet from your MPOS node to the stratum port. Double check IP and port number in MPOS. And make sure that NOMP actually opened the port using netstat.

**Comment by Minersworld** [comment]
Well the strange thing is that all other coins work fine.
Still there whas something about an extra module i needed to add to nomp for PPcoin to work... here it is: https://github.com/doomhz/node-peercoin 

As i tried this, it still doesn't work.

**Comment by Minersworld** [comment]
again i tried a port from a different coin, the ip is just the address  of my domain, it's the same for every coin only the port is different.

**Comment by TheSerapher** [comment]
Looks like a NOMP issue to me. If all coins work and this is special, I doubt it's an MPOS issue.

**Comment by Minersworld** [comment]
Download the Developer version of the PPcoin wallet. ( instead of master ! )
That should solve the connection error.

But besides it finaly runs at my place, no blocks found so far, found out the coin basic settings is on POS! ( check your nomp log ) 

I have no freaking idea how to change this to POW.
Checked all NOMP settings and MPOS settings to be sure... nothing there.
Who knows this part ?

**Comment by TheSerapher** [comment]
NOMP. Mining basics are all in NOMP/Stratum, MPOS just connects to pay blocks once they are discovered.

Not an MPOS issue. Try NOMP issue tracker or their help.

**Comment by Gexain** [comment]
enter in $ cd /var/www/MPOS/include/config/   sudo nano global.inc.php and search $config['gettingstarted']['stratumurl'] = ''; and change for $config['gettingstarted']['stratumurl'] = 'localhost';  for localhost o for your ip.

**Comment by drainx** [comment]
Gexain, that is incorrect; peercoin has a different RPC interface, which makes interacting with stratum difficult and requires a stratum change. I can't recall exactly what that change is off the top of my head, but as TheSerapher stated, it isn't an MPOS issue.
