### ISSUE TITLE
can't find block

### ISSUE THREAD

**Issue by xxTeDYxx** [MPOS/php-mpos#2385]
Hiho i have big problem.
Im using a mpos and my pool (pool.zaplnc.pl) can't find block, cronjobs are good all in monitoring on green.

When is probably bugs ?

**Comment by TheSerapher** [comment]
Not a bug. Depending on the coin, block chain, difficulty and many other factors this can take a while.

Confirm your wallet has found any blocks that MPOS didn't pick up first, if you need help on that check for the commands in the coind to list all discovered blocks.

**Comment by TheSerapher** [comment]
Also check crons log files.

It could also be instant orphaned blocks. Then they won't show up fast enough for MPOS to calculate them and mark them as orphan too (no coins for those). Then it looks like a very long round.

I have no track of all these coins being created out there but make sure that this one is supported. Most of the coins are :-)

**Comment by xxTeDYxx** [comment]
On my pool is: 

 SALT or SALTY is too short, they should be more than 24 characters and changing them will require registering again

	
 Own   Pool

 Valid

9,424	12,852,656
 Invalid

0	909,920
 Efficiency

100.00%	93.39%


in monitoring all okey

What now ?:<

**Comment by TheSerapher** [comment]
Check what I mentioned in my first and second comment.

**Comment by xxTeDYxx** [comment]
On my pool 1 person have 80 mhash (more than nethashrate) and don't find any blocks ?

**Comment by TheSerapher** [comment]
You still haven't check my original questions:

* What does your local coind say about your recent transactions? Does your coind say it found blocks that MPOS didn't pick up?
* If yes, what do the logs say?

**Comment by xxTeDYxx** [comment]
Where i can check this ?

**Comment by TheSerapher** [comment]
As I said, check your coind commands and maybe ask for help from the coin developers.

MPOS hasn't had any issues with picking up blocks for a year so it's very unlikely it's a bug. You should double check the coind is running and working properly with your stratum.

**Comment by xxTeDYxx** [comment]
On p2p pool it's work fine :P

In AP > Wallet info cant see address od wallet hmm

**Comment by TheSerapher** [comment]
Maybe this coin isn't supported for your stratum? Would be weird to show accepted shares but never solve a block but certainly not impossible.

Maybe find other pool operators running the same coin and find out what needs to be done to make it work - if at all.

**Comment by xxTeDYxx** [comment]
It works with the MPOS, only i have a problem: <

Do you have a digger? You can check this?

**Comment by TheSerapher** [comment]
If it works with MPOS, since you say others run it, how could it be a bug? It's more likely a problem with your Stratum/CoinD/MPOS setup - or you simply aren't running crons every minute.

I am not giving personal support, neither paid nor free. If you need assistance try IRC or other pool operators running this or any other coin. I am not actively developing MPOS anymore, only doing some basic maintenance if time allows.
