### ISSUE TITLE
Floating reward and contributions nodes

### ISSUE THREAD

**Issue by djnapalm** [MPOS/php-mpos#2390]
Hi!
How to be a non-constant reward and deductions master nodes? For example Darkcoin.
On good, the value of awards need not specify the configuration file, and to receive from wallet.
Masternode uptrend payments https://darkcointalk.org/threads/schedule-for-masternode-uptrend-payments.3700/

**Comment by TheSerapher** [comment]
I am not I understand correctly but if you are asking what about payouts of blocks changing their value - either one time each X blocks or constantly, MPOS has an option to set payouts to the actual block value or fixed. Default should be dynamic payouts based on block values.

Other than that, try asking around other MPOS pool owners running Dark Coin. This repository is not actively maintained anymore and any changes that may be required will have to be done via Pull Requests by the community.
