### ISSUE TITLE
limiting api requests

### ISSUE THREAD

**Issue by jjj092353** [MPOS/php-mpos#2391]
I was wondering is there is a limited to restrict api requests to a certain ip address and deny any api calls from all other addresses?

I'm asking because even though we were using the admins api key we were got a rate limit error/

thanks

**Comment by TheSerapher** [comment]
Not implemented right now but this isn't too hard to add via configuration and using a black- and whitelist.

The check has to be done early to ensure no code is executed prior to doing IP checks.

**Comment by TheSerapher** [comment]
Also admin keys can't be whitelisted right now, but as you mentioned you want something for IPs instead. This should be easier to add.

Agreed that it has to be added to the Rate Limiting section too. Maybe the entire white and blacklist can be placed there.

**Comment by jjj092353** [comment]
thank you - for my own custom code I was just considering some additional code at the beginning of api.class.php to deny requests from any ip's other than my own IP's which will be issuing api calls.

sound reasonable?

ps: we were able to modify the code to return a list of all workers in the pool who had network hash rates - thanks for your help.

**Comment by TheSerapher** [comment]
I would check the rate limiter and add it to that. Since the API class probably will not have any influence on the rate limiter, you'd still get blocked if you call the API too often.

PS: Excellent, it's not too hard to add but as mentioned in the other ticket that call is really expensive and not recommended for most pools ;-)

**Comment by jjj092353** [comment]
Thanks we have special needs for the pools (40) of them interfacing with Smarterhash.com. I've also made extensive use of symbolic links to eliminate redundancy across directories. We can create accounts and workers remotely from Smarterhash.com and do 'lots' of other things I'll be able to disclose soon.

Where exactly can I find the rate limiter?

thanks in advance.

**Comment by TheSerapher** [comment]
It's probably done here: https://github.com/MPOS/php-mpos/blob/f996118d17c75e151db549afe1c5f7be0cf096f2/include/classes/memcache_ad.class.php

**Comment by TheSerapher** [comment]
Closing for now.
