### ISSUE TITLE
pin change at user request ...

### ISSUE THREAD

**Issue by chrysophylax69** [MPOS/php-mpos#2392]
hi all ...

can a user ( or admin for that matter ) change the pin to a number that they desire? ...

or are we stuck with the pin change request to a pin that is random generated my mpos itself? ...

#crysx

**Comment by drainx** [comment]
It depends if you are willing to add an optional parameter to a function and call it.
https://github.com/MPOS/php-mpos/blob/master/include/classes/user.class.php#L310 is where you want to look.

**Comment by TheSerapher** [comment]
I strongly suggest not adding this for a simple reason:

If a hacker gains access to a users account by any means they still can't change any payout information unless they have a PIN. Giving a user the ability to set a pin on their own will open the door for an attacker to empty the users account.

So no, there is currently no way to do this.

**Comment by chrysophylax69** [comment]
ok ...

but as the admin of the pool AND the owner of my own account on my own pool - i keep forgetting the pin that is set ...

surely there should be a password backed ( or 2-3 level ) secure way of resetting the pin to a user defined one ... so a user does not forget it ...

much like a credit card pin - user defined ...

#crysx

**Comment by TheSerapher** [comment]
Not yet but feel free to add two factor checks to set a user PIN. It may be enough to confirm a change via email before taking it live, just like with a password.

**Comment by chrysophylax69** [comment]
tanx for the response ...

but i would not have the faintest idea how to achieve this ...

im nto a developer im sorry - 'i just work here' ;) ...

seriously - if there is a simple way of achieving this - please let me know ...

#crysx

**Comment by TheSerapher** [comment]
For a non coder? I am afraid not ;-)

Here some simple thing to do though: don't forget your pin. Maybe put it in a Keypass or 1Password vault so you won't have to reset it all the time ;-)

**Comment by chrysophylax69** [comment]
hehehe ... tanx for stating the obvious ;) ...

so can i safely assume this will not be a future 'feature' or option for this awesome piece of mining software? ...

it would simplify the users experience immensely ...

#crysx

**Comment by TheSerapher** [comment]
Probably not since I am not actively working on it anymore. Just maintaining it when needed.

If I get bored someday I may add it in though. I would reopen the ticket so you'd know.

**Comment by chrysophylax69** [comment]
that would be great mate ...

so who codes and maintains it now? ...

there would be a few things that would be a massive uplift to the package - and i would be happy to negotiate a fee for the additions / changes ...

#crysx

**Comment by TheSerapher** [comment]
Nobody. I was the only maintainer for a while and since real life has taken over, I have no more time to work on this project. Also this project is open source and does not accept fees for features. It's been that way since I started and I am not intending to change that. I am a believer in OpenSource and taking a 'free' to get features implemented does not fit this believe ;-)

**Comment by chrysophylax69** [comment]
i understand that - though that is not what i am asking ...

ive been an opensource advocate since the beginning ... there are things that WE would like done to OUR pool using this software ... where would a developer be in order to commission the work for things to be done ...

since you are the main one - i thought id ask if you were interested in developing the pool for us ... commissioning you ( for instance if you have the time and inclination ) is a contracted position - and therefore is a paid arrangement using this wonderful software as a base ...

#crysx

**Comment by TheSerapher** [comment]
I completely understand the intend of your offer but have to refuse for stated reason above. If someone hired me to improve a pool they'd probably want to keep those improvements in-house, which would not make it possible for me to release it to the public. Hence I have been and continue to refuse any paid work on this product.

On the other hand, you can always try some channels (IRC, Forum, others?) to find someone willing to spend time to improve your specific pool. But always keep in mind: You are dealing with money. If you get a developer to work on your software, make sure he won't run away with the coins. This probably happens more often than not.

For that reason, I can also not give you any real advise. This software was not really meant for a regular user, even though it is that easy to use nowadays. It was meant for someone with good mining knowledge and the potential to change the code as needed by themselves (to reduce the risk of someone stealing the coins just working on the code).

I have to admit, this ticket has gone a bit off-topic, but I hope this clears things up.

**Comment by chrysophylax69** [comment]
it does - and no issue ...

commissioning / contracting for work that needs to be done is something that needs to be done here - as we do not have the skillset for developing software ... hence the outsourcing ...

reasons are entirely understood ... and we are thankful that you have clarified this ...

as for stayign on-topic ... will there be any time that you will be spending on the software improving it any further - or is this it until someone picks it up again? ...

i understand you have stated that 'life' happens - and it certainly does - but the question remains whether this software is going to be further improved - and if so - how and when? ...

questions which probably dont have an answer unless someone ( or team ) is willing to pick up the project im assuming ...

much appreciated for your time ...

#crysx

**Comment by TheSerapher** [comment]
I have no intensions to getting back to the software anytime soon. Sadly nobody asked me to pick it up either (understandable, it's not the best code out there ;-)). So if or when you will see improvements again, no idea.

There have been other pieces of software though that could run as a full pool including payouts. I don't know how actively maintained these are or if they come close to the feature set provided by MPOS, but at least it's an option.

**Comment by chrysophylax69** [comment]
mpos seems to me to be the best pool software insofaras features and richness of 'stats candy' and flexibility within its infrastructure to be added to and improved ...

in any case - it IS opensource so once we get a team of devs that specialize in their own field togther - we will look much more intently at mpos again ...

until then - it is a very much appreciated tool ... in use in a small way at the moment - but thats due to the features that are missing for us ;) ... hehehe ...

tanx again mate ...

#crysx

**Comment by TheSerapher** [comment]
Yeah I hear you. Most features that I never got around to add (multipool for example being at the top of things) will probably never make it into MPOS. I doubt someone is willing to tackle the task of taking my code apart and re-assemble it in a way it will work generic for ALL coins supported so far and still not break anything in the backend (like payouts). To be honest, it may be best if someone else would start a new piece of software entirely from scratch using MPOS as the sample code ;-)

**Comment by chrysophylax69** [comment]
unless of course - it is worth it for you to redo it that way and improve it further ...

WITH all the features that we all want in it ...

;) ...

#crysx

**Comment by TheSerapher** [comment]
The same rule that applies to MPOS applies here: No time :-)

**Comment by chrysophylax69** [comment]
all good - much appreciated for your time here mate ...

good luck in what you plan on doing with the time you actually DO have :) ...

#crysx
