### ISSUE TITLE
hashrate error

### ISSUE THREAD

**Issue by micheldaniel** [MPOS/php-mpos#2393]
I have a  configure miningpool. If i hash with a cpu than i have the good hashrate but if I hash with my g-blade grindseed than give the pool 0.44 KH/S how can that???

**Comment by TheSerapher** [comment]
Have you checked that the pool is actually accepting your G-Blades shares? Sounds to me that they are all invalid.

Check stratum too, it should also accept these shares.

**Comment by micheldaniel** [comment]
the miningpool don't accept the G-blades shares.

**Comment by TheSerapher** [comment]
Then debug your stratum and G-Blade setup. This is not an MPOS issue nor is there a fix you can do in MPOS.
