### ISSUE TITLE
Python using only a single core

### ISSUE THREAD

**Issue by mmitech** [MPOS/php-mpos#2394]
I know this is not the right place to discuss this issue, but since there is no option to post about  issues in https://github.com/ahmedbodi/stratum-mining I will try to discuss it here, maybe someone have a suggestion or an idea for solving this problem. (because I am sure people went through this as well )

Like the title says, we have a problem where the stratum proxy is using only one core, on load the core goes at 100% while the other 3 cores are working at less than 20%, after searching around I found about Python's Global Interpreter Lock (GIL), but solving it require editing the source code and adding the multiprocessing code to it, and you guessed it right, I have no idea where to add that code...

any help, suggestions or tricks would be appreciated

Thank you and keep up the good work.

**Comment by TheSerapher** [comment]
As you said, not an issue here. Please find other channels to discuss things off-topic. Have you tried IRC or the Forums of Bitcointalk for example?

**Comment by TheSerapher** [comment]
Maybe try other implementations for Stratum:

https://github.com/int6/CoiniumServ
https://github.com/zone117x/node-open-mining-portal

I have used NOMP myself for a long time and have not had any real issues with it. It also runs with MPOS once you disable payment processing.
