### ISSUE TITLE
found block 0

### ISSUE THREAD

**Issue by waelboyka** [MPOS/php-mpos#2395]
thanks for this guide i try it with guncoin wallet and stratum server and all thing work fine but i have a problem always block found =0 and last block =0 i check the data base and i see that table block is empty .and table round is emty i passed 3 days mining i have 9000 shares but always last block found =0 and confirm block=00000 and unconfirmed =0000 how i resolve that?

**Comment by TheSerapher** [comment]
Check your Stratum, Check your coind for created blocks. Probably not an MPOS issue unless this coin does something totally different than others.

**Comment by waelboyka** [comment]
what is the best coin that mpos support?
