### ISSUE TITLE
cronjobs error

### ISSUE THREAD

**Issue by jam3oun** [MPOS/php-mpos#2396]
in the log file i find this error 
in findblock:
-No new RPC transactions since last block
-No new blocks without share_id found in database
in block update :
Failed to connect to RPC server
what's the problem ? how can i resolve it ?

**Comment by waelboyka** [comment]
i have the same problem and i can't resolve it

**Comment by TheSerapher** [comment]
Read error logs of crons, see wiki documentation. Find help on IRC or other forums.

Most likely a coind issue as the connection error already states.
