### ISSUE TITLE
cookie question

### ISSUE THREAD

**Issue by jjj092353** [MPOS/php-mpos#2397]
I have multiple pools such as abc.mypools.com, def.mypools.com, ghi.mypools.com and I want to share a cookie between all of the pools on the domain since I have setup mpos so that the account and workers tables are shared between the pools and really don't want to make people have to login to each pool since they'll often be mining in multiple pools simultaneously : is there a way to do this?

thanks in advance.

**Comment by TheSerapher** [comment]
Try .domain.tld on your installations but mark one as the "primary" which has host.domain.tld.

Not sure if works but I heard others use it properly. So there has to be a way. Maybe someone else can chime in.

**Comment by TheSerapher** [comment]
Sorry pushed close by accident.

**Comment by TheSerapher** [comment]
Closing this, if you have figured it out (since I am sure it has to work, other pools use it), please post a comment for others to see.
