### ISSUE TITLE
Mined blocks not update on mysql

### ISSUE THREAD

**Issue by jam3oun** [MPOS/php-mpos#2399]
I was succeed setting up stratum-mining + mpos at the first time, mpos is working fine, miner hashrate & share are shown
i can see all my shares in the DB
however, mined blocks are not showing, table blocks are empty alwayes when i put
 select count(*) from blocks;
alwayes 0

i had no idea what's wrong :( please help !!!

**Comment by TheSerapher** [comment]
You have not found any blocks. Check your mining works properly and you are in the range of finding a block. Check for your coind commands to check mined blocks show up in your blockchain.

Most common not enough patience and not an MPOS issue.
