### ISSUE TITLE
{literal} tags

### ISSUE THREAD

**Issue by phoneman13** [MPOS/php-mpos#2400]
Can someone remind why the {literal} tags are reversed in the dashboard api?  {/literal}{literal}  I've read it somewhere before but cannot remember or find it now. Thanks.

**Comment by TheSerapher** [comment]
IIRC No literal is possible because everything is escaped.

**Comment by TheSerapher** [comment]
Actually I am not sure. I guess it depends where you are using it. I don't remember using literals anywhere in the API.

**Comment by phoneman13** [comment]
dashboard/js/api.tpl....I think the js is in literals. It at first looked like the literals were reversed.

**Comment by TheSerapher** [comment]
Yes that's it :-) Literal was required so I don't have to take care of escaping strings I wasn't sure about. Worked easier this way.
