### ISSUE TITLE
Kimoto Gravity Well Next Difficulty

### ISSUE THREAD

**Issue by TheSerapher** [MPOS/php-mpos#2403]
Even though many coins now use the KGW algorithm to estimate the next blocks expected difficulty, this is not yet included in MPOS.

For some reason, no coind currently supports a `getnextdifficulty` call which would make all this a whole lot simpler.

So in order for expected next difficulty calculations to work we have to implement the entire KGW algorithm into the project as PHP: https://github.com/megacoin/megacoin/blob/master/src/main.cpp#L1276-L1334

And to make things worse, coins have started adjusting some parameters in that calculation. So we'd have to identify the variables used and allow pool operators to adjust them according to the coin.

Here a few that I have already identified:

* https://github.com/megacoin/megacoin/blob/master/src/main.cpp#L1309
 * 144 can be changed on some coins
* https://github.com/megacoin/megacoin/blob/master/src/main.cpp#L1340-L1341
 * 0.25 and 7 vary for some coins

The algorithm is also pulling in a lot of information. We have to see which one is required in order to make this work in MPOS.

**Comment by TheSerapher** [comment]
Created a new branch `kgw-next-diff` that shows where the magic needs to happen and already includes the identified variables. Maybe someone can pick this up.

**Comment by ahmedbodi** [comment]
ther isnt much point in this. theres a ton of different diff algos out there. Including:

Bitcoin diff system.
POS PPCoin System.
Dark Gravity Wave (DGW)
Kimoto Gravity Well (KGW)
Nite Gravity Well (KGW + Timewarp Patch)
Digishield v1, v2, v3 
Slingshield
The hundreds of custom forks out there

**Comment by TheSerapher** [comment]
Good point. And since this will never change, we keep it the way it is and mention it's an estimate ;-) Thanks for the heads up @ahmedbodi

**Comment by ahmedbodi** [comment]
all good @TheSerapher :)
