### ISSUE TITLE
MPOS SSO

### ISSUE THREAD

**Issue by TheSerapher** [MPOS/php-mpos#2405]
Since people keep asking to implement at least SSO to MPOS (since Multipool on a single site simply is too hard to do right now) I have decided to give it a go. You can find the result in the current development branch with details listed in the CHANGELOG and in the Pull Request: https://github.com/MPOS/php-mpos/pull/2402

This may need some testing from people that are either running SSO or wish to try it out. Hence I created this ticket for visibility. I would also like people to give some feedback if this is working for them or not, and if not what I may have to change to make it work.

Happy testing (git checkout development; git pull; php upgrade/run_upgrades.php)!

**Comment by TheSerapher** [comment]
This may be interesting for you @jjj092353 and @chrysophylax69

Hopefully the implementation is sane and can work for others too, then MPOS is officially SSO capable.

**Comment by TheSerapher** [comment]
Found a first smaller issue: When upgrading, you have to ensure the `$config['db']['shared']['name'] = $config['db']['name'];` line is also included in your `global.inc.php` file. Since most people will change the `$config['db']['name']` from the default supplied, you must add this option or your logins and worker logins will fail. You may also notice empty statistics and weird data until this is properly set.

**Comment by TheSerapher** [comment]
Updated to work as before so no config update will be required after upgrading to 1.0.2. Merging soon.

**Comment by TheSerapher** [comment]
Released. Closing issue.

**Comment by jjj092353** [comment]
I already implemented it myself at pool.smarterhash.com - it was easy by setting up a view to accounts and pool_worker then setting the cookie properly.

**Comment by TheSerapher** [comment]
That also works well indeed but doing it in the applications allows it for everyone without knowing much about MySQL :-) And it gets rid of the View as well.
