### ISSUE TITLE
restart the backend 

### ISSUE THREAD

**Issue by btcminerpool** [MPOS/php-mpos#2406]
hi i power off my server and now the backend didnt start back up how to restart the backend
im getting this 

We are investingating issues in the backend. Your shares and hashrate are safe and we will fix things ASAP.

Findblocks disabled, new blocks will currently not show up in the frontend
PPS payout disabled, share credit transactions are delayed
Blockupdate disabled, blocks and transactions confirmations are delayed
Payouts disabled, you will not receive any coins to your offline wallet for the time being

**Comment by TheSerapher** [comment]
Before restarting a server disable all cribs by hand and ensure they finished running.

You can force a cron run to fix this but make sure you don't double payout users due to a previous unfinished run.

**Comment by btcminerpool** [comment]
Whats the commands to do that on ubuntu 14.04 ? Thanks

**Comment by TheSerapher** [comment]
Whoever runs the crons, `crontab -e` and comment them out, then wait for any running crons to finish. Then reboot.

**Comment by btcminerpool** [comment]
email me at roy.meeson@icloud.com

**Comment by TheSerapher** [comment]
No, these are Linux basics you will need to look up online. I gave all the instructions required to safely reboot a server :-)

**Comment by ropyu1978** [comment]
disable all cribs by hand and ensure they finished running？

What  is the commands？

**Comment by TheSerapher** [comment]
Exact same way as you created them, *crontab -e* for the user running the crons and disable them there. Then wait until they finished.
