### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by waelboyka** [MPOS/php-mpos#2410]
after one hour of mining the balance stay always 0.0000 what is the problem?

**Comment by TheSerapher** [comment]
I have had a couple of those in the past 3 months all winding down to a simple answer: nothing is wrong. If your stratum is setup properly, your miners shares are accepted and show up in MPOs AND your crons are running at regular interval, sooner or later MPOS will pick up a generated block and pay out the users.

If any of those do not apply, check your coind, stratum and miners.

**Comment by waelboyka** [comment]
how long take the confirmation? and how long of time to pay users?

**Comment by xisi** [comment]
Depends entirely on the coin you're using and confirmation settings in your
config.

**Comment by waelboyka** [comment]
i use guncoin and confirmation in the config is 120 it atempt 120 in the miner but does'int happen in mpos
