### ISSUE TITLE
Cash out

### ISSUE THREAD

**Issue by waelboyka** [MPOS/php-mpos#2412]
i past 10 hours mining guncoin with cgminer but i can't get paid i chek account earning for 1hours it show 0.00000 so what is the problem? i use reaward system:pplns

**Comment by TheSerapher** [comment]
Duplicate issue?

Check your crons are running without errors, confirm that blocks are found and added to the coind and picked up by MPOS, check blocks are confirmed in the blockchain and in MPOS.

Most likely a hacked together coin daemon that isn't supported.

**Comment by waelboyka** [comment]
in the 10 hours i don't find a block ? do MPOS support Guncoin?

**Comment by TheSerapher** [comment]
Oh and more importantly use a compatible miner! Guncoin is Neoscrypt! A Scrypt miner will show that shares are accepted by you will never find a block! (Happened to me with Feathercoin while testing MPOS code).

**Comment by TheSerapher** [comment]
I guess my answer also answers your question. Yes, sounds like you use the wrong miner to me. Double check your settings and that your stratum is adding blocks properly. If that doesn't work already there isn't anything MPOS can do.

**Comment by waelboyka** [comment]
how i can check stratum adding blocks properly?

**Comment by TheSerapher** [comment]
Log files of stratum, coind listtransactions. But since MPOS can't see them I can assure you it's something in your stratum setup. Ask for help there or find other pools running Guncoin to get it setup. That's out of scope of MPOS.

**Comment by waelboyka** [comment]
do you have an idea about the best coin does suport MPOS and Stratum?

**Comment by waelboyka** [comment]
after mining i get 5000 shares ,i check the DB i found that table share_archives is empty and table shares is full but they have an upteam_result=N .what is the problem?

**Comment by TheSerapher** [comment]
Stratum not working properly. Looks like none of your shares are accepted.

And with over 500 coins out there I really can't tell which ones work. You have to check your stratum to see if THAT support it. MPOS doesn't care about coins much, only shares and blocks.

So before you think it's MPOS, ensure that your stratum setup works and finds blocks.

**Comment by waelboyka** [comment]
how i can know that stratum accept shares or refuse it?

**Comment by TheSerapher** [comment]
Miner and MPOS shows shares as rejected.

**Comment by waelboyka** [comment]
in the miner is show to me that shares ares accepted and MPOS also

**Comment by waelboyka** [comment]
In mpos account information it show confirmed 0 and unconfirmed 0 whthever valis shares is 5000 i cant untersdant why

**Comment by Spekske** [comment]
Guncoin is neoscrypt as already mentioned. You will need to setup your stratum to support neoscrypt or it will not work, and you will need a cgminer version that supports neoscrypt too, only version 3.7.7 and 3.7.8 have neoscrypt support.

**Comment by waelboyka** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/11723203/7375223/ff061006-edce-11e4-9b0b-fac411d4ed89.png)

**Comment by waelboyka** [comment]
is that an MPOS issue or stratum? and do you have an idea how configure stratum as neoscryt and that mpos supported

**Comment by TheSerapher** [comment]
I have said you have a stratum issue, not an MPOS issue. Take it to places that deal with stratum support to find further help. Stratum is not part of MPOS and not supported here.
