### ISSUE TITLE
run_upgrades.php for 1.0.0 to 1.0.1 fails

### ISSUE THREAD

**Issue by ctgiant** [MPOS/php-mpos#2413]
When running the run_upgrades.php script to upgrade to 1.0.1 the query fails:

- Starting database migration to version 1.0.1
-  Preparing: ALTER TABLE `dbname.coin_addresses` ADD ap_threshold float DEFAULT '0'
-    failed: Table 'dbname.dbname.coin_addresses' doesn't exist

**Comment by TheSerapher** [comment]
Looks like the shared DB name is prefixt twice.

Can you try setting the accounts DB name to an empty string?

**Comment by TheSerapher** [comment]
ACtually, try this first:
```
git checkout v1.0.1
./upgrade/run_upgrades.php
git checkout v1.0.2
./upgrade/run_upgrades.php
```

**Comment by ctgiant** [comment]
Okay.  Thanks for looking into it.  I'll wait for a fix.

**Comment by TheSerapher** [comment]
Released `1.0.3`, please try that one :-)

**Comment by ctgiant** [comment]
Thanks.  That worked!

**Comment by TheSerapher** [comment]
Thanks for the heads up, somehow I missed this.

It was caused by putting the table in in "`" (back)quotes. It prefixed the database name automatically so it was added twice (once via prefix, once by SQL).
