### ISSUE TITLE
 Your config files SHOULD NOT be writable to this user!

### ISSUE THREAD

**Issue by ropyu1978** [MPOS/php-mpos#2417]
i using admin acc logon on，see this warning!

how to solve?

**Comment by TheSerapher** [comment]
Change permissions on the configuration file so the web server user account can't overwrite it.

**Comment by ropyu1978** [comment]
how to solve it?

**Comment by TheSerapher** [comment]
Change the permissions on the file. Basic Linux command. This is out of scope of MPOS and you should read up on Linux Administration prior to running a pool. It's stated in the README and Quick Start Guide that running a pool is not an easy tasks and requires good knowledge of Linux systems, Databases and PHP Code.
