### ISSUE TITLE
neoscrypt algorithm

### ISSUE THREAD

**Issue by waelboyka** [MPOS/php-mpos#2419]
do mpos suport neoscrypt and how to configure?

**Comment by TheSerapher** [comment]
NeoScrypt works the same as Scrypt, there are no changes on how MPOS handles shares submitted by a NeoScrypt coin daemon. You have to ensure your Stratum and Miner supports it, or you will have a lot of accepted shares but no single block.

**Comment by waelboyka** [comment]
my stratum suppotrs neoscrypt so in mpos config what algrotithm must set?

**Comment by TheSerapher** [comment]
scrypt
