### ISSUE TITLE
Last login notification won't go away

### ISSUE THREAD

**Issue by suchpool** [MPOS/php-mpos#2421]
I upgraded my dev environment to the latest MPOS v 1.0.3.

I noticed that the last login IP message on top of the pool keeps appearing even after being closed. Such behavior was not occuring before, anybody would have an idea about this?

**Comment by TheSerapher** [comment]
Cannot reproduce on my test site. You may want to check you java script console for any errors. Maybe something is missing in your setup or you run a custom theme?

**Comment by suchpool** [comment]
Yes, we're running a custom theme. Will dig deeper, not sure if this was a generalized issue or not.

**Comment by TheSerapher** [comment]
Probably local issue then.
