### ISSUE TITLE
how to move mpos to other vps?

### ISSUE THREAD

**Issue by vetal20600** [MPOS/php-mpos#2422]
I am going to transfer MPOS to the new server. I will make backup of current databse. Then I will install new MPOS and deploy database there. It is enough?
My goal is to keep mining data.

**Comment by TheSerapher** [comment]
Depends in what services you are moving. I am guessing you move an entire server:

* Backup MPOS Database and Configuration
* Backup wallet.dat and configuration
* Backup stratum configuration

Move all backups to the new machine and setup the instance using those.

**Comment by vetal20600** [comment]
Thanks a lot.
