### ISSUE TITLE
Wallet does not cover AP (& MP?) payouts on equal value

### ISSUE THREAD

**Issue by xisi** [MPOS/php-mpos#2424]
reported via shawnp0wers on irc:

2015-05-21 22:35:01 - ERROR -->  Wallet does not cover AP payouts - Payout: 25.09461618 - Balance: 25.09461618

Seems to just be a comparison issue ie: 
https://github.com/MPOS/php-mpos/blob/development/cronjobs/payouts.php#L70
https://github.com/MPOS/php-mpos/blob/development/cronjobs/payouts.php#L157

edit: dug a bit deeper, daemon shows the same value as it is trying to payout, transactions same deal,  workaround was to add a bit to the wallet, from there resumed fine.

**Comment by TheSerapher** [comment]
Thanks for looking into this @xisi - It may have been caused by 0 payout fees and the wallet having to do a transfer including fees (which fails). People should check they add a transaction fee to cover these edge cases.
