### ISSUE TITLE
Move admin Checks to Admin Dashboard

### ISSUE THREAD

**Issue by TheSerapher** [MPOS/php-mpos#2427]
Maybe we should move all popups for admins into the admin dashboard as a table with things to fix and links to how to fix them instead of leaving it a popup. We could then point to the dashboard and let people see that table instead.

Would clean up the popups for new installations and give a better way to see what we actually check. Good checks could be listed as well :-)

**Comment by xisi** [comment]
I can probably take this, I've got a decent sized list of things to add and will write up nice descriptions for them all.

**Comment by TheSerapher** [comment]
That's great, thanks! I will check your PR when it's ready, maybe I have some additional ideas by then.

Was just a quick idea I had. It may be useful to add Wili pages for those helper links that we don't link across the wiki itself.

**Comment by xisi** [comment]
I am almost done with this, if you have any requests now is the time :+1:

**Comment by TheSerapher** [comment]
Awesome! Was just thinking about this issue ;-)

I'd like to make it as easy as possible to extend the admin checks. Very much like the admin settings, which creates the settings page from an array, we may look into splitting up admin checks into functions/includes that can be used easily. To add more checks, each one would need a short name, description, help link and the actual function to run the check. If those can be included dynamically and automatically on the dashboard, we'd have a clean way to expand this in the future.

**Comment by xisi** [comment]
I did it using includes (pages/admin/checks) and moved all of the current checks into that format. Using a call from a class or creating a simple model/loading would probably clean it up a good bit, and I will add field validation too - would like your input. I would like to write some additional checks as well.

**Comment by TheSerapher** [comment]
Excellent! I'd add more colors (warning yellow, critical red) and maybe one box for each check? Not sure how that would look like. It may become overloaded, so yours may be better. For variables, they should be put into a code kinda block to highlight it's  code (I think Bootstrap has something for that?). Last but not least, maybe supply an explanation what the check means without sending people to the Website?

Great work, that's exactly what I had in mind :-)

**Comment by xisi** [comment]
I will add error level ie notice/warning/omg why; colored for each type,
I can clean it up with a model/create new objects in each test, I was just worried about dealing with scoping. All of them will have longer descriptions, just haven't moved them in yet :-) Another hour or two of polish.

**Comment by TheSerapher** [comment]
I don't think we need objects for those simple checks, just make sure they can be included easily would be good enough for me. Thanks a lot man!

**Comment by xisi** [comment]
How is this? Each test will have a similar description beneath it.

I realize it's not immediately obvious but the config value listed in the pre links to the wiki page for the value/section.

![tests](http://puu.sh/iuJjy/3640594491.png)

**Comment by TheSerapher** [comment]
That's great! Love it.

**Comment by xisi** [comment]
That's all the current tests with extended descriptions. Open to input on the wording/etc, and new test ideas.

**Comment by TheSerapher** [comment]
It's like you read my mind :-) Good stuff, wording is fine. If you commit a PR please update the CHANGELOG as well and point it against development. Once I get a chance I will test it out myself!

**Comment by TheSerapher** [comment]
https://github.com/xisi/php-mpos/blob/29f879a9c1bdd77f69c33c2eea93b283bdaa4d73/include/pages/admin/setup.inc.php#L30-L36

I think it would be way easier to work with http://php.net/manual/de/function.glob.php

Returns only the files matching a pattern, no need to do file name parsing to find the proper files.

**Comment by TheSerapher** [comment]
We should somehow indicate that a coin daemon needs to fully sync before the software is fully usable.

**Comment by xisi** [comment]
For the stratum/daemon checks maybe?

**Comment by TheSerapher** [comment]
Good idea, usually that one won't work until fully synced.

**Comment by xisi** [comment]
Noted it in the daemon/stratum checks.

**Comment by TheSerapher** [comment]
Will try it out sometime this weekend. Merged into development in case others are willing to test it.

**Comment by TheSerapher** [comment]
Tested it out, the only change I can think of is placing the `To disable these checks, set skip_config_tests to true in global.inc.php` string at the footer of the box instead of in the header.

**Comment by TheSerapher** [comment]
Merged into master (with already existing merged data that I didn't pay attention to). We have now made it 1.0.4.
