### ISSUE TITLE
blocks with no worker

### ISSUE THREAD

**Issue by jjj092353** [MPOS/php-mpos#2428]
I have an odd problem in that there are a few blocks that were added to the blocks table with no worker or use id assignment.

I have tried deleting them, but after I force a run of the cron jobs they re-appear.

are there shares out there that are adding these block so the table - they keep re-appearing and I can;t get rid of them

thanks

**Comment by TheSerapher** [comment]
Issue happens if shares are not added in order and get included in other rounds. Can be fixed by marking those blocks as paid out but using a pool bonus to even out the miners losses.

**Comment by jjj092353** [comment]
so all I have to is set accounted = 1 - what about account_id, worker_name, shares and shared_id fields?

thanks

**Comment by jjj092353** [comment]
in addition there are no shares in the tables for any of the four blocks.

do I have to manually creates shares to each of the blocks?

**Comment by TheSerapher** [comment]
As I said, mark as accounted (as you did) and payout a pool bonus so everybody gets a payout for those unaccounted blocks. Don't adding shares to them.

**Comment by jjj092353** [comment]
I did that and it still throws the exact same error.

**Comment by jjj092353** [comment]
there is no account_id in these records, workers_names, shares or share_id

**Comment by TheSerapher** [comment]
Correct but MPOS ignores them when trying to do payouts or share assignments.

**Comment by TheSerapher** [comment]
Basically you marked them to be ignored for all payouts. Hence the additional bonus payout to pool users since they didn't really get paid for them.

**Comment by jjj092353** [comment]
I can handle the payout - however - cron jobs will not run because it keeps throwing this error:

I can get past this:

2015-05-26 16:41:34 - INFO --> | Block ID |     Height |          Amount |   Share ID |                    Shares | Finder          | Worker          |               Type |
2015-05-26 16:41:34 - ERROR --> E0001: The block with height 15371 found share 398 which is < than 900611 of block 14987.
2015-05-26 16:41:34 - CRIT --> E0002: Failed to fetch both offending shares 398 and 900611. Block height: 15371

**Comment by TheSerapher** [comment]
You have truncated the shares table. That has reset ALL share IDs to < 900611 which was the last used one for block 14987. You may recover from this by assigning share 398 to block 15471 by hand. It may pick up from where it left off then.

That’s all advice I can think of short of logging in myself and fixing it for you (which I am not).

**Comment by jjj092353** [comment]
thanks but this does not make sense since share 398 is already assigned to block 15371, both have : 953f2d9f8c8d06fb4c95efaf079b31c88dd1da34e5e31f3216c1a462e66a9627

**Comment by jjj092353** [comment]
since this is such a mess is there a way just to delete the block affected, shares and transactions contributing to these blocks and let the system somehow pick up  or should I just nuke the tables and pay the people out manually from the wallet.

**Comment by jjj092353** [comment]
can I email you or you email me? I have a problem and this problem is spreading to other pools on my server. it started with one pool and now 3 pools have the same problem with the shares table appears to have been somehow truncated and the shares have id's starting with 1 - I will pay for you help - jjj092353@gmail.com

**Comment by TheSerapher** [comment]
If you have shares duplicating solutions for blocks it sounds like a chain fork. Would be super unlucky to have it on three blocks at the same time but who knows with so many shitty coin forks out there. They may have forked the code including a coin fork ;-)

I am not doing paid support. You can try the Bitcoin forum, it may be you are lucky and find someone to clean it all up. But you gotta have a trustworthy one. Maybe @joey will help you out, he has done paid support in the past.

You may have noticed that running a pool is not as easy as this software makes it look. It tries to catch as many error cases as possible but simple bad maintained coin code - can't do much about that, sorry.
