### ISSUE TITLE
problem..

### ISSUE THREAD

**Issue by jjj092353** [MPOS/php-mpos#2429]
I'm not sure how to handle this

so all I have to is set accounted = 1 - what about account_id, worker_name, shares and shared_id fields?

I have 4,800 records in the shares table - I assume these shares are for the fours blocks that have no account_id

how do I go about attributing the shares for the four blocks. 

thanks

**Comment by TheSerapher** [comment]
You have a ticket open, it has been answered. It's a easy workaround for those blocks without proper share assignments.

**Comment by jjj092353** [comment]
your solution simply does not work. they're marked at accounted=1 and cron job still throws exact same error - over and over.

**Comment by TheSerapher** [comment]
Then check you accounted the proper blocks and force a run once cleared up the blocks table. Also make sure you don't run into a chain fork! You will have duplicate blocks then - which gets really messy to clean up.

**Comment by jjj092353** [comment]
no luck at all

I have set all the block accounted=1 and then went in an even changed last_account_block_id to 331 (which is the most recent block listed with a NULL account_id and I heelp getting the same error message when forcing the crons job to run.

2015-05-26 16:41:34 - INFO --> | Block ID |     Height |          Amount |   Share ID |                    Shares | Finder          | Worker          |               Type |
2015-05-26 16:41:34 - ERROR --> E0001: The block with height 15371 found share 398 which is < than 900611 of block 14987.
2015-05-26 16:41:34 - CRIT --> E0002: Failed to fetch both offending shares 398 and 900611. Block height: 15371

**Comment by TheSerapher** [comment]
You could try setting block share IDs to 1 for all blocks that have been accounted properly. Maybe that will make it skip them to ensure that the new low IDs are not causing issues.

Out of interest, is this some sort of multipool logging shares for many blocks into a single table?

**Comment by jjj092353** [comment]
no -we are not logging multipool shares into one table. We do have 50 mpos instances on one server and even though the mysql database has been turned pretty for speed we still get a lot of entries in the slow-queries log. I will try your suggestion. ps: Joey has a new job and in in San Francisco now but I messaged him on facebook - thanks

**Comment by TheSerapher** [comment]
Yep but sadly there are no more optimization a that I can do without losing the cool statistical data supplied by MPOS :-) Could help to just give high traffic instances their own database server. I hear that the FEDERATED table can link accounts into other remote DBs ;-)

And I would investigate why the shares rotated so early. It should be set to BIGINT unsigned and hence have plenty of room to grow. Unless you run very old instances ...

**Comment by jjj092353** [comment]
all code downloaded just 10 weeks ago. Id in the shares table is INT though - so I'll update it and in shares_archive to bigint however my eac pool gets a ton of activity and has never shown this problem

**Comment by jjj092353** [comment]
mistake - it is bigint(30) - I was looking at the block tables

**Comment by jjj092353** [comment]
my concvern however at this point is that (unless I'm wrong) all record written into the shares file from now on in these pools will have the incorrect ID - is that correct?

**Comment by jjj092353** [comment]
I think there pools need to have their blocks, shares, transactions and share-archive tables cleared out - correct?

**Comment by TheSerapher** [comment]
Share IDs are not *wrong* per say, they are just low again.

I think just setting all old blocks to a share ID to 1 should do the trick. MPOS will compare all newer blocks against those older blocks and double check that the new share ID is > 1 of the last old block.

As for other tables, they should not be affected by much. Maybe the archive, since it's the only one keeping an exact copy of each share (including the indexed share_id from shares table). All other use lose reference for them.

So try tricking the blocks table first and MPOS picking up rounds again, then go from there.

**Comment by jjj092353** [comment]
no - the shares tables picked up right where it left off assigning id's in sequence that are much lower than the id's in the shares_arvhives file.

**Comment by TheSerapher** [comment]
Truncate the archive then. The Share ID field seems to have rotated. Can happen but I find it strange it happened on three tables. Would also be cause by a truncate but I am sure you didn't do that.

**Comment by jjj092353** [comment]
I'm very careful with the table. I'm concerned that possible a slow query may have caused the problem and timed out.

**Comment by jjj092353** [comment]
didn't work - the shares tables want to start at 1 - I'm going nuke all tables - blocks, transactions, shares and shares archives and try again.

**Comment by TheSerapher** [comment]
It couldn't be a slow query. Auto increments don't break like that. I am sure it could have been fixed because others had those rollovers and could recover from it. Maybe something else broke for you, though I couldn't say what. I would guess it could be related to 50 instances running in the same data table and customized code, but that's just a wild guess.
