### ISSUE TITLE
MPOS show blank page on dashboard

### ISSUE THREAD

**Issue by prr0** [MPOS/php-mpos#2435]
Hi guys after a reboot of my mpos server the dashboard page appear blank, all other pages show info as normal

what can I check to solve this issue?

thanks for your time

Omar

**Comment by TheSerapher** [comment]
Internal server errors are logged in the error logs of Apache.

**Comment by XxSHERLOCKxX** [comment]
I've the same problem and on logs of Apache I find this :

PHP Fatal error:  Call to undefined method mysqli_stmt::get_result() in /home/sherlock/mpos/include/classes/base.class.php on line 174

The solution is to install the package php5-mysqlnd but it delete php5-mysql, and we found another error... 
Can you help me please :'( ?

**Comment by TheSerapher** [comment]
You only need php5-mysqlnd. If you have another website running on the ole php5-MySQL module try to find an updated version for it. That error is caused by not running mysqlnd. Restart Apache after you install it.

**Comment by XxSHERLOCKxX** [comment]
Yes it works ! tanks you very much ;-)
