### ISSUE TITLE
How to setup MPOS to use postfix instead of sendmail

### ISSUE THREAD

**Issue by prr0** [MPOS/php-mpos#2436]
I configure a postfix server to send mails from my MPOS box, I test sen mails from command line and every thing works find, but can't make MPOS to send mail using postfix

Any help with this will be appreciated

Regards

Omar

**Comment by TheSerapher** [comment]
That's a configuration issue of some kind. The default setup assumes postfix is installed. Make sure MPOS is configured correctly and the sendmail binary works.

This was referenced in the Wiki:
https://rtcamp.com/tutorials/linux/ubuntu-postfix-gmail-smtp/

**Comment by AndreyNag** [comment]
Hi. I have configured postfix on my pool. Mail have sended by hand, but automaticly dont send.
Where are the log about how postfix work or doesn`t work. I want to debug.
Thanks.
