### ISSUE TITLE
Need help MPOS error Connection refused

### ISSUE THREAD

**Issue by prr0** [MPOS/php-mpos#2438]
Hi guys,

This is a port issue for sure but can't solve it, MPOS is givinig me this error:

We tried to poke your Stratum server using your $config['gettingstarted'] settings but it didn't respond - Connection refused

I have the same port on ~/.bitcoin/bitcoin.conf, on ~/stratum-mining/config.py and on /var/www/html/MPOS/include/config/global.inc.php, I reboot the box and start every thing and still MPOS can't connect

I try using different port numbers and same result

Any help will be welcome

Regards

**Comment by TheSerapher** [comment]
Wait for the chain to be synced. Can take hours for Bitcoin.

**Comment by prr0** [comment]
Thank you, as soon as the blockchain was in sycn every thing start to work as normal
