### ISSUE TITLE
Default hostname for email confirmations. 

### ISSUE THREAD

**Issue by whattheflux** [MPOS/php-mpos#2439]
Just wondering where does the email template for account details change pull the URL from? No matter how many times I change my /etc/hosts the email still sends out a raw ip as the domain. Any thoughts? My setup is configured exactly as per the wiki. Thanks!

**Comment by TheSerapher** [comment]
https://github.com/MPOS/php-mpos/blob/master/templates/mail/password/reset.tpl#L5

PHPs SERVER_NAME is used, so make sure you VHost ServerName is setup properly and its properly passed to the PHP interpreter.
