### ISSUE TITLE
INFO mining # Failed worker authorization: IP

### ISSUE THREAD

**Issue by lahlor** [MPOS/php-mpos#2445]
Hi,

I am running now my second pool and shared the database tables. I were able to setup the second MPOS without any issues and I am able to login with my users out of the databse. But if Iam starting mining with stratum I getting "INFO mining # Failed worker authorization: IP " from the stratum log.
I setup the stratum to look into the master database of the second pool. But as you know the workerdata is in the shared database. So finally what have I to do that my stratum works with the pool and the shared database?

Cheers
lahlor

**Comment by TheSerapher** [comment]
There is no stratum supporting this model out of the box. You have to adjust the source code of your stratum to change the account lookup to check the table in the shared DB. Can't be of more help than that I am afraid.
