### ISSUE TITLE
Docker testing version

### ISSUE THREAD

**Issue by nrpatten** [MPOS/php-mpos#2450]
I'm currently building a docker version of MPOS to work in a container. I'm thinking this will be a good idea for people to play and workout how MPOS and a Coind > Stratum work.

So far i have got apache2, php, mysql, MPOS working need to get Coind and Stratum built in the container to so its a fully working pool.

This is a side project so i will work on it when i have time.. If anyone would like to help comment in this issue only.

Built on Ubuntu 12.04 Apache/2.4.12,  (Ubuntu) PHP 5.5.26,  mysql  Ver 14.14 Distrib 5.5.43

**Comment by TheSerapher** [comment]
Excellent! Let me know once I can pull an image and test it out :-)

**Comment by nrpatten** [comment]
So far
![docker](https://cloud.githubusercontent.com/assets/4833541/8615034/aa565348-2732-11e5-810c-7b2d793aebfa.jpg)

**Comment by nrpatten** [comment]
Git repo and docker repo
Build
`git clone https://github.com/nrpatten/mpos-docker mpos`
`cd mpos`
`docker pull nrpatten/ubuntu-mpos-base`

pull full version
`docker pull nrpatten/mpos`

**Comment by nrpatten** [comment]
Quick fix for MPOS table path in the container for both git and docker pulls.
Remove `/var/www/html/mpos/sql/000_base_structure.sql`
Add `/var/www/mpos/sql/000_base_structure.sql`

**Comment by nrpatten** [comment]
@TheSerapher got a full version working only thing thats not done is crontabs..

Git repo and docker repo
* Build
* `git clone https://github.com/nrpatten/mpos-docker mpos`
* `cd mpos`
* `docker pull nrpatten/ubuntu-mpos-base`
* `docker build -t nrpatten/mpos .`
* `docker run -itd -p 80:80 -p 3333:3333 nrpatten/mpos`
* To log into the container run
* ssh docker ip `username: root`  `pass: root`
* Or run:
* `docker ps`
* And add your `CONTAINER ID`
* eg: `docker exec -it 013ca0ec7315 /bin/bash`

There may be bugs but i dont have a working miner anymore to test stratum but the log looks good to me..

**Comment by TheSerapher** [comment]
Your image is on a private subnet: https://192.168.59.103:2376/ - can't download ;-)

Looks good. You may want to put a message on the news screen stating that all data will be lost as soon as the box is destroyed.

**Comment by nrpatten** [comment]
Hmm strange you can't get the image i installed another VPS to test the build and it works with out issue for me, You only have to log into the container and manually start memcached untill i get some time to add it to the the Dockerfile..

The image is on Docker Hub > https://registry.hub.docker.com/u/nrpatten/ubuntu-mpos-base/

Added "Please note all data will be lost if you destroy this container." on the news screen. on mpos.gitbox.link

**Comment by TheSerapher** [comment]
Silly me. Should have started boot2docker ;-) Sorry for that.

**Comment by nrpatten** [comment]
lol re pull the git repo and rebuild just updated with memcached

**Comment by TheSerapher** [comment]
Yep, seems to work. I can't test it all right but it started and I can see all services running. Good job!

**Comment by nrpatten** [comment]
All good mate :)
Just made a Docker "AUTOMATED BUILD REPOSITORY"
https://registry.hub.docker.com/u/nrpatten/mpos-docker/

**Comment by TheSerapher** [comment]
Thanks man, I will close this ticket for now but feel free to update the Wiki here with a documentation or link to your own documentation in that repo. It should give people a very easy way to get in touch with MPOS and how things work together.

**Comment by nrpatten** [comment]
No probs, i edited the wiki with a MPOS Docker page and the main page adding a link to the wiki page under pools running MPOS..

**Comment by nrpatten** [comment]
Well seems to be a hit already  read the comments > https://registry.hub.docker.com/u/nrpatten/mpos-docker/

**Comment by TheSerapher** [comment]
Scary. People plan to run it in a container :D Imagine a pool running well and then the containers die, all data is gone!

**Comment by nrpatten** [comment]
lol :+1:

**Comment by TheSerapher** [comment]
Next step: Make it a distributed setup with Database host, Memcache Host, Stratum node, Coin Daemon, MPOS Interface - all in different containers :D
