### ISSUE TITLE
Question about litecoin branch 0.10.x

### ISSUE THREAD

**Issue by cpo** [MPOS/php-mpos#2455]
Apparently (if I'm informed correctly) the rpc interface for 0.10.x has changed, does mpos know how to handle this? And if so, starting from what version?

Thanks!

Chris

**Comment by TheSerapher** [comment]
I have not read about any breaking changes. Would have to check. But I know Bitcoin is working fine on the 0.10.x version so I would assume Litecoin is similar.

**Comment by TheSerapher** [comment]
The only thing changed is how to talk to litecoind:

 litecoind no longer sends RPC commands. You must use the separate litecoin-cli command line utility.

**Comment by TheSerapher** [comment]
And since I hit send too quickly, this does not affect how MPOS talks with the RPC. It still uses RPC-XML via TCP socket.

**Comment by cpo** [comment]
Ok, cool! That's the thing I noticed, that the rpc stuff was gone from the main executable. Now it all comes back to me :)
Chris

**Comment by TheSerapher** [comment]
10 seconds Google foo could have replaced a ticket ;-) But good to know! Had no idea they did that even when recently testing 0.10.x since I never run command line RPC commands. It's mostly MPOS stuff I have to test ;-)

**Comment by Traffim** [comment]
Stratum-mining not support the latest versions of BTC and LTC ?
# bitcoin-cli getwork
error: {"code":-32601,"message":"Method not found"}

**Comment by TheSerapher** [comment]
MPOS doesn't care about  the getwork implementation and nor does Stratum. That's more of a mining client issue. You won't be able to use a getwork only client anymore unless adding a proxy.

I have a Litecoin testnet running on 0.11.2.2 which works fine.

**Comment by TheSerapher** [comment]
I am using the node.js stratum by the way.
