### ISSUE TITLE
adding specific coin test to bitcoinwrapper.class.php

### ISSUE THREAD

**Issue by jjj092353** [MPOS/php-mpos#2456]
I share the classes directory between multiple pools on my pool website and since I need to modify this code to obtain the network hash for HBN properly is there a way to test the coin ticker in this code so that I can put in special code that only get executed for ticker HBN and all other coins uses the standard code your distribute?

thanks in advance

**Comment by TheSerapher** [comment]
`$config['currency']` holds your currency. You can read that in most classes via `$this->config['currency']`.  You could try using that or passing it into the class where you need it.

What is the proper way to read HBN network hash rate properly? Maybe this can be added to the base code at https://github.com/MPOS/php-mpos/blob/master/include/classes/bitcoinwrapper.class.php#L69-L95
