### ISSUE TITLE
ethereum for MPOS

### ISSUE THREAD

**Issue by mmitech** [MPOS/php-mpos#2459]
Hi,
 Ethereum seems to be doing well, and I think it has some real potential, I am curious about how much work is needed to make MPOS Ethereum compatible...

I saw a few MPOS pools out there with ethereum support, I would like to know if there is any open source code out there for Ethereum pool mining, if not, how much work is needed to make a MPOS fork for ethereum? 

MPOS pools with Ethereum support:
https://eth.suprnova.cc/index.php
https://www2.coinmine.pl/eth/

Join the discussion https://bitcointalk.org/index.php?topic=1169282.0

**Comment by TheSerapher** [comment]
All coins are supported as long as they do the old fashioned share system. If MPOS needs adjustments to support it, those can be accepted via PR as long as they don't break any existing coins.

**Comment by TheSerapher** [comment]
As far as I can tell the core works the same as any other crypto coin out there. It's a regular blockchain which needs to be computed. Computation happens in Stratum. So if your stratum is able to create shares based on the Eth blockchain, MPOS will support it.

Try to find a stratum and make a test setup and I'd imagine it'll work out of the box.
