### ISSUE TITLE
Hashrate denominations

### ISSUE THREAD

**Issue by sixxkilur** [MPOS/php-mpos#2461]
The current MPOS does not support higher hashrates on the dashboard. I have forked the project and altered the files to support the following.
Update smarty_globals.inc.php to include higher hashrate denominations
Added PH/s and EH/s to Small helper arrray

Update admin_settings.inc.php to include higher hashrate denominations
Added PH/s and EH/s to Network Hashrate Modifier settings

**Comment by TheSerapher** [comment]
If you have a PR place it against Development and I shall check it out :-)

**Comment by sixxkilur** [comment]
I am new to this contributing deal so I am unsure if I did it correctly I created a pull request and then there was a merge with master option. I assumed you would have to approve the merge so I do not know if it was done correctly or not.

**Comment by TheSerapher** [comment]
Try again, the PR didn't reach my repository. Also make sure you make your changes to the development branch and push that for a PR. Master is the stable one, which should not receive any merges.

```git checkout development
git pull
[edit files]
git add <files>
git commit -m '[#2461] Added Hasrate modifiers
git push origin development
```

Then create the PR with the change you should see in Github.

**Comment by TheSerapher** [comment]
Hey again,

I could do this for you (by checking the change from your fork) but I'd like you to try and do it since it would show you as a contributor in my Repository. Just to make sure people know it was you ;-)

**Comment by jonnybravo0311** [comment]
Well, since it's been an open issue from September, 2015, I figured I'd make the changes (which I had already done locally for my pool) and create the PR #2487

**Comment by TheSerapher** [comment]
Closing since merged (sadly into master again but I doubt this matters for anyone if they properly use tagged versions :-))
