### ISSUE TITLE
Slightly Unclear Time -- Units of Measure

### ISSUE THREAD

**Issue by turnkit** [MPOS/php-mpos#2463]
I've seen some MPOS dashboard est. avg. time per block shown as nn:nn:nn and others as "hh hours and mm minutes" but predominantly the former.  It's not clear to those using the systems showing nn:nn:nn if this is dd:hh:mm or hh:mm:ss.

(Also it would be nice if there were an Estimated Next Change: Date & Time.)
(And also for Cryptocurrencies with different block sizes apparently this stat is just always incorrect -? See: https://www.reddit.com/r/defcoin/comments/3cr2wd/defcoin_difficulty_does_not_retarget_every_2016/)

![unclear unit of measure welcome to defcoin us - dashboard_2015-10-01_10-37-45](https://cloud.githubusercontent.com/assets/4126167/10225573/123f129c-6829-11e5-9e55-4eda92d48062.png)

**Comment by TheSerapher** [comment]
Retarget estimates are rather moot nowadays. Many different coins use many different algorithms today which are retargeting at every block. It's not possible to port each algorithm into PHP. If there were a coin API to as for this that would be best but alas that doesn't exist in any implementation.

I agree on the time estimates but those are wildly different across coins as well. Simply checking what the estimate is and knowing what the time per block is would make this a little clearer but I don't want to mess about with this. There are, again, way too many coins and possible estimates out there. Also times differ based on what you look at. But in general all nn:nn:non should have the same meaning.

**Comment by TheSerapher** [comment]
Sorry for closing this outright but I don't think I'd be able to work on this. Open to suggestions though, maybe there is some simple way to make it better.

**Comment by turnkit** [comment]
Thanks for replying.  Adding "hours and minutes" though as a default does
seem like it would increase the usability.  As it is now I think it's a bit
confusing for new users.

On Thu, Oct 1, 2015 at 11:42 AM, Sebastian Grewe <notifications@github.com>
wrote:

> Sorry for closing this outright but I don't think I'd be able to work on
> this. Open to suggestions though, maybe there is some simple way to make it
> better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MPOS/php-mpos/issues/2463#issuecomment-144782684>.
>



-- 
David C. Sutherland   |  (310) 729-6411 (c)  |  Lindale, Texas

**Comment by TheSerapher** [comment]
How about a footnote? The reason it wasn't added to the box is rather simple: it would mess up the box layout. The one box already having two lines stands out already, I was hesitant to add yet another.

At the table footer is still some room, or we add a small (?) as a Simple hover text.

**Comment by turnkit** [comment]
yeah, even if in small print underneath it shows "Time shown is in
hh:mm:ss" or "Units are dd:hh:mm:ss" or whatever, that would be very
helpful.

On Thu, Oct 1, 2015 at 11:48 AM, Sebastian Grewe <notifications@github.com>
wrote:

> How about a footnote? The reason it wasn't added to the box is rather
> simple: it would mess up the box layout. The one box already having two
> lines stands out already, I was hesitant to add yet another.
>
> At the table footer is still some room, or we add a small (?) as a Simple
> hover text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MPOS/php-mpos/issues/2463#issuecomment-144784000>.
>



-- 
David C. Sutherland   |  (310) 729-6411 (c)  |  Lindale, Texas

**Comment by turnkit** [comment]
In some ways, this is even better...

On Thu, Oct 1, 2015 at 1:34 PM, David Sutherland <turnkit@gmail.com> wrote:

> yeah, even if in small print underneath it shows "Time shown is in
> hh:mm:ss" or "Units are dd:hh:mm:ss" or whatever, that would be very
> helpful.
>
> On Thu, Oct 1, 2015 at 11:48 AM, Sebastian Grewe <notifications@github.com
> > wrote:
>
>> How about a footnote? The reason it wasn't added to the box is rather
>> simple: it would mess up the box layout. The one box already having two
>> lines stands out already, I was hesitant to add yet another.
>>
>> At the table footer is still some room, or we add a small (?) as a Simple
>> hover text.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MPOS/php-mpos/issues/2463#issuecomment-144784000>.
>>
>
>
>
> --
> David C. Sutherland   |  (310) 729-6411 (c)  |  Lindale, Texas
>



-- 
David C. Sutherland   |  (310) 729-6411 (c)  |  Lindale, Texas
