### ISSUE TITLE
mpos update block info,the finder was wrong,not real finder 

### ISSUE THREAD

**Issue by saymissme** [MPOS/php-mpos#2465]
those day
mpos pool add new blocks to database
the finder not the  real miner

i checked mysql, the share_id is not real from shares  table
how to fix it?

**Comment by TheSerapher** [comment]
Not sure what you mean but it could mean that you had a chain fork. In that case blocks will be duplicates and MPOS will have issues assigning valid shares to them.

Also if you are solo mining into the wallet a block found will have no share for it and MPOS fails.

If this is a valid block and you have valid shares for it you could simply mark it as laid (accounted column) and then pay miners a bonus to even out the lost income from that block.

**Comment by saymissme** [comment]
http://www.idcray.com/pool/shares.jpg
http://www.idcray.com/pool/block.jpg

like this

we found two blocks
the share_id is 14778 and 14755 in Block table
but in the Shares table  ID is 14781 and 14791
they are different

so the block finder was changed

**Comment by saymissme** [comment]
@TheSerapher
