### ISSUE TITLE
[BUG]block finder was changed

### ISSUE THREAD

**Issue by saymissme** [MPOS/php-mpos#2466]
http://www.idcray.com/pool/shares.jpg
http://www.idcray.com/pool/block.jpg

like this

we found two blocks
the share_id is 14778 and 14755 in Block table
but in the Shares table ID is 14781 and 14791
they are different

so the block finder was changed
how to fix it?

**Comment by TheSerapher** [comment]
The shares from the shares table are not real block shares (upstream_result = N). If you are certain these are the block shares just assign them to those blocks.

At the same time go and check if your block chain had a hard fork. Those are the most common reason for issues in MPOS.

And last but not least your coin stratum may not insert the solved block hash into the finding share. MPOS will fall back to various other search mechanisms which are not as reliable as the block hash checksum in the share field.

And if all fails, mark those blocks as accounted for and MPOS will skip them. If they keep showing up you have a hard fork in your chain and you need to clean up the chain before deleting all blocks after the fork occurred.

**Comment by TheSerapher** [comment]
I am now unavailable for two weeks (vacations and no internet - used a hotspot). Maybe someone else can help further if required.

**Comment by saymissme** [comment]
why mpos cant record the real shares_id for new blocks?
need update mysql,or not?

**Comment by TheSerapher** [comment]
Stratum, not MPOS. This is an issue with your coin daemon and stratum. Only once shares are inserted by you stratum server MPOS comes into play.

That's not fixable in MPOS. It has a lot of fallbacks in case stratum doesn't work as expected and the least favorable method to assigning a share is using any share that has about the same timestamp as the block. Bad way but the only left if all else failed.
