### ISSUE TITLE
 Database version mismatch (Installed: , Current: 1.0.1). Database update required, please import any new SQL files. Cronjobs have been halted. 

### ISSUE THREAD

**Issue by mahuaroy** [MPOS/php-mpos#2468]
Dear Sir / Madam,

Installed new mpos today.

After installation  Database version mismatch (Installed: , Current: 1.0.1). Database update required, please import any new SQL files. Cronjobs have been halted. 

Please give me some details about this.

Regards.

**Comment by mahuaroy** [comment]
Dear Sir.
It is working.
Thanks

Regards.

**Comment by TheSerapher** [comment]
Please refrain from sending email to my address when no reply is posted to your issue right away. You will get an answer eventually.

And as it turns out it was not an issue with MPOS. Please double check your setup steps when finding issues like those ;-)

**Comment by djxs2000** [comment]
Was this solved?
I'm having exactly this issue...

**Comment by TheSerapher** [comment]
Just checked the base import file and it has the proper version in it. New installations should work if properly installed.
