### ISSUE TITLE
PPLNS settings and change to all users kh/s to gh/s or th/s

### ISSUE THREAD

**Issue by AsicTrade** [MPOS/php-mpos#2469]
Good day to you
I have some questions about the setup of this configuration
I need help to set up this menu)

$config['pplns']['shares']['default'] = 4000000;
$config['pplns']['shares']['type'] = 'blockavg';
$config['pplns']['blockavg']['blockcount'] = 10;
$config['pplns']['reverse_payout'] = true;
$config['pplns']['dynamic']['percent'] = 30;

If i put the number of blocks 10 then $config['pplns']['shares']['default'] = will be applied? This amount will generally be to participate?

If I want to bring so considered in the past for example 100 blocks to me in the standard configuration should be changed only 10 > 100? no more need to change?

I need to set up a coin for example novacoin, how do I properly configure that-be made based on the average amount of for example 100 blocks? Maybe you can help me with this?

and I want to remake the map hashrate participants. How can I do that? need change kh/s to gh/s or th/s

**Comment by AsicTrade** [comment]
and I want to remake the map hashrate participants. How can I do that? need change kh/s to gh/s or th/s

**Comment by TheSerapher** [comment]
If you set type to `blockag` the default will not be used at all. It will wait until the first block is found and then use that as the first guidance for the share count. After the first block each additional block will be averaged up to `blockcount` blocks. Then averages are used for the past `blockcount` blocks.

Change your hash rate display for pool, network and personal hash rates in the `Admin Settings` menu through the webfrontend (`Statistics` tab IIRC).

**Comment by AsicTrade** [comment]
In /MPOS/templates/bootstrap/statistics/pool/contributors_hashrate.tpl need change Kh/s to Gh/s or Th/s
