### ISSUE TITLE
Blocks not confirming

### ISSUE THREAD

**Issue by DenisePalin** [MPOS/php-mpos#2470]
Blocks are not confirming on our pool as shown by the blocks stats page.

http://pool.applebyte.me/index.php?page=statistics&action=blocks

We had an issue where the wallet had become so bloated it was 750MB and was lagging the whole server to the point where it would no longer mine. We created a new wallet and imported the private keys. The pool is back up and miners can mine but new blocks are no longer being confirmed. There were two addresses moved over which were the only two addresses reported by the following command.

getaddressesbyaccount ''

This bought the balance over and the wallet behaved again but now we have this new problem with blocks. Nothing else has changed. Any help with this would be appreciated.

EDIT: Reading through the setup docs and the address defined in stratum-mining/conf/config.py is one of the two addresses imported. Probably the address which actually had the balance.

EDIT 2: So moving wallet we do not have the old blocks so they will never be confirmed. To brute force fix this I changed the confirmations columns to 120 in the blocks table. All blocks now shows as confirmed, the payout ran for ages and paid out a massive amount of coins. I guess that orphans got confirmed as well. Now waiting to see if new blocks behave, if so I will close this ticket. If not then I'll be back.

**Comment by DenisePalin** [comment]
Please assist. New blocks are still not confirming. Old blocks only confirmed as I did so manually in the database as described in EDIT2 in my post above.

**Comment by daygle** [comment]
Seems like you haven't setup the cron? Try following instructions here - https://github.com/MPOS/php-mpos/wiki/Cronjobs.

**Comment by DenisePalin** [comment]
Cron is running, I double checked following that guide. Here is the ourput of `crontab -e` for root.
```
MAILTO=""
* * * * * /var/www/MPOS/cronjobs/run-statistics.sh -d ABY
* * * * * /var/www/MPOS/cronjobs/run-payout.sh -d ABY
* * * * * /var/www/MPOS/cronjobs/run-maintenance.sh -d ABY
```
Here is the last few minutes of syslog.

```
Nov  4 14:14:01 applebytepool CRON[18062]: (root) CMD (/var/www/MPOS/cronjobs/run-statistics.sh -d ABY)
Nov  4 14:14:01 applebytepool CRON[18063]: (root) CMD (/var/www/MPOS/cronjobs/run-maintenance.sh -d ABY)
Nov  4 14:14:01 applebytepool CRON[18064]: (root) CMD (/var/www/MPOS/cronjobs/run-payout.sh -d ABY)
Nov  4 14:15:01 applebytepool CRON[18122]: (root) CMD (/var/www/MPOS/cronjobs/run-maintenance.sh -d ABY)
Nov  4 14:15:01 applebytepool CRON[18124]: (root) CMD (/var/www/MPOS/cronjobs/run-payout.sh -d ABY)
Nov  4 14:15:01 applebytepool CRON[18128]: (root) CMD (/var/www/MPOS/cronjobs/run-statistics.sh -d ABY)
Nov  4 14:16:01 applebytepool CRON[18185]: (root) CMD (/var/www/MPOS/cronjobs/run-maintenance.sh -d ABY)
Nov  4 14:16:01 applebytepool CRON[18186]: (root) CMD (/var/www/MPOS/cronjobs/run-statistics.sh -d ABY)
Nov  4 14:16:01 applebytepool CRON[18187]: (root) CMD (/var/www/MPOS/cronjobs/run-payout.sh -d ABY)
Nov  4 14:17:01 applebytepool CRON[18243]: (root) CMD (/var/www/MPOS/cronjobs/run-payout.sh -d ABY)
Nov  4 14:17:01 applebytepool CRON[18247]: (root) CMD (/var/www/MPOS/cronjobs/run-maintenance.sh -d ABY)
Nov  4 14:17:01 applebytepool CRON[18249]: (root) CMD (/var/www/MPOS/cronjobs/run-statistics.sh -d ABY)
Nov  4 14:18:01 applebytepool CRON[18310]: (root) CMD (/var/www/MPOS/cronjobs/run-payout.sh -d ABY)
Nov  4 14:18:01 applebytepool CRON[18311]: (root) CMD (/var/www/MPOS/cronjobs/run-statistics.sh -d ABY)
Nov  4 14:18:01 applebytepool CRON[18312]: (root) CMD (/var/www/MPOS/cronjobs/run-maintenance.sh -d ABY)
```
It seems that the pool is going through all the motions but not updating blocks. The only change to the server was to create a new wallet on the pool with the coin address from the old wallet.

**Comment by TheSerapher** [comment]
Removing the old wallet and starting a new one removed all references for old blocks. Those will never be able to update again. You imported the address only, not the entire discovered blocks by that wallet.

This is not an issue with MPOS but with the way how the blockchain works. There is no workaround in MPOS for this and it's strongly not recommended moving wallets unless one knows the impact. If you have to move a wallet, disable the pool, wait for all blocks to confirm, then move the wallet.

**Comment by DenisePalin** [comment]
NEW BLOCKS DO NOT CONFIRM. Forget about the old blocks, I confirmed them manually.

I will quote my first response...

"Please assist. New blocks are still not confirming."
