### ISSUE TITLE
FR: user stats API for mobile support

### ISSUE THREAD

**Issue by turnkit** [MPOS/php-mpos#2472]
Feature request: would like a simple API to request user dashboard stats such that a mobile dashboard app or wallet app could gather MPOS mining dashboard info easily.

**Comment by TheSerapher** [comment]
Pretty sure much of that information is already available. Check the API docs and in case it's not up to date the API pages in include/pages/api

**Comment by TheSerapher** [comment]
Already there of course. The dashboard already uses the API to fetch all data so just hook up to that too. Requires a proper key.

There also is a MPOS app already, unless it was pulled from the store.

https://github.com/MPOS/php-mpos/blob/master/include/pages/api/getdashboarddata.inc.php

**Comment by TheSerapher** [comment]
And yes documentation is up to date. Wonder if you checked before opening this ticket ;-)

https://github.com/MPOS/php-mpos/wiki/API-Reference

**Comment by turnkit** [comment]
I didn't realize. Thank you. I'll dig more next time.
