### ISSUE TITLE
How to use two pools on the same ip?

### ISSUE THREAD

**Issue by vetal20600** [MPOS/php-mpos#2475]
I am not sure this is much related to MPOS but I hope to receive an advice here. I have two vps with the same ip. 
Let say pool 1 is using 217.1.2.3:80. 
Pool 2 is using 217.1.2.3:79.
This is how to connect miner to pool 1: ./cgminer --scrypt -o stratum+tcp://217.1.2.3:3333 -u Weblogin.WorkerName -p WorkerPassword
My question is how to connect miner to pool 2?

**Comment by TheSerapher** [comment]
This isn't related to MPOS indeed and a very basic question. Use Pool 2 IP instead of Pool 1 in your minerd. Always depends on where you stratum is running really.

**Comment by mmitech** [comment]
Use a reverse proxy to forward ports. try googling it,
