### ISSUE TITLE
Change access permissions to single API action

### ISSUE THREAD

**Issue by Aareon** [MPOS/php-mpos#2479]
This may have already been done or explained, but I haven't been able to find it anywhere.

I'd like to be able to access the getuserstatus action for any specified key without giving full admin rights to that key. Thank you.

**Comment by TheSerapher** [comment]
This is not possible. Users are not allowed to fetch information about other users.

I would strongly suggest not doing this. The status includes each users balance on their account. Exposing this information to anyone will allow attackers to search for potential targets with many coins.

**Comment by turnkit** [comment]
Some of that information is already exposed on the donors page and the
stats pages

I assume the availability of those usernames and transaction volumes has
already been considered. Users can choose to show up anonymously, which is
a big difference.

**Comment by TheSerapher** [comment]
As far as I know there is no direct public available API endpoint or website overview that shows the exact amount of coins in a users account. Donations just shows what they have donated, not what they currently have in their account.

As for your original question, there is no such system in place allowing permissions to specific API functions that would allow a user to cross check for other users unless they are admins.
