### ISSUE TITLE
Fatal error: Uncaught exception 'Swift_RfcComplianceException' 

### ISSUE THREAD

**Issue by nysky** [MPOS/php-mpos#2482]
Not sure why all of a sudden I am getting the following error when I test email.
Has anyone had this issue before? 

Fatal error: Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /home4/shw25shw/public_html/wp-content/plugins/cimy-swift-smtp/Swift/lib/classes/Swift/Mime/Headers/MailboxHeader.php:348 Stack trace: #0 /home4/shw25shw/public_html/wp-content/plugins/cimy-swift-smtp/Swift/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('') #1 /home4/shw25shw/public_html/wp-content/plugins/cimy-swift-smtp/Swift/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array) #2 /home4/shw25shw/public_html/wp-content/plugins/cimy-swift-smtp/Swift/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array) #3 /home4/shw25shw/public_html/wp-content/plugins/cimy-swift-smtp/Swift/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array) #4 /home4/shw25s in /home4/shw25shw/public_html/wp-content/plugins/cimy-swift-smtp/Swift/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 348

**Comment by TheSerapher** [comment]
Empty address? I'd say that isn't RFC conform.

**Comment by TheSerapher** [comment]
This isn't MPOS ...
