### ISSUE TITLE
blake256 algo

### ISSUE THREAD

**Issue by Webonaute** [MPOS/php-mpos#2483]
Is it possible to add the support for Decred coin using blake256 algo.

https://github.com/decred/blake256

**Comment by TheSerapher** [comment]
Maybe someone can share a working coin configuration but have you tried using the regular sha256 algorithm and see if hash rates match up?

**Comment by TheSerapher** [comment]
Doesn't look like anyone would like to share their implementation on Blake256 so closing this issue.
