### ISSUE TITLE
pushpool not insert difficulty to shares table

### ISSUE THREAD

**Issue by saymissme** [MPOS/php-mpos#2484]
i am running a pushpool for one coin
and set `"rpc.target.bits" : 32,` in my server.json
the working diff is 1.
every thing is working fine

but pushpool insert sharelog to my mysql database without difficulty info

do you know hwo to fix it?

**Comment by saymissme** [comment]
i need more difficulty port

**Comment by TheSerapher** [comment]
Since this is not an MPOS issue I am unsure if I can assist. Seems to be a pushpool problem so you should ask there. Or any other pool operator running this software. You may leave a comment on how to fix it for others.
