### ISSUE TITLE
Not able to get share of block

### ISSUE THREAD

**Issue by aryabiz** [MPOS/php-mpos#2485]
Hello,

I have just created a peercoin pool using mpos, And found a block (ID 222346) but none of the miners got there shares, When I go to Admin>wallet Info it says : 
Account- Default
Address- 
Category - Immature
Amount- 68.14000000000000056843
Confirmations - 148 (slowly increasing)
Transaction ID -  24580002...adc99878 
Time - 02/19/2016 18:14:08 

And When I do ppcoin/src# ./ppcoind getinfo
    "version" : "v0.5.1ppc.rc2-beta",
    "protocolversion" : 60005,
    "walletversion" : 60000,
   **"balance" : 0.00000000,**
    **"newmint" : 68.14000000,**
    "stake" : 0.00000000,
    "blocks" : 222493,
    "moneysupply" : 23000257.53415700,
    "connections" : 8,
    "proxy" : "",
    "ip" : "xx.xx.xx.xx",
    "difficulty" : 454673581.02571476,
    "testnet" : false,
    "keypoololdest" : 1455620454,
    "keypoolsize" : 101,
    "paytxfee" : 0.01000000,
    "errors" : ""
How to transfer these coins to miners or to wallet. Please help

**Comment by TheSerapher** [comment]
Answered: https://github.com/MPOS/php-mpos/issues/537#issuecomment-186621647
