### ISSUE TITLE
i created my pool and now i get this error 

### ISSUE THREAD

**Issue by omjanu** [MPOS/php-mpos#2489]
before this it was running properly but after 2 days my server provider stop my service and they restarted after that i am getting this error 

  We are investingating issues in the backend. Your shares and hashrate are safe and we will fix things ASAP.

Findblocks disabled, new blocks will currently not show up in the frontend
Blockupdate disabled, blocks and transactions confirmations are delayed
Payouts disabled, you will not receive any coins to your offline wallet for the time being

**Comment by TheSerapher** [comment]
Force a run, cron was killed or coin daemon was dead when the crons ran. See documentation.

**Comment by omjanu** [comment]
Which documents please can you tell me the steps

**Comment by omjanu** [comment]
The pool was created by someone else thats why i need instructions

**Comment by TheSerapher** [comment]
Read your crons log file and it will tell you how to force runs. Please also refer to the various documentation pages:

https://github.com/MPOS/php-mpos/wiki
https://github.com/MPOS/php-mpos/wiki/Cronjobs

Hint: `<script> -f`

**Comment by omjanu** [comment]
I read this all but didn't too much help so if someone can give me setp by step instructions then it will really good

**Comment by mmitech** [comment]
Find cronjobs folder in the mpos directory the run ./run-crons.sh -f

I advice you to check logs of the failing cronjob before forcing it to see why it failed in the first place.

**Comment by TheSerapher** [comment]
And I advice not running pools setup by other people without actually knowing how to operate a pool. It's better to set it up yourself, get to know all the components and make it fail to see how to recover from failures.

**Comment by omjanu** [comment]
Ok but in my directory i have unomp also how how i know why did it fail

**Comment by mmitech** [comment]
check your webserver where the mpos directory is, check in the enabled-sites (same in Apache or nginx), for logs you have to check the logs folder when you find your mpos directory.

Get help from the person who deployed the pool for you, it is not wise to run a pool if you don't have a complete understanding of how MPOS works let alone if you are not familiar with unix/Linux systems.

**Comment by TheSerapher** [comment]
I did mention why it failed: Your server was rebooted/disconnected/turned off by the ISP. You can't just reboot a MPOS machine without first stopping all services and cronjobs. If not properly stopped, cronjobs may fail and run into the issues you are seeing. You are not looking at the proper folders. Find your MPOS installation, go into the `cronjobs` folder and run `./run-crons.sh -f` which will fix your issues.

Please refrain from using this issue tracker as your HOWTO helper to make a pool work again. I can not stress this enough: Do not let others setup a pool for you. That part is the easiest step following the guides in our Wiki. The hard part comes when operating it and since you haven't done anything to set it up, you have no idea how things are working together. You may be lucky and find help in the IRC channel though I am not sure how many active users are still in there.

**Comment by omjanu** [comment]
i just have bitcoin redis-stable tmp and unomp  when i log in as root and type ls so now tell me what do i do

**Comment by TheSerapher** [comment]
Sorry, no. This is not a place to take a user by their hand showing them the basics of an installation. Find the person that setup the pool for you and ask them to fix it for you or find someone else via Bitcointalk or other channels to help you out. This is an issue tracker and not a place to ask for individual help. Sorry :-)

**Comment by omjanu** [comment]
can i use this link to make all new stuff 
http://dev.cryptolife.net/compiling-the-daemon-for-your-altcoin-in-ubuntu-linux/

**Comment by omjanu** [comment]
Can you please send me a link which will help me create bitcoin litecoin and namecoin and dash coin mining pool

**Comment by mmitech** [comment]
We can all see that you have no idea about what you are doing, you are seeking help in the wrong place, no dev is not going to help you for sure here for sure.

I can only tell you this, you even stop this pool before you find your self in a very hard situation (especially when people's money is involved) or find someone to run t for you.

For sure you can learn, no one was born with knowledge, but you are taking the wrong direction here.

**Comment by omjanu** [comment]
How do i learn can you tell me so i can learn first then i can solve this problem

**Comment by turnkit** [comment]
Cut the noise. Ban this user. This is a dev page not general help. Omanju -
please ask on bitcointalk forum.
