### ISSUE TITLE
0.0.11 -> 0.0.12 Upgrade Fix

### ISSUE THREAD

**Issue by akuma6099** [MPOS/php-mpos#2490]
I was updating my server from 0.0.6 and I hit an error during 0.0.11_to_0.0.12. Please remove the backticks surrounding $user->getTableName() on line 14.

To:      $aSql[] = "ALTER TABLE " . $user->getTableName() . " DROP `coin_address`";

The backticks result in a double up of the table name so when it executes the statement it is looking for TABLE.TABLE.accounts which fails. Removed backticks and commented out the first 2 statements. Upgrade finished through to 1.0.1

**Comment by TheSerapher** [comment]
Sorry for slacking, fixed it :) Thanks for reporting this!
