### ISSUE TITLE
Annoying sound in dashboard

### ISSUE THREAD

**Issue by tupieurods** [MPOS/php-mpos#2493]
Can you please add an ability to disable that "block found" sound from account settings? Or at least remember its state between dasboard page refresh? Because it is so annoying. And when i have many pools opened, it is like tortures.

**Comment by iAmShorty** [comment]
Try this #2510

**Comment by TheSerapher** [comment]
Was merged into the development branch so feel free to try it out there. Will be merged into master someday.
