### ISSUE TITLE
No module named twisted.websocket

### ISSUE THREAD

**Issue by vetal20600** [MPOS/php-mpos#2494]
Not related to MPOS directly but I believe I'll found the advice here.

Following Quick Start Guide I renamed _/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/websocket_transport.py_
from
`from autobahn.websocket import WebSocketServerProtocol, WebSocketServerFactory`
to
`from autobahn.twisted.websocket import WebSocketServerProtocol, WebSocketServerFactory`
After this modification each time I put **twistd -y launcher.tac** it gives me the bellow errors:

> 2016-04-13 00:16:44+0100 [-] Log opened.
> 2016-04-13 00:16:44+0100 [-] twistd 13.2.0 (/usr/bin/python 2.7.6) starting up.
> 2016-04-13 00:16:44+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
> 2016-04-13 00:16:44+0100 [-] Changing process name to twistd-stratum-mining
> 2016-04-13 00:16:44+0100 [-] Log opened.
> 2016-04-13 00:16:44+0100 [-] twistd 13.2.0 ( 2.7.6) starting up.
> 2016-04-13 00:16:44+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
> 2016-04-13 00:16:44+0100 [HTTPPageGetter,client] 2016-04-13 00:16:44,397 DEBUG stats logger.get_logger # Logging initialized
> 2016-04-13 00:16:44+0100 [HTTPPageGetter,client] 2016-04-13 00:16:44,400 DEBUG protocol logger.get_logger # Logging initialized
> 2016-04-13 00:16:44+0100 [HTTPPageGetter,client] 2016-04-13 00:16:44,401 DEBUG socket_transport logger.get_logger # Logging initialized
> 2016-04-13 00:16:44+0100 [HTTPPageGetter,client] 2016-04-13 00:16:44,402 DEBUG http_transport logger.get_logger # Logging initialized
> 2016-04-13 00:16:44+0100 [HTTPPageGetter,client] Unhandled error in Deferred:
> 2016-04-13 00:16:44+0100 [HTTPPageGetter,client] Unhandled Error
> 	Traceback (most recent call last):
> 	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
> 	    result = g.send(result)
> 	  File "/opt/gcoin/stratum-mining/mining/__init__.py", line 127, in setup
> 	    on_startup.callback(True)
> 	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
> 	    self._startRunCallbacks(result)
> 	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
> 	    self._runCallbacks()
> 	--- <exception caught here> ---
> 	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
> 	    current.result = callback(current.result, *args, **kw)
> 	  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/server.py", line 46, in setup_finalize
> 	    import websocket_transport
> 	  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/websocket_transport.py", line 1, in <module>
> 	    from autobahn.twisted.websocket import WebSocketServerProtocol, WebSocketServerFactory
> 	exceptions.ImportError: No module named twisted.websocket

Any suggestions how to fix this up?

**Comment by TheSerapher** [comment]
Indeed not an MPOS issue so try the proper channels for the coin daemon.
