### ISSUE TITLE
What RPC calls does MPOS Make

### ISSUE THREAD

**Issue by jjj092353** [MPOS/php-mpos#2495]
I am modifying a wallet that does not support RPC Calls to accept RPC calls and I need to know what RPC commands that wallet should accept - thanks

J

**Comment by TheSerapher** [comment]
Running `grep "bitcoin->" * -R` on the code should give you a fair idea. Though I am pretty sure that modifying a wallet that doesn't support RPC calls to support them isn't necessarily a good idea.
