### ISSUE TITLE
email to gmail issue

### ISSUE THREAD

**Issue by saymissme** [MPOS/php-mpos#2496]
my mpos server send some mail to gmail got this error:

````
This is the mail system at host iZ62fx3md2oZ.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.
The mail system
<ttbdesign@gmail.com>: host gmail-smtp-in.l.google.com[74.125.23.27] said:
    550-5.7.1 [xxx.xxx.xxx.xxx       1] Our system has detected an unusual rate of
    550-5.7.1 unsolicited mail originating from your IP address. To protect our
    550-5.7.1 users from spam, mail sent from your IP address has been blocked.
    550-5.7.1 Please visit 550-5.7.1
    https://support.google.com/mail/answer/81126 to review our Bulk Email 550
    5.7.1 Senders Guidelines. o7si3247622igu.7 - gsmtp (in reply to end of DATA
    command)`
```

i was set a third smtp server,looks not work
how to fix it?
thx

**Comment by TheSerapher** [comment]
Read the error message supplied by Google and you will notice this isn't an MPOS issue. Your host has been blacklisted. It even gives you a link to get more information.

**Comment by saymissme** [comment]
sorry
last question:
why mpos not use smtp server to send this mail?

**Comment by TheSerapher** [comment]
Could be a lot of things, but check the configuration of Swiftmailer: https://github.com/MPOS/php-mpos/wiki/Config-Setup#swiftmailer

It should be setup to use SMTP as the handler (`type` should be `smtp`) and the proper options for handling SMTP traffic.

Another option could be setting up your local postfix (`type` is `sendmail`, the default) or other mailer to act as a relay host for your upstream SMTP server. This is not covered by MPOS though and you should check out the documentation in our Wiki: https://github.com/MPOS/php-mpos/wiki/Quick-Start-Guide#e-mail

In general, check the documentation. Most of the things are covered there.

**Comment by AndreyNag** [comment]
All hear allready understand how to install, setup postfix and manual use postfix. Anybody tell us how to setup _mpos to use postfix instead sendmail.
What we will to do to run postfix instead of sendmail?

**Comment by TheSerapher** [comment]
Sendmail is just a binary. Postfix placed that too. You can keep MPOS setting to use sendmail, it will then call the binary. There is a mail test script in MPOS too that you can try out.

**Comment by AndreyNag** [comment]
If you can show me where is the "mail test script in MPOS"?
Thanks.

**Comment by TheSerapher** [comment]
https://github.com/MPOS/php-mpos/blob/master/scripts/test_email.php

The rest was already explained earlier and the Wiki had an example. All defaults should be sufficient to send mail via a local postfix.

**Comment by AndreyNag** [comment]
Excuse me, tell me how to invoke this script?
