### ISSUE TITLE
How I can fixed a number dispaly out of box on round informaiton?

### ISSUE THREAD

**Issue by jeong760** [MPOS/php-mpos#2502]
Dears,

How I can fixed a numbers display out of box on round infomaiton section of overview screen?
Does anyone know about this?

![round_infomation_issue](https://cloud.githubusercontent.com/assets/18043565/15167065/7405b13e-1760-11e6-8095-29fea9f91f48.JPG)

Many thanks
John Ahn

**Comment by TheSerapher** [comment]
The BTC estimate is a bit off but the others are just very very high numbers that have no rounding issue. Not sure how this could be improved unless we drop X digits and replace it with k/m/b indicators.

**Comment by jeong760** [comment]
So for now there is no way to fixed it?

**Comment by TheSerapher** [comment]
Unless you feel like editing the JavaScript file that displays this data I don't think so.
