### ISSUE TITLE
The inquiry of create a monitoring specific API key for Uptime

### ISSUE THREAD

**Issue by jeong760** [MPOS/php-mpos#2504]
Dears,

How I create a Monitoring API keys for UPtime status? I've read out link as following but don't understand how to.

Link: https://github.com/MPOS/php-mpos/wiki/Uptime-Robot-Setup 

Regards,
John Ahn

**Comment by TheSerapher** [comment]
As far as I can tell the documentation is up to date and should work. If you need help creating the monitors try the Uptime help. It's just a matter of creating the monitors, give them an API key and adding their ID (name) and key to MPOS as documented.
