### ISSUE TITLE
Ethereum-Pool with MPOS

### ISSUE THREAD

**Issue by zimbo123** [MPOS/php-mpos#2506]
Hello,

i try to install an Ethereum Pool with MPOS, i had some Pools (PPC, WDC, TAG, CSC) already running with MPOS. But with Ethereum i had a Problem. What Kind of Algorithm should i use?

The doc said:

Algorithm

Underlying coin algorithm that you are mining on. Set this to whatever your coin needs, sha256d, scrypt, scryptn or x11.

Default Values:
algorithm    =    'scrypt'

algorithm
•sha256d: Bitcoin and similar ones.
•scrypt: Litecoin and most of the all-coins.
•scryptn: Vertcoin and similar ones.
•x11: Darkcoin and similar ones.

Has anybody an idea?
Thank you very much.

Best regards

Zimbo

**Comment by TheSerapher** [comment]
It's called Ethhash but isn't supported in MPOS yet. Maybe someone can share a proper config so it could be added to MPOS.

**Comment by TheSerapher** [comment]
FYI Ehtereum RPC is completely different to any bitcoin based RPC system used in other coins. At least according to: https://github.com/ocminer/ethcore-pool-mpos/issues/3

Please re-consider if you wish to run a pool based on this coin since it won't be supported in MPOS unless someone finds a way to include it to the core code.

**Comment by mmitech** [comment]
Ocminer from suprnova has done that but he is not willing to share his changes with anyone.

Meanwhile you can use [Sammy's Pool](https://github.com/sammy007/open-ethereum-pool), it is great.

**Comment by TheSerapher** [comment]
The usual "I make it work and cash-in since I am the only pool owner" mentality. Thanks for the confirmation though, I wasn't 100% sure about this myself.
