### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by wiico** [MPOS/php-mpos#2507]
Hi Team,

thanks for mpos !

i can't configure sso 

global.inc.php A 

$config['db']['host'] = 'localhost';
$config['db']['user'] = '';
$config['db']['pass'] = '';
$config['db']['port'] = 3306;
$config['db']['name'] = 'xvg';
$config['db']['shared']['accounts'] = $config['db']['name']='moll';
$config['db']['shared']['workers'] = $config['db']['name']='moll';
$config['db']['shared']['news'] = $config['db']['name']='moll';

global.inc.php B 

$config['db']['host'] = 'localhost';
$config['db']['user'] = '';
$config['db']['pass'] = '';
$config['db']['port'] = 3306;
$config['db']['name'] = 'wdc';
$config['db']['shared']['accounts'] = $config['db']['name']='moll';
$config['db']['shared']['workers'] = $config['db']['name']='moll';
$config['db']['shared']['news'] = $config['db']['name']='moll';

sudo mysql -p -e "create database moll"
sudo mysql -p moll < sql/000_base_structure.sql

export import 'xvg' tables account coin address and news  to 'moll'

I can login to pool A normally but i cant to pool B . I had to make password recovery ans it's works , then pool A fail , recovery password then pool B fail ...

What am i doing wrong please ?

**Comment by TheSerapher** [comment]
You haven't configured it properly. Check the Wiki and note that the DB name has to prefix the shared database name (e.g.`shared_mpos.moll`). Otherwise it won't know which database to check for the shared accounts and will look into your `$config['db']['name']`. You are using a very funky format there.
