### ISSUE TITLE
Auto-Exchange feature expansion

### ISSUE THREAD

**Issue by rmeskill** [MPOS/php-mpos#2519]
Would be really nice if I could set auto-exchange only to certain coins. There doesn't seem to be any consistency to when I click the arrow in the direction of 'credited' as to whether a coin is simply credited to me or automatically goes to the exchange. I have now shut off the auto-exchange option, but would really like to be able to have only *some* coins auto-exchange. If there was a way to, maybe, exempt some coins from auto-exchange, that would be fine, too. Maybe, for example, only have auto-exchange active if I don't have a wallet withdrawal address entered? But if I do have a wallet withdrawal address entered, always credit my local wallet until my withdraw amounts are reached.

**Comment by TheSerapher** [comment]
I am not sure what you are referring too. MPOS allows and should enforce an auto transfer for mined coins for each user. Leaving coins on the pool is a bad thing and should be avoided at all times. If you enter your personal wallet address as the destination, that's where coins are sent to. If you add an exchange address, it will be sent to an exchange.

Maybe you are confusing MPOS with a customized version running on a pool you access? MPOS supports multiple pools with one authentication backend but doesn't support multicoin in a single backend.

**Comment by TheSerapher** [comment]
I think you did confuse a pool feature running someplace with a basic MPOS feature. There is no auto-exchange option in MPOS. Only a coin limit that will trigger a wallet transfer to the configured address for each user.
