### ISSUE TITLE
Pool alert

### ISSUE THREAD

**Issue by cqtenq** [MPOS/php-mpos#2520]
I see some alert info in banner :
We are investigating issues in the backend. Your shares and hashrate are safe and we will fix things ASAP.
Findblocks disabled, new blocks will currently not show up in the frontend
Blockupdate disabled, blocks and transactions confirmations are delayed
Payouts disabled, you will not receive any coins to your offline wallet for the time being

what's happening here?  how to fix it .

**Comment by TheSerapher** [comment]
Mostly happens if either your coin daemon isn't reachable when the crons tried to run or the server was rebooted before disabling all cronjobs and waiting a bit for running ones to finish.

Force a cron run, see wiki how to do that (Crons).
