### ISSUE TITLE
Does it support skein algorithm?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [MPOS/php-mpos#2521]
I specified the skein algorithm (for digibyte) within the config file. 
And I'm getting a message on a page.

```
Unable to load your coins class definition for skein
```

**Comment by AlexanderKozhevin** [comment]
Well, I found that algorithm should be matching one of [these](https://github.com/MPOS/php-mpos/tree/master/include/classes/coins).
1. scrypt
2. scryptn
3. sha256d
4. x11

**Comment by TheSerapher** [comment]
If you figure out what it is feel free to create a pull request against our development branch and we integrate it :-)

**Comment by AlexanderKozhevin** [comment]
I couldn't find that number within the coin docs or somewhere else. So I just left it as it is - 16. 
I don't know whether it's valid number of not, and what this number at all. But the UI seems to be working now.
