### ISSUE TITLE
Is it possible to disable registration for users?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [MPOS/php-mpos#2522]
I'm running a [nomp](https://github.com/zone117x/node-open-mining-portal) mininig pool. 
And it allows to connect to it just with an address, without any account or passwords.
It is possible just disable registration?

**Comment by TheSerapher** [comment]
If NOMP is your share processor too, you don't need MPOS at all. NOMP has MPOS support though, that way you can run with regular users and let NOMP handle authentication through the user database.

There is currently no way to disable registration in MPOS nor is it a planned feature at this time.
