### ISSUE TITLE
Could not find any transactions no listings under blockshares.

### ISSUE THREAD

**Issue by GatekeeperZA** [MPOS/php-mpos#2523]
I have been struggling now for over 2 weeks to get mpos / unomp up and running on an LTC pool
all looks good miners connect all everything works except no payments no balance debug shows shares being submitted and lists on dashboard.  but im also seeing no blockshares and and under transaction there are no transactions. they list in sqldb but nothing on mpos side payments are disabled on unomp side have I done something wrong.
I have been seeking help on the IRC but no answers for 3 days.
I have read http://www.grewe.ca/crypto-currency-mining/ but didnt help much even tried switching payout methods please help or comment if im being an idiot.. thanks.

**Comment by TheSerapher** [comment]
If you see a proper valid hash rate and shares are inserted to the tables, ensure your crons are Setup properly to do the payouts and block detection. If those are also setup, also check that your coind actually has any blocks discovered at all. You may just having to mine more shares before you get a block. Unless there is a block you won't see any transactions either.
