### ISSUE TITLE
MPOS Installation guide for VPS

### ISSUE THREAD

**Issue by hiroshi2701** [MPOS/php-mpos#2526]
Hi there, 

I'm planning to switch from uNOMP to MPOS. And I'm just wondering if what guide I can use to install MPOS mining pool to my VPS. I'm using http://vultr.com as my VPS. Any help will be appreciated! Thank you. 

Best Regards, 
Mark

**Comment by TheSerapher** [comment]
No different than any other host. Unless you don't have direct access to it, then I am afraid you are out of luck.
