### ISSUE TITLE
Feature request: Bulk or automatic adding of workers

### ISSUE THREAD

**Issue by xdo-soft** [MPOS/php-mpos#2528]
It would be great if a facility was added for bulk adding workers. E.g. suppose I have workers numbered from 0 to 99, it would be great if I could add all 100 workers simultaneously with the same password. Doing this manually rapidly becomes tedious, and browser automation is rather unreliable.

Perhaps even better, would be the automatic creation of workers on connection. So I would set a special "default" worker password for unrecognised worker IDs, and then if a connection was made with an unrecognised worker name, but the correct default password, the worker ID would automatically be added to the workers registered for my account. (Dwarfpool does something similar.)

**Comment by TheSerapher** [comment]
Bulk adding sounds like a good thing, maybe I will look into this someday. Other than we are open to PRs.

On the fly creation has to be taken care on another level, at your stratum server. Those can easily add new workers to the table and that's all MPOS needs to work.

Maybe adding this as the first write API call is another option. Would allow creation workers in POST from anywhere.

**Comment by xdo-soft** [comment]
I'm afraid creating a PR for this would be rather outside of my comfort zone, but I'm glad you agree that enabling bulk adding of workers is a good idea. I appreciate that you have other priorities in the short term though.
The write API also sounds like a very good idea, and would certainly answer my use case.

**Comment by TheSerapher** [comment]
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.
