### ISSUE TITLE
equihash support for ZCash

### ISSUE THREAD

**Issue by vs4vijay** [MPOS/php-mpos#2530]
Hi,

I am tying to add equihash for ZCash, I have changed in global configuration and created `coin_equihash.class.php`. 

and added following content:

```php
class Coin extends CoinBase {
  protected $target_bits = 16;
}
```

Is this sufficient? What all other changes do I have to make to support equihash?

**Comment by TheSerapher** [comment]
It should, but in the end that largely depends on the coin itself. Most will do with setting proper target bits and/or maybe precision ...

**Comment by Aleix-Oto** [comment]
im interesed to install equihash algorithm to MPOS its possible??

Will there be updates MPOS?

**Comment by TheSerapher** [comment]
That depends on the coin and user activity on this project since I am not tackling any major tasks anymore myself.

**Comment by kingcap1** [comment]
i vote for YES !

running MPOS with Eqh Coinbase /thx GQM !
https://github.com/MPOS/php-mpos/issues/2531

and 
Script from here 
https://github.com/z-classic/z-nomp/issues/2


working like charm .

but i dont get Payout to run cause 
ERROR --> E0078: RPC method sendmany did not return 200 OK: Address: tmQ1zndMLjEWBPjUTTtCUhwh3UvjzYRgzme ERROR: RPC call did not return 200: HTTP error: 500 - JSON Response: [-6] Coinbase funds can only be sent to $Z Address

which i CANNOT entered in Useraccount Payout Address

Any Suggestions ?

Example for an t Address : tmQ1zndMLjEWBPjUTTtCUhwh3UvjzYRgzme
and an Z Address :  ztSPWEZbQHVJU4iWs4UjAstUeF65H7yzi1bRC5dv4VMuiG3NsfmMEd7iWTjLGENK3GceCvhcr8TzT936rcGvEEZh3M3vudR

both on Testnet

**Comment by GQM** [comment]
@kingcap1 you have to use this script to cycle the coins in order to process payments https://gist.github.com/sammy007/4739e07a0ee92bde99f8f1f40835c7f1

**Comment by kingcap1** [comment]
@GQM : 
jep , i use that script 

its cycle the Coins correctly , but when i want to Payout like this : 
2017-03-21 23:04:09 	Debit_MP 	Confirmed 	tmQ1zndM...jzYRgzme
the Payout Log give me that : 

ERROR --> E0078: RPC method sendmany did not return 200 OK: Address: tmQ1zndMLjEWBPjUTTtCUhwh3UvjzYRgzme ERROR: RPC call did not return 200: HTTP error: 500 - JSON Response: [-6] Coinbase funds can only be sent to $Z Address

And i cannot add an Z Address to my Account on MPOS , cause it wont accepted from Mpos

Any Suggestions ?

**Comment by kingcap1** [comment]
./zcash-cli getaddressesbyaccount ""
[
    "tmCG7BGuGTbXqNrGfg3VGGC85BeAf8H45dj",
    "tmMNzPU8iUXbd1FugpUZEB3bTCndqRzUhmV"


./zcash-cli z_listaddresses
[
    "ztVBgC4eu4enUdZZm7U9Lhip1tpaRmzRYMDomAPUxUm1Wrurdy8HoTkAvBWF2ibzidHkRoU1LBvnLBqizfiR9oV9Yw23cvs",
    "ztnkzb9r1ng5pgPF7iAhzq2W7nfuDQD2eg3avFk4dTHrwh6odePXA2otzAf136UBMLJkAD5pZMroqY6krEDNeFD43GnMc53"
]


 ./zcash-cli z_gettotalbalance
{
    "transparent" : "549.9998",
    "private" : "599.9997",
    "total" : "1149.9995"

**Comment by TheSerapher** [comment]
As far as I can tell his means tha Zcash doesn't work well with mpos because for whatever reason it has two different coin address systems but the RPC address validation only works with one. I'd guess if they added the validation for both address types into one RPC call and allow mpos to validate it may work. But you can also disable address verification. This will skip all verifications though so be sure your users know they can't make typos :-) See sample config and wiki on how to disable it.

**Comment by TheSerapher** [comment]
And on a side note I doubt the payment processor of mpos can deal with two different balances in a single wallet.

**Comment by GQM** [comment]
@kingcap1 please double check your config file for the script. Its purpose is to move the coinbase transaction to a z address and then to another t address which the MPOS payment processor can handle.

The error you have shared about means that you are trying to send coins from a coinbase transaction which will fail.

@TheSerapher zcash has two address types t = transparent and z = anonymous 

The t addresses function just like any crypto currency address, as far as the rpc calls are concerned. For whatever reason the coinbase transactions can't be spent from the original t address and must be "shielded" before being spent.

**Comment by TheSerapher** [comment]
Sounds like a cold Storage within the same daemon? Not sure that adds any security but certainly added complexity ;-)

**Comment by GQM** [comment]
I think it has something to do with the founders rewards and how they wanted the shield the outputs  or something.

It certainly adds complexity lol

**Comment by kingcap1** [comment]
Hi !

just came back from Work .

![zclpooltestnet](https://cloud.githubusercontent.com/assets/26490498/24216028/02a22d46-0f3b-11e7-8bd7-a238695ec5ce.jpg)

will restart testmining in about 1h and share my conclusions after .

Thx Sebastian and GQM for helping

**Comment by kingcap1** [comment]
![3](https://cloud.githubusercontent.com/assets/26490498/24216777/dcb6f4a6-0f3d-11e7-9984-eb96963d2de2.jpg)

Ha ! , seems working now .
what i have done ? 
Just in case of Failure i deleted Wallet.dat on my receiving Address ( Miner )
added the new Address in Mpos User Account

mined 2 more Blocks and do a manually Payout Request

As show above it worked .

Seems there was a Problem with maturing the Coins after mining.

Thanks again Dudes for helping out  !

**Comment by kingcap1** [comment]
One more Thing for Clarify on Equihash Solution : 

![4](https://cloud.githubusercontent.com/assets/26490498/24218059/2a4d18fe-0f42-11e7-869c-a38a66ce66a8.jpg)

The Amount 599 Receive and Send 524,99 on about 17 o Clock was an manually Start of the Script shown above from GQM

then i restarted Mining on Testnet at 20:17 o clock

Maturing Coins again later 4 Blocks needed to confirm from "shielding"
conclusion for me : 

if Mining confirmed after 100 Blocks my Setting to Payout has to be more than 104 Blocks for confirming
better 110 Blocks !

Seems MPOS is able to add equihash Coins with 1 Fix ( GQM ) and 1 Backround Task / Script to shielding .

WORKS !
