### ISSUE TITLE
Themes/Templates

### ISSUE THREAD

**Issue by cryptobay** [MPOS/php-mpos#2532]
Hi there,

i am currently looking for smoe themes. But sadly i wasn't able to implement one...
Could anybody please share some resource links? It could also be a bundle or anything where i have to pay a little bit. Free to use would be prefered but it's  no must have.

I am also looking for a complete pool dashboard. I am running multiple instances of MPOS pools for different coins, and i would like to setup a dashboard with all coins like on http://ispace.co.uk/ pool.

Anybody here who can help me out? :)

**Comment by TheSerapher** [comment]
This is a bug reporting tool, not a community forum to find support on implementing custom features :-) Please refer to an online source of your choice to contact developers to implement a new custom theme.

MPOS comes with a default theme which is the only one we support.
