### ISSUE TITLE
How does each PPLNS round shares decided?

### ISSUE THREAD

**Issue by jeong760** [MPOS/php-mpos#2534]
Dears,

I am operating a personal small BTC mining pool now using MPOS+UNOMP. 
But just I wonder how does each round shares target decided by pool? by default maximum round is 10 but each round estimate shares are same as current difficulty. 

Is there any method to reduce a each round shares them?

Current Difficulty	        310,153,855,703.43328857
Est. Shares this Round	310,153,855,703 (done: 0.09%)

Regards,
John Ahn

**Comment by TheSerapher** [comment]
Estimated shares are based on difficulty and can not be influenced.

Round shares in PPLNS just combines past shares with the current round to smooth out payments for users. If you just joined a pool you will get a lot less payout on a quick round than someone that's been around for a while.

Please look it up with google. There are resources available to teach you the basics, a Bug Tracker certainly isn't the right place to ask this.

**Comment by jeong760** [comment]
Thank you. I know my question is stupid things. but I am not sure how I've learn about PPLNS and what is rule for each round.

**Comment by TheSerapher** [comment]
https://github.com/MPOS/php-mpos/wiki/Config-Setup#pplns-settings
