### ISSUE TITLE
Cronjob status

### ISSUE THREAD

**Issue by jeong760** [MPOS/php-mpos#2535]
Dears,

Just I wonder following cronJob list are ok. because it was changed every minutes but "Acvtiv" marked as X.
When does it changed as like "V"?

![cronjob](https://cloud.githubusercontent.com/assets/18043565/21379055/629e01a6-c78e-11e6-9c17-8f943b9d6efd.JPG)

**Comment by TheSerapher** [comment]
Look a thing the times and you should see they are active.
