### ISSUE TITLE
mpos+nomp

### ISSUE THREAD

**Issue by aspirecoin** [MPOS/php-mpos#2537]
Working, but My Sharerate

0.00 S/s 
and 
Block	Finder	Time	Actual                           Shares
37276	luciferdark	12/25/2016 17:39:29	0
37275	luciferdark	12/25/2016 17:36:18	0
37274	luciferdark	12/25/2016 17:34:52	0
37273	luciferdark	12/25/2016 17:33:06	0
37271	luciferdark	12/25/2016 17:22:45	0

x11 algo. help...

**Comment by TheSerapher** [comment]
You are using NOMP for payouts and not as a bridge to MPOS. You need to wipe your installation and start again but ensure NOMP writes all shares to the MPOS database and disable payments in NOMP.

This is probably documented in the readme of NOMP too.

**Comment by aspirecoin** [comment]
i use nomp without payouts and share save in mpos mysql. i see. but in web  they always 0
in mysql i see share. in mpos no.. why?

**Comment by TheSerapher** [comment]
Selected the wrong algorithm in MPOS? Maybe MPOS doesn't use the right database? Could be a lot but it all comes down to a configuration or setup issue and not a bug in MPOS.

**Comment by aspirecoin** [comment]
no, select x11

**Comment by TheSerapher** [comment]
Can't say for sure but it could be a rounding issue and your coin isn't completely the same as X11? Maybe check with a coin related forum and ask for setup help. It should work with MPOS but it's not guaranteed to work without modifications if it's some altcoin.
