### ISSUE TITLE
Expose block statistics via API

### ISSUE THREAD

**Issue by zoomequipd** [MPOS/php-mpos#2538]
would it be possible to expose the basic elements of each block found via the API? 
from this page in a MPOS instance
https://[pool_url]/index.php?page=statistics&action=round&height=####

Would it be possible to expose the following elements via the API?

ID	####	Height	####	Amount	#	Confirmations	### left
Difficulty	####	Time	YYYY-MM-DD HH:MM:SS	Shares	#### Finder	[user]

**Comment by TheSerapher** [comment]
https://github.com/MPOS/php-mpos/blob/master/include/pages/api/getblocksfound.inc.php

Already there i would think. Try it out.

**Comment by zoomequipd** [comment]
that works for the most recent blocks, would it be possible to be able to specify the height parameter on that page so one can pull details of less recent blocks?

**Comment by TheSerapher** [comment]
Yeah should be possible. But maybe it should be it's own API call allowing to fetch one single block.

**Comment by TheSerapher** [comment]
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.
