### ISSUE TITLE
Feature request: Pushover.net notifications

### ISSUE THREAD

**Issue by blondak** [MPOS/php-mpos#2539]
Add options to send user notifications using https://pushover.net/

**Comment by TheSerapher** [comment]
Looks cool even though it does cost money if users want to stick to it. Not sure if many are willlong to pay for something as simple as notifications if a simple Mail would do the trick.

Anyway leaving it open if someone feels like tackling this.

**Comment by blondak** [comment]
Or maybe some universal interface for custom classes, basically implement and define some INTERFACE and user can write own class (XMPP, Pushover.net, etc...)

**Comment by TheSerapher** [comment]
Not sure if someone would tackle that, but the only place I can see that needs to be more generic is the sendNotifications task:

https://github.com/MPOS/php-mpos/blob/master/include/classes/notification.class.php#L140-L166

It's setup for mails only right now but it shouldn't be too hard to make it more generic to accept some basic data and then act :-)

**Comment by blondak** [comment]
ok, I'm doing on it ;)

**Comment by TheSerapher** [comment]
Awesome, be sure to PR it against the development brach here so we can run it against the community before we release it :-)

**Comment by TheSerapher** [comment]
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.
