### ISSUE TITLE
Email can't be sent

### ISSUE THREAD

**Issue by UnsignedInt8** [MPOS/php-mpos#2544]
Hi, sir. I'm a newer about the mpos. I have a question about the Email configuration.

I've installed the Postfix and I'm able to send email from terminal: 

`$ echo "Test mail from postfix" | mail -s "Test Postfix" my-email@outlook.com`

But the MPOS can't send any email, could you please tell me why?  Thank you.

**Comment by TheSerapher** [comment]
Please check your configuration and read the Wiki entry regarding mail delivery using MPOS. It's most likely a configuration issue for your mail sending options.

**Comment by UnsignedInt8** [comment]
Hi, sir. Can I leave empty string here? I just want to use the Postfix service.

`$config['swiftmailer']['type'] = '';`

![sendmail](https://cloud.githubusercontent.com/assets/15274326/22505492/bd771ec0-e8b6-11e6-90c5-a198d98644e4.png)

**Comment by TheSerapher** [comment]
I think you don't understand that Postfix == Sendmail in this context. Postfix also installs a /usr/sbin/sendmail script that allows any program to send mail via it's local queues.

Leave it at type sendmail and configure Postfix and you are done.

And here a warning: Running Postfix as your global mail sender for MPOS is not recommended. You are guaranteed to land on a spam blacklist at some point which will cause no mails to be delivered. Hence an article in the Wiki to run MPOS via Postfix and Gmail: https://github.com/MPOS/php-mpos/wiki/Quick-Start-Guide#e-mail

Sorry, this all the help I can give, everything else is very generic Mail setup that is not included in the MPOS setup guide or supported via this Bug Reporter.

**Comment by UnsignedInt8** [comment]
I think I understand it now. Thank you so much. :)
