### ISSUE TITLE
Can I use MariaDB?

### ISSUE THREAD

**Issue by UnsignedInt8** [MPOS/php-mpos#2548]
Hello, sir.

After saving more than 10 million shares, MYSQL server (5.5) is too slow. Can I use MariaDB to improve the performance?

**Comment by TheSerapher** [comment]
You can try but no guarantee it improves. With many shares the only way to keep things smooth is better hardware and using the performance tuning recommendation by Percona tools. And ensure caching is enabled, without memcache the website will come to a crawl.

**Comment by UnsignedInt8** [comment]
Thank you sir.

**Comment by UnsignedInt8** [comment]
Excuse me sir. Could you tell me why mpos can't delete accounted shares? I just installed MariaDB, and did nothing about database files.

![untitled](https://cloud.githubusercontent.com/assets/15274326/23264744/6cad08ec-fa1d-11e6-8824-dc1d2b4fd22d.png)

**Comment by TheSerapher** [comment]
Sorry can't help there. This is a if tracker and not s support forum for core changes in your setup. You'll have to debug that on your own or check out the other forums available for help :-)

**Comment by UnsignedInt8** [comment]
OK, thank you so much :)
