### ISSUE TITLE
API Problem

### ISSUE THREAD

**Issue by Marekkon5** [MPOS/php-mpos#2556]
! NOT AN ISSUE ! But is it possible to get more than 10 blocks from api? Thanks, sorry if I asked wrong

**Comment by TheSerapher** [comment]
It was available in the past but used to DOS pools so a limit was added set via your settings panel in MPOS. So you could increase that to whatever you like but be aware that it may be abused.

**Comment by Marekkon5** [comment]
I am not admin, so I probally can't do this. thx
