### ISSUE TITLE
Miningpoolhub

### ISSUE THREAD

**Issue by imrecsoka** [MPOS/php-mpos#2557]
Hi i am not sure how to get hold of the Miningpoolhub crew, i just wanted to point out that the Maxcoin wallet seems to be flaky or dodgy. My coins have not been exchanged and its been almost 1 month.
If you can point me to the correct people ill appreciate it.

**Comment by TheSerapher** [comment]
Sorry no idea. This is an issue tracker and not a communication hub for various pools :-)

**Comment by imrecsoka** [comment]
yip

**Comment by miningpoolhub** [comment]
Here's miningpoolhub's forum.
https://bitcointalk.org/index.php?topic=472510

maxcoin will not be auto exchanged as bittrex delisted maxcoin.
Click the left arrow button to move your coins to normal wallet at Wallet page and withdraw maxcoin, exchange it manually.

**Comment by imrecsoka** [comment]
no problem iam new to this stuff, so i dont know even which exchange to use yet. I do have an account with bitrex but i need to know if there is a better exchange. I also dont understand how i can possible get my coins in to my currency. Really looking for guidance and best practices
