### ISSUE TITLE
Cors problems when using API

### ISSUE THREAD

**Issue by thibautvincent** [MPOS/php-mpos#2558]
I tried to use the API and acces it by using Fetch (JavaScript). After a lot of searching and trying over and over again I wasn't able to fix this problem. There is always a problem with the cors. Keep having the issue `Failed to load resource: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.` Don't know if it's something on my end or not.

I'm developing from localhost. Maybe this is the problem?
The image shows the code.
![screen shot 2017-05-23 at 18 40 34](https://cloud.githubusercontent.com/assets/9417678/26365258/5e9e949a-3fe7-11e7-8b9d-6ec2aa3b20d0.png)
Error in console.
![screen shot 2017-05-23 at 18 17 32](https://cloud.githubusercontent.com/assets/9417678/26364478/c341ea80-3fe4-11e7-9893-894fa6bbb4fc.png)

Thanks for looking into this.

**Comment by TheSerapher** [comment]
I think I had the same issue running local development. I then added a `/etc/hosts` entry pointing to the site (e.g. some.coin.com) and it worked.

This is not something MPOS is doing but something being enforced by your browser and web server. I don't remember adding CORS checks into MPOS so it's probably just supposed to fail for localhost ;-)
