### ISSUE TITLE
Wrong share information after time adjustment

### ISSUE THREAD

**Issue by HashUnlimited** [MPOS/php-mpos#2559]
During server maintenance the time was adjusted. Afterwards the Dashboard shows incorrect numbers for user hashrates, the Share Information shows all zero, for own and pool shares. 
Crons are working correctly, rewards are accounted. 
<img width="907" alt="screen shot 2017-05-24 at 23 52 25" src="https://cloud.githubusercontent.com/assets/26601261/26425112/5d8aa1ac-40dc-11e7-853d-02b0adfa31e4.png">
<img width="289" alt="screen shot 2017-05-24 at 23 52 39" src="https://cloud.githubusercontent.com/assets/26601261/26425113/5de46f48-40dc-11e7-9d99-4b1522c9b91e.png">
Any hint to resolve this would be helpful in the Wiki as well.

**Comment by TheSerapher** [comment]
Have you checked if there are any shares in the shares table? Are those timestamps of these shares correct? If MPOS doesn't see any shares maybe there is an issue elsewhere e.g. While inserting them.

**Comment by HashUnlimited** [comment]
Well, clearing memcache seemed to have done the trick, it needed a while to smooth out though. Rough instructions for how to do that are on the Wiki already.
