### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by zhiyan114** [MPOS/php-mpos#2560]
When it in the public section, it show the missing config message but when i move it out (where the config and all file is), it shows 500 ERROR request, so how can i fix this?

**Comment by TheSerapher** [comment]
Read the error logs of your Webserver - this isn't an MPOS issue but your setup.

**Comment by zhiyan114** [comment]
My error:
[Sat May 27 18:47:27.321717 2017] [mpm_prefork:notice] [pid 99204] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sat May 27 18:47:27.321788 2017] [core:notice] [pid 99204] AH00094: Command line: '/usr/sbin/apache2'
[Sat May 27 18:47:30.881179 2017] [php7:error] [pid 99207] [client 108.188.164.183:56167] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/include/classes/statscache.class.php:21\nStack trace:\n#0 /var/www/html/include/classes/statscache.class.php(114): StatsCache->__construct(Array, Object(Debug))\n#1 /var/www/html/include/autoloader.inc.php(65): require_once('/var/www/html/i...')\n#2 /var/www/html/include/bootstrap.php(55): require_once('/var/www/html/i...')\n#3 /var/www/html/public/index.php(40): include_once('/var/www/html/i...')\n#4 {main}\n  thrown in /var/www/html/include/classes/statscache.class.php on line 21
[Sat May 27 18:51:40.332526 2017] [php7:error] [pid 99208] [client 108.188.164.183:56251] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/include/classes/statscache.class.php:21\nStack trace:\n#0 /var/www/html/include/classes/statscache.class.php(114): StatsCache->__construct(Array, Object(Debug))\n#1 /var/www/html/include/autoloader.inc.php(65): require_once('/var/www/html/i...')\n#2 /var/www/html/include/bootstrap.php(55): require_once('/var/www/html/i...')\n#3 /var/www/html/public/index.php(40): include_once('/var/www/html/i...')\n#4 {main}\n  thrown in /var/www/html/include/classes/statscache.class.php on line 21
[Sat May 27 18:56:38.823628 2017] [php7:error] [pid 99209] [client 108.188.164.183:56430] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/include/classes/statscache.class.php:21\nStack trace:\n#0 /var/www/html/include/classes/statscache.class.php(114): StatsCache->__construct(Array, Object(Debug))\n#1 /var/www/html/include/autoloader.inc.php(65): require_once('/var/www/html/i...')\n#2 /var/www/html/include/bootstrap.php(55): require_once('/var/www/html/i...')\n#3 /var/www/html/public/index.php(40): include_once('/var/www/html/i...')\n#4 {main}\n  thrown in /var/www/html/include/classes/statscache.class.php on line 21
[Sat May 27 18:56:42.461130 2017] [php7:error] [pid 99210] [client 108.188.164.183:56435] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/include/classes/statscache.class.php:21\nStack trace:\n#0 /var/www/html/include/classes/statscache.class.php(114): StatsCache->__construct(Array, Object(Debug))\n#1 /var/www/html/include/autoloader.inc.php(65): require_once('/var/www/html/i...')\n#2 /var/www/html/include/bootstrap.php(55): require_once('/var/www/html/i...')\n#3 /var/www/html/public/index.php(40): include_once('/var/www/html/i...')\n#4 {main}\n  thrown in /var/www/html/include/classes/statscache.class.php on line 21

**Comment by zhiyan114** [comment]
i cant install the 5.6 memcache because i cant find the package anywhere so i install the latest memcache

**Comment by zhiyan114** [comment]
NVM, i change the ubuntu version and everything is fixed

**Comment by zhiyan114** [comment]
and also my set up it correct, it the version of  ubuntu dont support it

**Comment by freemanjackal** [comment]
what version of ubuntu did you use??

**Comment by TheSerapher** [comment]
With a few tweaks MPOS runs with Ubuntu 16.04. Search this issue tracker for a ticket with a guide URL in it.

**Comment by zhiyan114** [comment]
V16 won't work only v14

**Comment by TheSerapher** [comment]
See here: https://github.com/MPOS/php-mpos/issues/2566
