### ISSUE TITLE
Explanation request / possible hack for difficulty alignment between stratum and MPOS

### ISSUE THREAD

**Issue by HashUnlimited** [MPOS/php-mpos#2561]
Hi there,

I'm looking in to the possibility to display proper values in MPOS while running multiple instances of stratum. 

Setup: one node instance (not accounting the backups), 4 x stratum instance, one DB instance, one MPOS instance

The background is that our token has some specialities inside - so the network hash rate currently varies between 4 GH/s and 100 GH/s Scrypt.

This requires our "small" ones like CPU/GPU miners to be able to connect as well as rushing in with a tremendous amount of rent power, for example from Nicehash. Now equalising the POOL_TARGET throughout all stratum instances is not an option since it's the starting diff and there for necessary to be set high for Nicehash & Co. But the small ones starting at this high diff are going to get disconnected since they are unable to produce a single share in reasonable time so that they could be re-targetted. There for I need at least one instance running on lower target.

Now I'm searching for a way to work around this problem, did some unsuccessful tests on the stratum side already. But I do not totally understand how this POOL_TARGET is effectively going into the frontend since we are using VarDiff. Probably some guys here can help me out.

BTW it's a great piece of frontend what you have pulled off here, have stocked up my BTC holdings yesterday and will of course shortly show my gratitude.

Thx

**Comment by TheSerapher** [comment]
If you are storing with vardiff and it's inserted into the database there isn't anything to do with MPOS. It's been used for Litecoins in the past using variable diff without issues.

**Comment by TheSerapher** [comment]
PS: Thanks for the offer of a donation! I'd have to check that my BTC address is till valid :-) Or I could offer a broker address I use since it'll be easier for me than downloading the entire chain again.

**Comment by HashUnlimited** [comment]
yep, gib mal addi

http://www.pm-tech.at <http://www.pm-tech.at/>

Ing. Michael Polzer
Schoßbachstraße 21
9400 Wolfsberg

UID: ATU60129328
Tel. +43 664 28 68 800
Email: hashpower@pm-tech.at

**Comment by TheSerapher** [comment]
Great and thanks :-) I'll grab the Keychain and check for it :-)
