### ISSUE TITLE
Ethereum compatability

### ISSUE THREAD

**Issue by imnuruddin** [MPOS/php-mpos#2562]
I would like to run MPOS as ethereum pool, but I am getting `Unable to load your coins class definition for Ethash` error since Ethereum uses Ethash as an algorithm. How can I implement Ethereum

**Comment by TheSerapher** [comment]
There is no official support but it seems you can check here to find help how to modify MPOS to work with it: https://github.com/ocminer/ethcore-pool-mpos

I am not sure if this can be added in a generic way to MPOS itself without adding a lot of complexity to it. From what I read, these are RPC changes so just adding the coin class alone won't do the trick. Sadly the change itself is not mentioned and kept private, but maybe you can find help there :)
