### ISSUE TITLE
No payments are done

### ISSUE THREAD

**Issue by mario1987** [MPOS/php-mpos#2564]
I have this problem with prop using MPOS with NOMP the found blocks are not shared among the miners 

proportional_payout |   | ERROR |   |   | 07/07/2017 09:44:28 | 07/07/2017 09:44:28 | No shares found for block

**Comment by TheSerapher** [comment]
Ensure NOMP is set to MPOS mode and shares are inserted to the database. Also NOMP payouts must be disabled.

If properly setup there should be no issues running NOMP with MPOS.
