### ISSUE TITLE
blockupdate		ERROR

### ISSUE THREAD

**Issue by mraksoll** [MPOS/php-mpos#2568]
1 | 2 | 3
-- | -- | --
blockupdate |   | ERROR

I fix this problem but how now enable ? it's not stop say the of error :/

**Comment by mraksoll** [comment]
add -f for crone job end run it on admin panel

**Comment by mraksoll** [comment]
xxx.sh -f

**Comment by TheSerapher** [comment]
Correct, cron script with -f for force.
