### ISSUE TITLE
Help creating POOL using MPOS

### ISSUE THREAD

**Issue by didraro** [MPOS/php-mpos#2571]
Can someone give me an full tutorial of creating VPS Pool wit MPOS for any coin , zetacoin , peercoin , bitcoin , any coin . 

Please i did try much tutorials and i can not succes .

**Comment by TheSerapher** [comment]
This is not a support forum or setup guide, this is a bug tracker. Please try other places to find setup help if the existing guides usable via Google or even this Wiki are not sufficient.
