### ISSUE TITLE
how do i add support for ethereum?

### ISSUE THREAD

**Issue by k1ng440** [MPOS/php-mpos#2576]
thanks

**Comment by TheSerapher** [comment]
Simply put, you can't with MPOS Core: https://github.com/MPOS/php-mpos/issues/2506#issuecomment-226103881

RPC Calls for Geth are completely different to the implementation in MPOS and hence won't work at all unless you do some core changes. I have no idea what these are nor do I think they could be added in a 'generic' enough way to not break other coins. So either find a pool operator willing to share these changes or mine on existing pools.
