### ISSUE TITLE
MPOS Dashboard Values

### ISSUE THREAD

**Issue by rahulmanuwas** [MPOS/php-mpos#2578]
Hi, I was hoping if one of the core developers could answer this question: 
[https://bitcoin.stackexchange.com/questions/56834/what-do-all-of-the-items-in-the-output-from-mpos-mean](url)

Sorry for submitting this as an issue.

**Comment by TheSerapher** [comment]
If you know it's wrong, why do you cross post a question from Stackexchange into MPOS Bug Tracker? Closing this, please do not do this again.
