### ISSUE TITLE
its possible authenticate workers without account? only with wallet address..

### ISSUE THREAD

**Issue by minerpool** [MPOS/php-mpos#2580]
when people mining only working with account and workers 
`./ZecMiner64 -zpool stratum+tcp://zenpool.com:3032 -zwal Weblogin.WorkerName -zpsw WorkerPassword `

its possible authenticate workers with wallet address pre-registrated on mpos..???

`-zpool ssl://zenpool.org:3032 -zwal znhGeka9zXmixvw6ufzGpcaSXcSACrjx5WZ.example -zpsw x`
thanks

**Comment by TheSerapher** [comment]
No.
