### ISSUE TITLE
MySQL 5.7 Bug: Problem with Workaround

### ISSUE THREAD

**Issue by zimbo123** [MPOS/php-mpos#2585]
Hello,

i have the same Problem.
But i didn't understand the Workaround.
I wrote in the SQL-Consle of the MPOS-Database

set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

But the Problem wasn't solved. Where is my mistake?
Who can help me?
Sorry, but my SQL-KnowHow is very low.
Thank you very much.

**Comment by TheSerapher** [comment]
First make sure that the bug really is your issue. It may be something else triggering an error. Other than that the command looks good. You also don't define your exact issue so it's hard to assist.

**Comment by zimbo123** [comment]
The bug was my issue. But i found the solution. I made the Workaround again and it works. I don't why not before.
Thank you very much
