### ISSUE TITLE
Altcoins

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [MPOS/php-mpos#2587]
There is in the future to implement altcoins?
Like Monero ( CryptoNote/CryptoNight )

**Comment by TheSerapher** [comment]
No, there is no more active development on MPOS on my part. It's still usable but no more work been done for 3 years (i think). No plans to come back either, it was a hobby project to learn more about crypto mining and pools. It replaced an unreliable software I used to get started and got more traction than I expected.
