### ISSUE TITLE
getSharesForAccounts returns nothing

### ISSUE THREAD

**Issue by GQM** [MPOS/php-mpos#2588]
I've reset the database with a clean install and have run into a problem with payouts not completing. Curious if anyone is familiar with how `$share->getSharesForAccounts` works as this seems to be where the problem is.

https://github.com/MPOS/php-mpos/blob/b7b45eb580dfd7f683540b519a66e14d3fe8321d/include/classes/share.class.php#L96

> 2017-08-16 20:30:49 - DEBUG --> Starting PPLNS payout process
> 2017-08-16 20:30:49 - INFO --> |         PPLNS Target |        Actual Shares |   Height |     Amount |          Finder |
> 2017-08-16 20:30:49 - INFO --> |              1007616 |              1007616 |  1056333 |      10.25 |        ZenMiner |
> 2017-08-16 20:30:49 - DEBUG -->   Matching or exceeding PPLNS target of 1007616 with 1007616
> 2017-08-16 20:30:49 - DEBUG --> 1
> 2017-08-16 20:30:49 - DEBUG --> 
> 2017-08-16 20:30:49 - CRIT -->   No shares found for this block, aborted! Block Height : 1056333, Block ID: 1

**Comment by GQM** [comment]
Seems that its an issue with MySQL V5.7+

https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

When I run the query manually I'm getting:

`Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mpos.a.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

**Comment by TheSerapher** [comment]
See FAQ and searching tickets for my detailed explanation.
