### ISSUE TITLE
[BUG] [Workarround] Unable to update account: Unable to update account

### ISSUE THREAD

**Issue by zPools** [MPOS/php-mpos#2593]
Hi,
I experienced a bug while trying to update coin addresses.

Every time I tried to update the coin addresses, in the "My Account" Tab, the error "Unable to update account:Unable to update account" was showing.

I found out that the problem comes from MySQL, from the table `"coin_addresses"`

The problem is, that the "currency" field is limited to 5 characters. If you are using a altcoin which ticker name is longer than 5 characters, the problem will appear. 

You can either shorten the name of the coins ticker name, but that will look awful in many cases.

Or you edit the sql base structure file (MPOS/sql/):

Find:
 _`CREATE TABLE IF NOT EXISTS coin_addresses`_

Take a look at: _`currency varchar(5) NOT NULL,`_

Replace the 5 with the length you need:
 _`currency varchar(**6**) NOT NULL,`_

Save and exit

**If you have no data on the database**, I would recommend to drop the database and import the new structure 

`mysql -u (mysql user) -p`
`DROP DATABASE (database name);`
`exit`
`sudo mysql -p -e "create database mpos"`
`sudo mysql -p mpos < sql/000_base_structure.sql`

And now, the bug should be gone.

Of course you can use phpmyadmin, or mysql itself, to change the value on the field, if you are fit enough in either of those

**Comment by TheSerapher** [comment]
Following that logic, even 6 can be not enough someday. When writing MPOS the basic length for coins was about 3-5 letters (BTC,LTC, etc.) hence it was limited to 5 chars which seemed enough. Which coin is now using more than these letters as a short handle for the coin? Seems weird ..

**Comment by TheSerapher** [comment]
Probably useful information for others, and maybe something that could be added as a mysql Upgrade at some point. For now I'd handle these as the odd ones and not implement it into the core.
