### ISSUE TITLE
Cronjob error

### ISSUE THREAD

**Issue by loctai** [MPOS/php-mpos#2595]
PHP Warning:  chdir(): open_basedir restriction in effect. File(/var/www/html/MPOS/cronjobs) is not within the allowed path(s): (/var/www/foo.bar/:/usr/local/php/) in /var/www/html/MPOS/cronjobs/findblock.php on line 23
PHP Warning:  require_once(): open_basedir restriction in effect. File(/var/www/html/MPOS/cronjobs/shared.inc.php) is not within the allowed path(s): (/var/www/foo.bar/:/usr/local/php/) in /var/www/html/MPOS/cronjobs/findblock.php on line 26
PHP Warning:  require_once(/var/www/html/MPOS/cronjobs/shared.inc.php): failed to open stream: Operation not permitted in /var/www/html/MPOS/cronjobs/findblock.php on line 26
PHP Fatal error:  require_once(): Failed opening required 'shared.inc.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/MPOS/cronjobs/findblock.php on line 26
PHP Warning:  chdir(): open_basedir restriction in effect. File(/var/www/html/MPOS/cronjobs) is not within the allowed path(s): (/var/www/foo.bar/:/usr/local/php/) in /var/www/html/MPOS/cronjobs/proportional_payout.php on line 23
PHP Warning:  require_once(): open_basedir restriction in effect. File(/var/www/html/MPOS/cronjobs/shared.inc.php) is not within the allowed path(s): (/var/www/foo.bar/:/usr/local/php/) in /var/www/html/MPOS/cronjobs/proportional_payout.php on line 26
PHP Warning:  require_once(/var/www/html/MPOS/cronjobs/shared.inc.php): failed to open stream: Operation not permitted in /var/www/html/MPOS/cronjobs/proportional_payout.php on line 26
PHP Fatal error:  require_once(): Failed opening required 'shared.inc.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/MPOS/cronjobs/proportional_payout.php on line 26

please Help me fix it

**Comment by TheSerapher** [comment]
PHP Warning which you can Google for, not an issue with MPOS itself. Properly configure your PHP setup and you will be fine.

`PHP Warning: chdir(): open_basedir restriction in effect`
