### ISSUE TITLE
seems stuck on maintenance mode

### ISSUE THREAD

**Issue by htskltd91989** [MPOS/php-mpos#2596]
after enabling maintenance mode to update wallet, it seems findblock is stuck on maintenance mode. I've tried to force run all crons with -f, but only this one remains stuck.

![image](https://user-images.githubusercontent.com/29922967/30558005-0c59d67e-9c7e-11e7-99af-da3030ee0836.png)

Also, is it normal for everything to be checked as both "active" and "disabled" at the same time??

To be super clear - maintenance mode is not currently enabled on my pool

**Comment by TheSerapher** [comment]
Have you disabled maintenance mode and checked the log file for errors?

**Comment by htskltd91989** [comment]
Yes maintenance mode is disabled. the Log says:

2017-09-19 12:34:01 - CRIT --> Unable to start cronjob: Cron is already active in database: findblock_active is 1, please force run with -f once ensured it' not running

I went to the sql database, changed from 1 to 0 for disabled and ran with -f....no luck. Same error.

**Comment by TheSerapher** [comment]
Have you disabled all cron processing before trying this out? Maybe it did start up in the meantime and the real error is something else? It's doubly strange because the status in the monitoring is not updated at all so it could be having issues someplace else.

Try removing all references to this cron in your monitoring table. That way we are sure it's clean. And disable crons, then run just find block itself and check for error output.

I am guessing there is an RPC issue that find block can't handle after the wallet upgrade which may be the root cause. You'll have to do some digging on your end to see why this upgrade started causing issues.

**Comment by htskltd91989** [comment]
Could you clarify what you mean when you say "remove all references to this cron in your monitoring table"?

**Comment by TheSerapher** [comment]
Check your database, there is a monitoring table - remove all entries for `findblock_*` in there. You will still have to disable the cron completely and manually check runtime for it, since I assume there is a different issue here caused by the wallet upgrade.

**Comment by htskltd91989** [comment]
Great, got it. I will keep you posted. Thanks for the prompt reply!

**Comment by htskltd91989** [comment]
Would it make sense that I'm getting this error because the pool has not
found a block yet?

PHP Fatal error:  Uncaught exception 'Exception' with message 'RPC
call did not return 200: HTTP error: 500 - JSON Response: [-8] Invalid
blockhash' in /root/mpos/include/lib/jsonRPCClient.php:120
Stack trace:
#0 /root/mpos/cronjobs/findblock.php(35):
jsonRPCClient->__call('listsinceblock', Array)
#1 /root/mpos/cronjobs/findblock.php(35): BitcoinWrapper->listsinceblock('')
#2 {main}
  thrown in /root/mpos/include/lib/jsonRPCClient.php on line 120

**Comment by TheSerapher** [comment]
Yes but mPOS seems to have blocks in its table and tried to fetch all new transactions since then. If this was a hard reset of the coin you should create a new pool so MPOS is aware of that.

**Comment by TheSerapher** [comment]
Or your coin simply can't handle an empty blockhash, which seems to be the reason here. In any case it's not something MPOS works around, so either check with the coin developers how they had this case in mind or "hack" a way around it.
