### ISSUE TITLE
MySQL 5.6, 5.7/Maria DB Support

### ISSUE THREAD

**Issue by ephieth0** [MPOS/php-mpos#2597]
We currently run php-mpos on MySQL 5.5 and want to move to a newer mysql version / maria db for better performance.

Talking about a bigger production environment with a lot of workers. We just want to make sure that everyhing runs in supported state.

I know about the limited MySQL 5.7 compatibilty on some queries. Whats about MySQL version 5.6 Support?

Additional to this, I'am also very interested in to switch to Maria DB. Is there any experience recommendation from your side?

Thanks a lot!

**Comment by TheSerapher** [comment]
Only 5.7 is not fully supported unless a workaround is in place. MariaDB has been in use by some other people but I can't tell which version may be affected by the same issue as MySQL 5.7.
