### ISSUE TITLE
Upgraded from somewhere in 2014 to now but now payouts

### ISSUE THREAD

**Issue by Bushstar** [MPOS/php-mpos#2601]
Upgraded from quite an old version, everything went really well considering the number of updates, I was expecting a lot of issues but it went smooth. Ran the SQL upgrade scripts, they took a long time but the completed. Copied new config and updated with local settings and had to tweak the Apache virtual host slightly. The pool went back up, blocks were found, everything appeared to be good.

However we got the pesky message.

"PPLNS payout disabled, round credit transactions are delayed"

Checking the PPLNS log we see this for the first block found after the pool came back up repeated again and again, all PPLNS logs for the last three days repeat this for every day,

    2017-09-25 6:32:41 - INFO --> |         PPLNS Target |        Actual Shares |   Height |     Amount |          Finder |
    2017-09-25 6:32:41 - INFO --> |            178739514 |            288266064 |   884757 |  400.36586 |           jmcab |
    2017-09-25 6:33:10 - CRIT -->   No shares found for this block, aborted! Block Height : 884757, Block ID: 318203

Checking the blocks table we see.

    select * from blocks where height=884757;
    +--------+--------+------------------------------------------------------------------+---------------+-----------+-----------------+------------+-----------+------------+--------------+-----------+------------+
    | id     | height | blockhash                                                        | confirmations | amount    | difficulty      | time       | accounted | account_id | worker_name  | shares    | share_id   |
    +--------+--------+------------------------------------------------------------------+---------------+-----------+-----------------+------------+-----------+------------+--------------+-----------+------------+
    | 318203 | 884757 | 3346da4b07e690977a4e7b5c160c20b577c5385563540ea4b031760f5a5a02ee |           127 | 400.36586 | 2114.0749221663 | 1506191540 |         0 |          8 | jmcab.jmcab3 | 288266064 | 1180360125 |
    +--------+--------+------------------------------------------------------------------+---------------+-----------+-----------------+------------+-----------+------------+--------------+-----------+------------+

Searching shares for the shares ID I see.

    select * from shares where id=1180360125 ;
    +------------+----------------+--------------+------------+-----------------+--------+------------------------------------------------------------------+------------+---------------------+
    | id         | rem_host       | username     | our_result | upstream_result | reason | solution                                                         | difficulty | time                |
    +------------+----------------+--------------+------------+-----------------+--------+------------------------------------------------------------------+------------+---------------------+
    | 1180360125 | 104.131.104.33 | jmcab.jmcab3 | Y          | Y               |        | 3346da4b07e690977a4e7b5c160c20b577c5385563540ea4b031760f5a5a02ee |       1024 | 2017-09-23 14:32:36 |
    +------------+----------------+--------------+------------+-----------------+--------+------------------------------------------------------------------+------------+---------------------+

I'm not totally sure where I should be looking, I imagine that there has to be more share records against that block but do not know where to look for them. Mining of blocks is certainly working and we have 150+ people on the pool. Without payouts people are getting a bit panicky and I'm not totally sure where to look from here. Any guidance here would be appreciated.

**Comment by TheSerapher** [comment]
Maybe check FAQ for MySQL 5.7 Workaround. Smells like that =)

**Comment by Bushstar** [comment]
Spot on. Running MySQL 5.7, running the following workaround from the FAQ fixed the issue.

    set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

**Comment by TheSerapher** [comment]
Be aware that this is temporary, you have to also add it to you my.cnf to make it permanent.

**Comment by Bushstar** [comment]
Top tip. Added to my.cnf.

```
[mysqld]
 sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
```
