### ISSUE TITLE
You have an error in your SQL syntax

### ISSUE THREAD

**Issue by Caberhagen** [MPOS/php-mpos#2606]
Hi at all.

I have installed tody mpos.
On a Debian 8 System with mysql 5.5.
The Website is working and the crons do her job.
But on registering an account following error are show:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '******.accounts (username, pass, email, signup_timestamp, pin, api_key, is_adm' at line 1 

CU

**Comment by Caberhagen** [comment]
Which is the suportet mysql version of 1.0.7?
Tried today different versions.
Allways i get the mysql error at registering the first account.

Thnx for any help

**Comment by TheSerapher** [comment]
Can’t check right now but anyone able to confirm this? I tried setting up a pool with 1.0.7 a while ago and haven’t had any issues. Can you try checking out 1.0.6 and running a setup with that?

**Comment by Caberhagen** [comment]
Hi Sebastian,

May be tomorrow i can start a test with 1.0.6.


Am 30.09.2017 19:11 schrieb "Sebastian Grewe" <notifications@github.com>:

**Comment by Caberhagen** [comment]
Hi Sebastian,
i fired up version 1.0.6 now.
First i get the error. Unable to find your selected theme `` in the list of available themes. Please reset your `website_theme` setting in your database.

Added fix from 1.0.7 in smarty.globals, now the page ok.

But i have the same error on registering first account.

I don't find any usefull hints in Logs! 

My System:
Debian 8.8
Mysql Ver 14.14 Distrib 5.5.57
PHP 5.6.30-0+deb8u1

I am happy for any idea....

**Comment by TheSerapher** [comment]
That sounds like a local issue then. I do remember setting up at least 1.0.6 on Ubuntu with MySQL around that version as well and had no issues. Maybe double check your config and see if it may be caused by a wrong string someplace.

**Comment by Caberhagen** [comment]
Yes seems like ever i have a local issue.
I tri to find the solution.

Am 01.10.2017 9:59 vorm. schrieb "Sebastian Grewe" <notifications@github.com

**Comment by Caberhagen** [comment]
I found the problem-
I used in coin db-name some - charakters.
seems thats the problem.
now its working. 
sorry 
CU
