### ISSUE TITLE
This web app sucks

### ISSUE THREAD

**Issue by Volxz** [MPOS/php-mpos#2607]
Anyone down to rebuild this properly in PHP Laravel or some non-ancient secure framework?
I hate this with a passion, we use it on over 10 pools and it has been the biggest pain in the ass, starting with ergonomic error pages to not loading on misconfiguration. Smarty is absolute garbage and so is the community backing it. We need to make this better as a community. Anyone who is interested in building something that actually works properly and people can expand upon send me a message via email.

Love ya all but I hate smarty and poorly written code <3

**Comment by TheSerapher** [comment]
And I agree! This was just a project to learn about pooled mining and mining in general. It just grew out of proportion. Not to mention that I could have used a framework and decided not to in order to learn as much as possible.

Poor decision on my part back then.

I am still supporting this only because nobody else came up with a better, widely accepted solution. They either lacked features or the completeness of this Web UI.

By all means, start a new project and get it out so this can finally closed for good. Though I would have chosen the words more delicately since this still is “my little baby” which I am proud of ;-)

**Comment by Volxz** [comment]
For sure it is amazing and one of a kind. I'm very glad you went open source and contributed to the community so much. Sorry if I insulted your little baby :P. If you know of anyone who is experienced with pooled mining I would be glad to learn and build the next mpos :P

**Comment by Volxz** [comment]
@TheSerapher

**Comment by TheSerapher** [comment]
Not many are that experienced to start this from scratch. Mostly end users around here that don’t know anything going on in the backend.

I started working on a successor years ago built on Symfony2 - I had accounts and workers ready and then realized that the entire backend is most of the work. If you want to be quick just integrate the current stratum systems via shares table and work the rest around it. It’s much easier (and faster) to get started that way before deciding to built the entire framework for mining. Let others worry about Stratum and handle share processing only.

There is plenty of code you can look at in MPOS on how things work. I will try to help when time allows but I won’t be coding anything anymore :-)

**Comment by shtse8** [comment]
I want to join and now rewrite many parts of the codes already.

**Comment by TheSerapher** [comment]
It was a one man show by someone that only scratched the surface of PHP back then. Time to pass on the torch and start a new project that does things better. Proper coding style, fully integrated tests and a build pipeline to ensure things are working. It’s your (erveryone) turn now to keep things going. MPOS just showed it’s possible at all, now make it good ;-)

**Comment by shtse8** [comment]
I have already done the best. It's the best pool I have ever seem.

**Comment by xisi** [comment]
The issue, like many projects, is a few hundred thousand lines of code that everyone agrees "isn't the best written" but works. It's easy to critique, but here we are again with complaints and no PR or code to speak of.

**Comment by TheSerapher** [comment]
Very well put @xisi - if it’s stupid but works, it ain’t stupid ;-)

**Comment by Volxz** [comment]
Don't get me wrong it's an amazing project and works like a charm 95% of the time. I want to rewrite this to be more up to date and easily maintainable by the community so I feel as if rewriting in laravel or something g similar would be ideal. I'd anyone wants to pull this off with me let me know because I can only imagine how much work was put into this and how much we will have to put in for a new version of mpos.

**Comment by nrpatten** [comment]
@Volxz  Why don't you build a front and backend of your own design that works 99% of the time that is as easy to setup as MPOS with a comprehensive Wiki and has all the API data and stats MPOS does, Once you do this then you have the right to critique MPOS, Until then your just talking and disregarding the 1000's of hours of coding that people put into making MPOS the best "FREE OPEN SOURCE SOFTWARE" it could be at the time. My 2 cents.

**Comment by TnTBass** [comment]
I'd agree with @TheSerapher.  If anyone wants to undertake writing a new front end, that would be far easier than rewriting a stratum as well.
https://github.com/krisklosterman/node-open-mining-portal is a fork of the original nomp and is intended to have future development.  If anyone wants to take on writing a new MPOS, I'd suggest working with the dev of this fork of nomp and make something awesome together.

**Comment by TheSerapher** [comment]
NOMP is great and simple, large support for coins and very well performing. Only issue is that modes like PPLNS that rely on specific time stamps per share to be stored won’t work well with it. The Redis Backend is a key value store and adding time stamps will pretty much eliminate any performance gain from using Redis - you’d be back at a relational Database at that point.

Probably one of the reasons why it wasn’t more accepted and pretty much used in MPOS compatibility mode when I saw it around.

As a hint, most parts of MPOS are straight forward. Especially if you decide to drop the entire use management aspect and allow for coin addresses to be used only. It takes away a lot of the community feeling when mining, but you could just as elk support both at the same time or at least make the pool Admin select the mode.

It took me less than a day to get users and workers running on something like Symfony2, the hard part comes later when combining that with a backend for payouts ... then it gets complicated ;-)

I also looked at Ruby, which comes with great tools to run background processing tasks and a sync workers. Really cool stuff and may have become MPOS v2 down the road. Then again life happened and I got other stuff to worry about than programming - so maybe someone else will pick it up.

**Comment by TheSerapher** [comment]
Closing since not much to be added here.
