### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by d1mf** [MPOS/php-mpos#2608]
cd stratum-mining
git submodule init
git submodule update
cd externals/litecoin_scrypt
sudo python setup.py install
cd ~
cd stratum-mining/externals/stratum

**sudo python setup.py install**
_RuntimeError: maximum recursion depth exceeded_  
I can not solve this error
Ubuntu 17.04

**Comment by Caberhagen** [comment]
Hi
You have to ask at the stratum project.
You issue is stratum related not from the mpos project.

**Comment by d1mf** [comment]
ok.ty
