### ISSUE TITLE
go die in hell fagots and return my money that you stole!

### ISSUE THREAD

**Issue by olegai** [MPOS/php-mpos#2609]
for a whole hour all hashes rejected from 6 rigs.. 20usd you owe me fags

**Comment by TheSerapher** [comment]
This is not a pool operator but the Software you are running on. If you have a gripe with a pool, and more specifically with a Stratum that sends out work units which apparently got rejected, bring it up with your pool operator. This is a bug tracker which coincidentally has nothing to do with shares being accepted or rejected. That’s all stratums work.
