### ISSUE TITLE
API, Server too busy. Please try again later.

### ISSUE THREAD

**Issue by hunasdf** [MPOS/php-mpos#2611]
Dear Developers,

I develop an iOS application which support your php-mpos too. Sometimes, when I start an API request to "getdashboarddata", the response is "HTTP 503 Service Unavailable" (Server too busy. Please try again later.). What may is the problem? Is this a core problem, or web page specific? Can I fix somehow on device side? Can we solve it somehow?

For example https://dgbs.suprnova.cc/ return this error for me. Sometimes https://ubiq.suprnova.cc/ too.

App is available on App Store, so you can check it: https://itunes.apple.com/us/app/asis-mining-pool-monitor/id1274075951?l=us&mt=8

Thanks for your answer!
Best regards,
Gergo

**Comment by TheSerapher** [comment]
As the error indicates the other end is too busy with web requests so it results in a 503. It can also be returned if you are calling data too fast and something tries to throttle you.

Could be anything really and probably not something that needs fixing in MPOS.
