### ISSUE TITLE
low worker difficulty

### ISSUE THREAD

**Issue by vetal20600** [MPOS/php-mpos#2613]
hello mpos community. I want to give an advice about how to avoid this situation? what worker setting this message suggests to adjust? it's unclear for me.

"one or more workers of this rig has been assigned a share/worker difficulty by your pool is **too low**. **Hashrate performance may occur**.
Please either adjust your worker settings at your pool, or change pools if you are unable to do this at your current pool. Thanks!"
![_feffe](https://user-images.githubusercontent.com/4103746/31239757-dba885fc-aa06-11e7-80a1-81213a5d63f5.png)

**Comment by TheSerapher** [comment]
That’s not an MPOS Message, ask your pool operator that runs a modified version it seems.

And this is again stratum related, also wrong place to ask.

**Comment by TheSerapher** [comment]
If that’s a message from your miner, also the wrong place to ask. Pool operator has to adjust stuff for you or you need to connect to another worker process with higher share difficulty.

**Comment by vetal20600** [comment]
@TheSerapher can you guess where it the better place to ask? Thanks
