### ISSUE TITLE
Small issue with LTC. Est Earnings in admin dashboard's round information

### ISSUE THREAD

**Issue by Coinizy1** [MPOS/php-mpos#2615]
Hi, Why i am seeing this LTC. Est Earnings in my admin dashboard it is saying me 49.50000 even i had a miner connected for few seconds only.
Thanks
Round Information
1291114

Current Block

0.00%

Of Expected Shares

49.50000000

LTC Est. Earnings

977,949.42795694

Difficulty

917,941.19565919

Est Next Difficulty
Change in 1148 Blocks

1166739113949:10:00

Est. Avg. Time per Block

**Comment by Coinizy1** [comment]
Also, It is showing "

Current Active Workers | 0
-- | --

" in general statistics in "/index.php?page=statistics&action=pool" Even if i have connected my miner again.
Thanks

**Comment by Coinizy1** [comment]
shall i used the automatic difficulty method?  because it is saying me current difficulty is 4
Please guide a little
thanks

**Comment by Coinizy1** [comment]
Please give me some information on these things
http://prntscr.com/gun0rb
Why the difficulty is 4 and why it is showing 7.0000 somehting in LTC Est eArnings
Thanks

**Comment by TheSerapher** [comment]
For basic help on operating a pool and understanding how mining works you should go ask the community at any forum of your choice. This is a big tracker only and not a support forum.

There is nothing wrong with MPOS. It just shows information based on valid shares submitted.

**Comment by Coinizy1** [comment]
Thank you, i know my question was very noob.  Does it count estimated dollars per month or LTC per month on current hashrate?
thanks

**Comment by TheSerapher** [comment]
LTC for the round (when block is found). For a more average earnings estimate find calculators online. But if you pay for power it may not be worth it, just FYI.

**Comment by Coinizy1** [comment]
Thank YOU Sir.
Love you :)
