### ISSUE TITLE
Worker hashrate drops when connecting more than 1 machne

### ISSUE THREAD

**Issue by xslugx** [MPOS/php-mpos#2617]
I have been working on setting up a mining pool using MPOS and have been thinking of using coiniumserv as well. however I have MPOS running right now with stratum-mining and any time I connect more than 1 L3+ to a worker it drops hashrate to 0 for that worker. However My miner shows its submitting shares.

**Comment by TheSerapher** [comment]
They have to be valid shares, sounds more of a Stratum issue than MPOS though. If shares aren't added properly MPOS will not see them and not be able to calculate a hash rate.

**Comment by xslugx** [comment]
@TheSerapher thanks, I figured as much. I will dig deeper, however I did not see any log files for stratum, so more testing it is.
