### ISSUE TITLE
Coins missing. Have we been hacked?

### ISSUE THREAD

**Issue by Bushstar** [MPOS/php-mpos#2619]
No one has been paid in the last couple of days so I check the pool, we had millions of coins totalling a lot of dollars, now there are only ~6,000 coins left. Lots of outgoings TXs broken down into amounts of 19 or 38 coins a piece.

http://explorer.artbyte.me/tx/526ce8218468c8c44ba9bd9d5e1d2214a1c7bcf43534c60d82d6ffab9ce798c3

The admin settings shows the following for balance.

Wallet Balance | 6,547.43772366
Locked for users | 1,516,827.03223133
Unconfirmed | 400.03360000
Liquid Assets | -1,510,679.62810767

This is followed by liquid assets showing as the amount about as a negative value plus 6,000.

Cold wallet is set to 0.

Does it look like we've lost the coins to a hack?

**Comment by TheSerapher** [comment]
IN the past most coin losses seen happened due to either a misconfiguraion, insecure configuration of any upstream service or simple oversights (backup configs readable from the web). It could be anything in your case so you’d have to do some forensics to find how they got removed. Not much I can tell from MPOS since it doesn’t have a whole lot of permissions to do so.

**Comment by KevinBiomech** [comment]
I had a similar situation and complete restart of the pool solved it. I
never did figure out what happened, but it did work. If you already went
there, disregard this.

**Comment by Bushstar** [comment]
Restart did not help unfortunately. If this gets figured out I'll report back here I was vainly hoping that MPOS might have put the coins in a .dat somewhere. I'll go read up on the cold wallet functionality as I'm not familiar with how that works.

**Comment by Bushstar** [comment]
Look to my like the block bonus was set to 6% with 400 connections. It seems that the pool spent people's mined coins to pay the bonus.

Does the pool normally prevent the block bonus from being paid from everyone's coin or is that an issue with our setup?

**Comment by Bushstar** [comment]
I did the maths, right now we have 200 connections, we've seen a lot more but not consistently and we've seen less so let's use 200 for now. We mined 76 blocks in the period, with the 6% we would have paid out 395200, for the 18,400 coins we mined. We lost 5 million coins in the period and looking at the explorer I can see that sometimes the bonus was paid in triplicate so it was not just the bonus but the bonus paid several times over.

**Comment by TheSerapher** [comment]
Block bonus are paid out of your pocket. It’s not something paid of the block itself. Each block is paid to all users that mine and you added a 6% bonus to it.

In any case that’s a setup issue.

**Comment by TheSerapher** [comment]
And keep in mind that block explorer only shows payouts that have been done due to users payout settings. Users usually don’t pay out the same way so you won’t see the block payouts in those transactions but only what users wanted to get paid out.

**Comment by FeatherCoin** [comment]
The problem seems to be that the bonus was paid in triplicate until all the coins we gone. Does the pool allow the wallet balance to go below the amount locked for users?

I think it would be sensible for MPOS to check the wallet balance and disable the bonus when the extra funds have run out.

**Comment by Bushstar** [comment]
Oops, I am in my phone and was logged in on the wrong account. Scripts were set to force, I wonder if this resulted in triple bonuses.

**Comment by TheSerapher** [comment]
Yes it does since you are paying a block bonus which will automatically let the wallet go below what's available to users. If you don't have the coins off-hand do not pay any block bonuses to attract new users. It will cost you money to do so.

As mentioned by Bushtar, it was a forced payout. Each time you force a failed payout it will start from the beginning basically paying out users again. If payouts fail, deep investigate why they failed and not blindly run the cron again hoping for the best. It will fall on your feet at some point. Even if a force worked 10 times, the one time you miss why it failed you double pay your users from your own wallet.

MPOS will not do a sanity check if you have money to do so or not. It's not maintained anymore and no new features will be added. The way it works is also mentioned in the Wiki and operators should make sure they checked it: https://github.com/MPOS/php-mpos/wiki/Config-Setup#block-bonus

I consider this issue closed, everything that needed to be said was said :)

**Comment by Bushstar** [comment]
Thanks. That does clear it up for me and this matter can be laid to rest. There was a fault but payouts were force so bonuses were paid several times over. The force option was set by the person who initially set the pool up, we left it in place after the upgrade. I'll remove the option and if it fails in future we will investigate rather than force it.

**Comment by olegkhylyuk** [comment]
Hello. COINS IS MISING. I sended ffrom Bittrex exchange to my ABY wallet. But i did'nt recive it. 

Status on Bittrex: 10/14/2017 | ABY | 399060.95223100 | Completed

TxId: 48f98b2c2a3f553acc628cc8e8b40195fc605f1342332b1c2203474b0b1736a3

Where is these coins?

**Comment by TheSerapher** [comment]
Please do not spam this issue tracker with personal issues with a pool, pool operator or coin exchange. This is a big tracker only and has no control over how people run their peoples. And top top it off you hijacked a topic with your question.

Please contact those responsible, not this software ..

**Comment by Bushstar** [comment]
olegkhylyuk please go to the ArtByte forum.

**Comment by Bushstar** [comment]
We very recently added multiple instances of stratum on different ports with different minimum difficulties to separate CPU, GPU, ASIC and farms. I noticed that users were connecting the same worker to multiple ports. This solution seems to be employed by other pools so it seemed like a good idea at the time.

I'm wondering if the bonus was then paid several times over for each worker connection.

Does this sound plausible?

**Comment by olegkhylyuk** [comment]
--Надіслано з мобільної Яндекс.Пошти15.10.2017, 02:22, "Peter Bushnell" <notifications@github.com>:We very recently added multiple instances of stratum on different ports with different minimum difficulties to separate CPU, GPU, ASIC and farms. I noticed that users were connecting the same worker to multiple ports. This solution seems to be employed by other pools so it seemed like a good idea at the time.
I'm wondering if the bonus was then paid several times over for each worker connection.
Does this sound plausible?

**Comment by olegkhylyuk** [comment]
I. Received it already. Thanks --Надіслано з мобільної Яндекс.Пошти15.10.2017, 02:22, "Peter Bushnell" <notifications@github.com>:We very recently added multiple instances of stratum on different ports with different minimum difficulties to separate CPU, GPU, ASIC and farms. I noticed that users were connecting the same worker to multiple ports. This solution seems to be employed by other pools so it seemed like a good idea at the time.
I'm wondering if the bonus was then paid several times over for each worker connection.
Does this sound plausible?

**Comment by Bushstar** [comment]
olegkhylyuk You are subscribed to the GitHub issue you posted on and receive emails every time someone adds a comment, any email responses you send will automatically be added to the conversation here. You will want to ignore any further emails from this issue.

https://github.com/MPOS/php-mpos/issues/2619

**Comment by KevinBiomech** [comment]
You can definitely multiple ports in one instance of stratum. That is what
I did without problems.

**Comment by Bushstar** [comment]
Sure, but does that work if you have a pool_bonus set?

**Comment by TheSerapher** [comment]
No because workers are merged into accounts and summarized. This will not cause multiple payouts. A forced Cron would.

**Comment by Bushstar** [comment]
It's happening again and this time we have no errors and the payout script is not being forced.

http://explorer.artbyte.me/tx/617918a9436a2e72fbb2f439ea7bfe131f8b4990d4ff52dbd48e9314f4cf00cc

Everything seemed to be okay and then the pool pays out 100,000+ more than expected taking the liquid assets into negative balance so not from the locked user funds. The blocks have a 400 coin reward, the bonus is 1%, in the TX above the 3.9 coin payments are the bonuses, the 400 coin payments are to consecutively created accounts, so account ID 3230, 3231, 3232 and so on. 

I checked a couple of the consecutive accounts, they are on the same IP address for 100 to 1,000 shares before changing IP and they are mining with the lowest possible vardiff so will be CPU mining for the bonus yet they got paid a block worth of coins. 

I checked the shares_archive table and one of the accounts that got credited 400 coins only has a record of five shares being submitted.

I'm not sure how this is happening, everything was running well and then suddenly we haemorrhaged coins.

**Comment by TheSerapher** [comment]
Check the transactions table - for any payout done there should be a proper transaction. MPOS payouts are very reliable and issues have been unheard off when it would overlay users unless something was changed or setup wrong. I can’t be of much help since I am not actively developing nor supporting MPOS anymore. Maybe you can find help of others of the community or subscribed to this topic?

**Comment by Bushstar** [comment]
Thanks for the tip, the transaction history does show that they have been contributing for a long time and amassed 400 coins per account. The shares_archive appears to have been purged which made me reach the wrong conclusion.

Does the bonus coins owed to an account count towards the locked coin total on the wallet information page?

The fact that we went into negative balance made me thing this was in addition to the coins owed to users but if bonus coins already calculated as belonging to an account but not the total locked coin sum then that would explain it.

**Comment by TheSerapher** [comment]
Bonus coins are calculated just like any other coins and are added as a positive transaction locking coins in the wallet for users. MPOS doesn’t care where a payment comes from, it’s always locked coins for users.

**Comment by TheSerapher** [comment]
THtat is as far as I remember it :D

**Comment by sunk818** [comment]
this seems to be an issue with PPLNS and having a bonus attached to it. How many blocks does one share in PPLNS count toward a worker? if all you need to do is submit 1-4 acceptable hashes and that keeps your bonus alive for the last 10 found blocks (?), then you would certainly cycle through many pool accounts. scrypt miners like cgminer have ways to rotate pool accounts in a round robin style.

> We mined 76 blocks in the period, with the 6% we would have paid out 395200, 
> for the 18,400 coins we mined. We lost 5 million coins

If you look at the PPLNS rounds on the pool for block 893,947, I counted about 2364 PPLNS round shares. workers. So, 5 million coins divided by 76 blocks divided by 2364 PPLNS shares is about 27.82 coins which is very close to 24 bonus coins.

I think if you look at blocks from 870,000 (2017-09-02) to 880,000 (2017-09-16) that is where you will find your answer. I looked at Round Transactions, Round Shares, and PPLNS Round Shares. That is when the growth started occurring.

**Comment by Bushstar** [comment]
Locked coins as shown in the admin panel are 1,346,229.92947656

SQL queries against the transactions, seems to me that once these have been paid then archived is changed to 1.

```
select SUM(amount) from transactions where archived=0 and type='Credit';
2565043.0176066

select SUM(amount) from transactions where archived=0 and type='Bonus';
956128.75304437

select SUM(amount) from transactions where archived=0 and (type='Bonus' or type='Credit');
3521171.77065097

select SUM(amount) from transactions where archived = 0 and type='Fee';
48566.28651532

select SUM(amount) from transactions where archived=0 and type='Donation';
8289.26930743
```

Total owed in bonus and credit is 3,521,171, bonus and fee makes little impact, but the amount shown as locked in the backend is 1,346,229. I wondered why we went into negative assets so soon, we owe a lot more than expected if I'm getting this right. Checking my account any TXs showing as Credit or Bonus is found in the transactions table and is what I get paid to my wallet.

@sunk818 As to the bonus I assume users only need submit one share for a block to get the bonus. Does this behaviour change if we switch to prop?

**Comment by sunk818** [comment]
Sorry I'm not sure. Maybe you can try contacting a pool operator like Pooler on the litecoin pool (he is on Bitcoin talk) or maybe serapher is willing to answer. Wiki is here though https://github.com/MPOS/php-mpos/wiki/Config-Setup

I think you have about 1600 pool accounts that need to be kicked for having multiple accounts by the same person or same scam group.

**Comment by TheSerapher** [comment]
YES one share should be sufficient for a bonus.

I implemented bonus payouts as means for pool operators to help paying out “failed” payouts. If one block wasn’t paid properly a bonus could be added to pay it out eventually. It’s not meant to be enabled non-stop. I haven’t seen them used often other than in these cases so maybe this is a bad side effect of it. If anyone feels like feel free to dig into the code and find a fix :-)
