### ISSUE TITLE
No PPLNS shares for sole user

### ISSUE THREAD

**Issue by Bushstar** [MPOS/php-mpos#2622]
This is getting somewhat frustrating now, I think I'm getting pool fatigue!

Setting up a new pool, everything has gone very well, seems to be a good clean set up, MPOS + Crypto-Expert/stratum-mining. Mined five blocks on the pool. I'm the only person mining and should have all the shares shown in the pool overview.

We're set to PPLNS, but the block overview shows 0 PPLNS shares but millions of actual shares.

https://i.imgur.com/dsyqpoG.png

Only entry in config for payout.

    $config['payout_system'] = 'pplns';

Under earnings it shows 0.00000000 across the board. In the database I can see that all shares belong to my workers. 

The very first block that was found showed up like this in the pplns log.

    2017-10-13 23:09:03 - INFO --> |         PPLNS Target |        Actual Shares |   Height |     Amount |          Finder |
    2017-10-13 23:09:03 - INFO --> |            279052176 |            279052176 |   898793 |        400 |        bushstar |
    2017-10-13 23:09:04 - CRIT -->   No shares found for this block, aborted! Block Height : 898793, Block ID: 1

MySQL blocks table.

    | id | height | blockhash                                                        | confirmations | amount    | difficulty        | time       | accounted | account_id | worker_name | shares    | share_id |
    |  1 | 898793 | 92f46951c2b8f6ba75ffe5ccd3ea4081612498d990f5749d94cd71540fc4b16e |           120 |       400 | 1309.169013775394 | 1507936081 |         0 |          1 | bushstar.1  | 279052176 |   432025 |

Shares has 1,066,839 entries, here's the first line.

    | id | rem_host       | username   | our_result | upstream_result | reason | solution                                                         | difficulty | time                |
    |  1 | 81.141.245.126 | bushstar.1 | Y          | N               |        | c9ea313900af127d8e7f3d8a9f1eb27063ef60003fbf3a62aad48a4761b4b943 |         32 | 2017-10-13 16:15:32 |

**Comment by Bushstar** [comment]
Switching to ahmedbodi/stratum-mining just in case shares are being added to DB incorrectly or differently, the MPOS setup instructions says to use the ahmedbodi version. It is out-of-date compared to the Crypto-Expert version which also seems to be maintained by ahmedbodi.

**Comment by KevinBiomech** [comment]
Ahmed is a friend of mine, use the crypto-expert version. It's the main
version now. Unfortunately no idea what the issue is, since the DB seems to
be recording correctly. Its been about a year since I ran a pool.

**Comment by Bushstar** [comment]
It is odd. I've got a different pool that's working correctly so tried the version of Stratum from there in case it was recording in the DB incorrectly but I get the same 0 PPLNS shares so I'm thinking this must be a MPOS thing.

**Comment by TheSerapher** [comment]
MySQL 5.7?

**Comment by Bushstar** [comment]
Shame on me.
