### ISSUE TITLE
Pool bonus

### ISSUE THREAD

**Issue by Bushstar** [MPOS/php-mpos#2623]
You may have guessed that I'm in a spot of bother.

I'm going to have to remove the last weeks worth of bonuses, payouts have been suspended after a huge amount of coins disappeared, these coins were paid from a pool bonus.

Bonuses are shown in the transaction table, bonus, credit and donation. The payout script has been disabled for a week and no new transactions have been entered, so no bonus amount shows.

If I set pool_bonus to 0 and then run payout will the bonus field in the transactions table show as 0 or will it remember that this was set to a higher number?

I'm wondering if there is somewhere else that I have to edit the bonus or as there the payout script has not run it is enough to set pool_bonus to 0 then run the script.

**Comment by TheSerapher** [comment]
It reads the config, the config says 0 so no bonus is paid. No transactions are created for it either.

**Comment by Bushstar** [comment]
Excellent. Thanks for your patience over this and taking the time to respond to my many questions.

Do you have a donation address?

**Comment by TheSerapher** [comment]
It’s in the readme - they are both valid :-)

**Comment by Bushstar** [comment]
I sent a donation to the Bitcoin address yesterday.

**Comment by TheSerapher** [comment]
Thanks! Much appreciated :-)
