### ISSUE TITLE
[Feature Request] Ability to sort the workers grid by columns. or at least name.

### ISSUE THREAD

**Issue by gnewtzie** [MPOS/php-mpos#2625]
Would be handy to be able to sort them by the names.

**Comment by TheSerapher** [comment]
I am not even sure the Bootstrap table supports sorting by names since the name is an input field. I will leave this open though, maybe someone feels like trying this out (and verifies that submitting changes updates those rows as expected even when sorted).

**Comment by bziemek** [comment]
Given a template that initializes DataTables on the worker table (which is not the case by default), sorting the Worker Login column is just a matter of adding `data-sort="{$username.1}"` to the <td> in the template. In this way, sorting could easily be applied to the "Active" and "Monitor" columns as well.

DataTables is one of my least favorite plugins, but maybe I can take this on later.

**Comment by TheSerapher** [comment]
Nothing was done here so closing this.
