### ISSUE TITLE
Any chance the quick start guide could be updated?

### ISSUE THREAD

**Issue by tomvalois** [MPOS/php-mpos#2626]
I just tried following the instructions in the quick start guide (to the letter) on a clean install of 16.04. The very fourth line I am instructed to type in fails: libdb5.1-dev and libdb5.1++-dev have no installation candidates. I can continue by replacing them with the libdb5.3 versions, but I am not sure if that is sufficient. 

Also, the instructions for installing Litecoin do not work for the current version of Litecoin. I got it installed by following the instructions on the litecoin github, but I could not install it by following the MPOS quick start guide. 

I was hoping I could continue with the rest of the guide. However I soon hit an impasse. The line:

sudo python setup.py install

does not work when it is run in the ~/stratum-mining/externals/stratum directory. It returns an error that  twisted/plugins/__init.py__ is not found. As a result (I suspect, anyway), /usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/websocket_transport.py, which I am instructed to edit, does not exist. All of this results in errors when try to start stratum-mining. Is there any chance someone can figure this out  on a modern Ubuntu install, and post follow up instructions that actually work? If I get it working, I will post what I had to do differently from the guide.

**Comment by TheSerapher** [comment]
I’d rather delete the quick start guide and only reference MPOS itself rather than keeping it updated for changing third party software. They should have their own quick start guides to give an idea how to run them, which could be referenced in MPOS. Mich better than doing it here and not being able to keep up.
