### ISSUE TITLE
Compatibility with PHP 7?

### ISSUE THREAD

**Issue by sunk818** [MPOS/php-mpos#2628]
I read there are a lot of performance improvements with PHP 7. Has anyone run MPOS successfully on PHP 7?

https://haydenjames.io/clean-upgrade-to-php-7-centos-debian-ubuntu/

**Comment by TheSerapher** [comment]
Haven’t run it in PHP 7 myself but considering that the most performance impact is caused by database queries and much less by the code itself I would assume gains are minimal. Just an assumption though ;-)
