### ISSUE TITLE
Cash Out API

### ISSUE THREAD

**Issue by kuprel** [MPOS/php-mpos#2634]
Is it possible to cash out with an HTTP request/post if I am mining with an MPOS pool?  I don't see an API for it.  It looks like I need to call the createPayout function here somehow: https://github.com/MPOS/php-mpos/blob/master/include/classes/payout.class.php

This feature would be nice because I would like to route the pool payouts to different wallets algorithmically. I'm happy to figure out the code to write to call it.  My question is whether it is even possible if I'm not the pool operator.  Thanks.

**Comment by TheSerapher** [comment]
It’s certainly possible to add it but was left out by design. I decided not to add it since it exposes the coins of a user directly to the public without any two factor authentication or verification other than a token (which can easily be leaked on accident by sharing a url for example).

**Comment by tymiles003** [comment]
Team,
I'm new to the environment, and wanted to know how to setup a pool to mine the x11 algorithm? I'll like have it auto switching between multiple pool on the same server if possible.

**Comment by TheSerapher** [comment]
This isn't a support forum, please check proper support channels (Reddit, Bitcointalk) for help. Also do not hijack existing topics. 

Coin switching is not supported by MPOS and won't be added either.

**Comment by tymiles003** [comment]
No worries, my apologies...
Thanks

**Comment by ricardoaveloso** [comment]
This would really be useful. My use case is slightly different from Kuprel, though. I would like to cash out immediately once I mined a certain value in BTC, not in the mined coin, according to the current rate. The point is, sometimes the mined coin has a spike in value that, if not acted upon rather quickly, is lost. I have a script keeping track of the coin's value in my chosen exchange and it knows when it reaches the value in BTC that I want to cash out, but it cannot order a cashout from MPOS's API, only manually or waiting for the value in the mined coin to reach the preconfigured value... Also, note that it wouldn't really be that unsafe, given that you wouldn't be able to change the destination address, only order a cashout to the preconfigured address, which only the user can change.

**Comment by ricardoaveloso** [comment]
bump. is triggering a cash out to the user's preconfigured address a big enough security risk that this useful feature would not be implemented? any third party would not be able to take control of those funds...

**Comment by TheSerapher** [comment]
If anyone feels like tackling this go ahead. I am not working on MOOS anymore for years but left the ticket open just in case.

**Comment by TheSerapher** [comment]
See PR, decided to not do it because the security implications are too big after all.
