### ISSUE TITLE
Rechapcha upgrade!!!

### ISSUE THREAD

**Issue by pooladmin** [MPOS/php-mpos#2641]
i'm new on github sorry for errate section,
google say's  reCAPTCHA v1, which will be turned off on March 31, 2018!
it's time to upgrade to v2 or invisible?

**Comment by jimcouts** [comment]
I'd say, make a pull and merge request after doing that part. Because @TheSerapher is retired from OSS for now. :)

**Comment by TheSerapher** [comment]
What @jimcouts said :D

**Comment by AmazingDreams** [comment]
Has anyone started on this? Otherwise I'll go ahead.

**Comment by daygle** [comment]
@AmazingDreams I don't think anyone has started on this. I'm interested if you you end up developing this.

**Comment by AmazingDreams** [comment]
@daygle

**Comment by daygle** [comment]
Excellent, thanks heaps. I'll give it a try.

**Comment by TheSerapher** [comment]
Added to Development branch via 97b3cc3 by @AmazingDreams - thanks a lot!
