### ISSUE TITLE
Project info needs update

### ISSUE THREAD

**Issue by tamlin-mike** [MPOS/php-mpos#2643]
"A unified mining interface for various Scrypt and SHA256d Crypto-currencies!"

I suspect that info is a bit stale by now :-)

**Comment by TheSerapher** [comment]
Since it’s unmaintained that’s to be expected. What should it say instead?

**Comment by jimcouts** [comment]
Boo! @TheSerapher! What have you been up to lately? Would be good to know how life is treating you, thank you so much for making this possible through the years. :)

**Comment by TheSerapher** [comment]
Anything but software development ;-)

It was a hobby but it became more and more a job so I pulled the plug. It still being used in a lot of places shows there hasn’t been a suitable replacement for MPOS after all these years. There is still hope a new OSS project will take over someday!

**Comment by jimcouts** [comment]
I'm debating on porting this over to laravel later though, it's a good start for what could be in there. I've already set up the project on my own GitLab server. That way it'll give me something to do this mid-winter while everyone else is on their projects here. 

Glad to know you backed out, it takes a team to actually work on something like this for OSS. That or it'll drain you like no other. I learned this back in 2003 after releasing a project to the wild. Got sucked in, and never got out in time without being mentally drained from all of the insane support "You NEED to do this..." :( 

Anyways @TheSerapher hope all is well, but thank you for starting this project up and having it still online.

**Comment by TheSerapher** [comment]
That was exactly the reason why I pulled the plug. I was awake at night below my people and adding features instead of sleeping and being there for my wife and kids.

Priorities change in life and I realized it was time for a change.

**Comment by tamlin-mike** [comment]
@TheSerapher "Since it’s unmaintained that’s to be expected". Ah, didn't know that. The exchange between you and jimcouts made it clear why, and I think you made the right decision (speaking as someone who has seen the dark side of being "burnt out").

As for alternative wording, what about simply dropping the "Scrypt and SHA256d" part?

Whether accepted or rejected, this issue can be closed.
++luck;
