### ISSUE TITLE
There is no worker on a pool

### ISSUE THREAD

**Issue by heavensdoors** [MPOS/php-mpos#2647]
Hello
I installed mpos with ltc and i used stratum-mining and instructions.
So i installed everything and its working fine. I mean there is no error on the logs or something like that.
When i tried to run a mining from my rig its not giving any error message on minig rig side.
But when i login to the mpos UI with admin account i couldnt see any pool worker on the dashboard.
How can i fix this issue ?

Thanks a lot

**Comment by TheSerapher** [comment]
Probably a setup issue with stratum and the database backend. If no shares get inserted into the DB you will not see any work being done in MPOS. Debug where your shares are lost and MPOS will properly work.

**Comment by heavensdoors** [comment]
can you explain a little bit more in order to debug stratum ?
i couldnt see any data in shares table in my db.

**Comment by KevinBiomech** [comment]
Usually easier to just start over on stratum. It isn't part of MPOS. Try to
contact crypto-expert on Bitcoin talk. His version is the most widely used,
and he is good people.
