### ISSUE TITLE
no earnings!

### ISSUE THREAD

**Issue by OnlyPalmero** [MPOS/php-mpos#2650]
Hi, my mining hardware point to my new php-mpos instance with 100% work efficiency, but always i see 0.00000000 earnings although the time continue.... When crontab start, i can see the status list in transactions tab, appear all confirmed as 0.00000000 for "n/a" block. Whats happend? Why can't I get rewards? Thank'u

**Comment by TheSerapher** [comment]
There is no active support in this project anymore, if you need help try to find it in other community channels.

**Comment by OnlyPalmero** [comment]
Can you say some channel me? thank you

**Comment by TheSerapher** [comment]
I am not involved into Crypto Currencies anymore so the only ones I'd remember is Bitcointalk, Reddit.

**Comment by OnlyPalmero** [comment]
mmm, ok... very thank's and my congratulations for your work in this project.
