### ISSUE TITLE
Worker stats

### ISSUE THREAD

**Issue by tomasfil** [MPOS/php-mpos#2652]
Enchancement. 
Expand API to send stats for each worker. To be able site like https://miningpoolhubstats.com/ track stat for each miner.

**Comment by TheSerapher** [comment]
I am not sure what's needed here, the existing call `getuserworkers` already lists every single worker of the API Key account - extracting information from there isn't too hard. But should you really trust your API Key with a third party? Granted, MPOS is not allowing much with those keys (for good reason) but I wouldn't do that.
