### ISSUE TITLE
My Hashrate and Pool Hashrate Empty

### ISSUE THREAD

**Issue by virtualjj** [MPOS/php-mpos#2654]
Brand new setup and I'm probably missing something but I am not seeing the **My Hashrate** or **Pool Hashrate** dashboards populating with live hashrates.

I have one server running NOMP and MPOS and another client actively mining against the NOMP+MPOS server pool.

I setup two accounts in MPOS; one admin and one regular account.

The regular account as a worker configured and I am successfully mining (seems so anyway):

![image](https://user-images.githubusercontent.com/10323889/34760483-5ea7b26c-f623-11e7-953d-b30043291e84.png)

However, the dashboard isn't indicating any of the hashes:

From the Admin Dashboard

![image](https://user-images.githubusercontent.com/10323889/34760540-9bc1405a-f623-11e7-89f3-34fd3e8bc140.png)

From the regular account Dashboard

![image](https://user-images.githubusercontent.com/10323889/34760566-b2685e88-f623-11e7-9f69-bb98fcc041ba.png)

The **Current Block** and **Difficulty** sections are correct however

This is what I'm running:
[zone117x/node-open-mining-portal](https://github.com/zone117x/node-open-mining-portal)
Ubuntu 16.04.3 LTS
MPOS - 1.0.8 
Config - 1.0.1 
Database - 1.0.2

It's probably an easy fix but I've having trouble finding it.

**Comment by TheSerapher** [comment]
No active support anymore, try another portal like Bitcointalk or Reddit. In any case, no shares in the DB so no hash rate is displayed. Wrong setting for NOMP.
