### ISSUE TITLE
No registration of "https://lbry.suprnova.cc"

### ISSUE THREAD

**Issue by wangliangrong** [MPOS/php-mpos#2662]
No registration of "https://lbry.suprnova.cc"
I want to register here, the user and the mailbox are complete, PIN code itself set * * *, click the registration, there is a verification code error, need to be registered.
This URL registration process where the verification code, always can not see, please help me, there are a lot of people need to register.
EDIT: Removed private infos

**Comment by TheSerapher** [comment]
WOW. Posting your private information INCLUDING your mail address and password for a POOL on a PUBLIC resource is terrifying! You went to the wrong place, this is not a support forum for a specific pool but the creator of the software used by the pool.

Check with their support! I redacted your information but it was already sent to people subscribed to this repository so you may want to change your password everywhere if you used it somewhere else.

**Comment by wangliangrong** [comment]
I will thank you for a good friend to register and thank you for your help again.
