### ISSUE TITLE
shares_archive becoming massive, really fast

### ISSUE THREAD

**Issue by smiba** [MPOS/php-mpos#2664]
We're currently on a 5 minute per mined block avg. which means the shares_archive table is increasing in size in rapid speed. 

Since some queries depend on it, the mysqld will slowly start using more CPU the bigger the table gets. Especially the notification cron becomes hopelessly slow because it tries to fetch idle workers from the archive tab, taking more then 300 seconds per run while hogging one complete CPU core.

We're using a PROP payout system, what part does the shares_archive play in this system? I can't find much in the code about PROP payout distribution actively needing the shares of over 200 blocks ago.

Can I in this case safely lower this value to something like 6 hours? (60 * 6)

Thanks, sorry for bothering I know you retired from this project!

**Comment by TheSerapher** [comment]
I am not sure, but 200 blocks sounds very excessive. I checked the config:

https://github.com/MPOS/php-mpos/blob/master/include/config/global.inc.dist.php#L210-L211

and it states a backlog of 10 blocks and a maximum age of 1 day. Maybe your values are customized so it keeps growing that much? And you should be able to lower the values safely, backlog is used for estimates and statistics only.

**Comment by smiba** [comment]
When using a prop payout method the system only seems to use maxage and not maxrounds

Not sure if feature or bug? Sorry for reopening

**Comment by TheSerapher** [comment]
Probably on purpose to allow for a minimum amount of shares for statistics independent of block counts ... just set it much lower, value is in minutes.

**Comment by smiba** [comment]
Been running with 60*6 (360 minutes) for a week now and it's all been good. Was just wondering if there are any reasons not to do so 

Problem resolved
