### ISSUE TITLE
Some of my ZCash shows in autoexchange wallet although I have switched off atuoexchange for that cooin

### ISSUE THREAD

**Issue by e-stonia** [MPOS/php-mpos#2670]
Most of my ZCash not in auto-exchange of course but wondering why some is. When I compared my ZCL normal wallet amount to yesterday's amount then it's less so it means it's auto exchanging it.

**Comment by TheSerapher** [comment]
If there is no transaction there was no transfer. There is no known issue with auto transfers on MPOS - maybe it’s coin related?
