### ISSUE TITLE
Blocks missing if mined within a few seconds

### ISSUE THREAD

**Issue by hellomotow** [MPOS/php-mpos#2677]
As the cron currently only runs once per minute if we where to find 10 blocks within a 5 minute window only 5 would show. This obviously gets worse with coins that blocks are every x seconds. What can I change to detect this?

Cron is currently set to

* * * * * /var/www/MPOSBUNN/cronjobs/run-statistics.sh -d BUNN
* * * * * /var/www/MPOSBUNN/cronjobs/run-payout.sh -d BUNN
* * * * * /var/www/MPOSBUNN/cronjobs/run-maintenance.sh -d BUNN

**Comment by TheSerapher** [comment]
Modify crons or add helper scripts which will call them multiple times in a minute.
