### ISSUE TITLE
API: GetUserTransactions, Hardcoded to only return first page

### ISSUE THREAD

**Issue by jdonohoo** [MPOS/php-mpos#2679]
https://github.com/MPOS/php-mpos/blob/master/include/pages/api/getusertransactions.inc.php#L17

If you compare the account page to the api page you will see how the api hardcodes start =0 filter = NULL, so you can never fetch your transactions > page1.

**Comment by desaerun** [comment]
this should fix it once merged:
https://github.com/MPOS/php-mpos/pull/2681

**Comment by TheSerapher** [comment]
Just merged and noticed it was against master. Reverted that merge, so please create a new PR against development and we can close this issue =)

**Comment by TheSerapher** [comment]
Done in #2687
