### ISSUE TITLE
a question about pool fees

### ISSUE THREAD

**Issue by mabbas1975** [MPOS/php-mpos#2684]
i know it's not the right place for my question, but i am really confused, i am new to MPOS i am wondering
where i can add the address which used for fees transactions, as i see in web UI there are a transactions
marked as fees or donation but i am wondering how can i configure these two addresses, or the admin
address used for that purpose?

**Comment by TheSerapher** [comment]
Use the command line to send these coins to a wallet if your choice. No UI or automation for that.
