### ISSUE TITLE
bootstrap.php, non created class

### ISSUE THREAD

**Issue by christianreiss** [MPOS/php-mpos#2695]
Hey folks,

in bootstrap.php, line 35 you are trying to log things:

`$log->log("info", "Forcing session id regeneration, session failed to start [hijack attempt?]");`

but $log is not created until autloader.inc.php is required, which only happens in line 55. So you can never log and debug that case.

**Comment by TheSerapher** [comment]
Feel free to play with this line and see where the session could be initialised with login, but to be honest I'd think this error would show in PHP error logs already.

Have you had a use case for it?

**Comment by christianreiss** [comment]
Yes I have.

On a miss-configured node (php session directory did no exist) php was unable to create any php sessions, as such I went directly into that if() block. I was unable to proceed as the $log variable was null. not an Logger Object. 

After creating my phpsession directory everything went smoothly again; still: The sole reason for that catch if block is void if you try to log into an object thats, well, not an object. Either remove logging from there or instanciate a new Logger object beforehand if (! is_object($log) { $log = new Logger(....)

**Comment by TheSerapher** [comment]
Remove it is! :D
