### ISSUE TITLE
Problem pool with account worker

### ISSUE THREAD

**Issue by Federik1234** [MPOS/php-mpos#2697]
Hi please forgive my ignorance and my english first, I'm setting up a pool for a friend of mine then I state that I used a node to support the x16r (RVN) algorithm with mpos.
Everything works, the node connects and the cron jobs give no error, my problem is that to test the functioning and detection of workers I have tested undermining for one hour with my computer...but it did not give me any money and above all there is no blockage in the "blocks" page. I would like to understand if it's normal or if I'm wrong or if I still have to add something else.
Thank you in advance.......

p.s I am attaching some photos below to make you understand better

![earnings](https://user-images.githubusercontent.com/12891921/37372017-a2c183c8-2711-11e8-9b04-8e3ecc85dcdb.PNG)

![transactions](https://user-images.githubusercontent.com/12891921/37372053-c04c1a98-2711-11e8-9b56-067eb2d6bd48.PNG)

![block](https://user-images.githubusercontent.com/12891921/37372084-df757252-2711-11e8-9cf9-f2999dd7f32e.PNG)

Please guys help me, I have not slept anymore for 3 days to solve this problem

**Comment by TheSerapher** [comment]
You should first understand how mining works before putting your hands on creating a pool. This is a 24/7 job once it takes off and requires in depth knowledge of MPOS and mining in general to debug issues. 

If your shares are accepted and displayed in MPOS but no blocks are found this can be Ok depending on the coin difficulty. Try with a testnet first, that should give plenty of blocks to test. Wipe your wallet and MPOS before switching to a live coin.
