### ISSUE TITLE
coin daemon: RPC -getinfo deprecated in bitcoin 0.16

### ISSUE THREAD

**Issue by HashUnlimited** [MPOS/php-mpos#2699]
the RPC command was intermediately (bitcoin master 0.15.99) removed totally and now at the 0.16 release it's back responding with the DEPRECATED message and no information. 
This makes us believe we can't connect to the node....

**Comment by TheSerapher** [comment]
It’s been replaced with three new commands. The CLI still allows it with a parameter to gather the old information and then merge it into getinfo format.

If someone wants to address this here an idea to make it compatible with old versions:

* Run getinfo and check the output
* If OK, return data
* If invalid, run the new commands and merge data into old getinfo format

This will allow us to continue using it for all these other coins that have not upgraded to the new commands.

Other places affected could be the admin dashboard and wallet info page.

**Comment by lubuzzo** [comment]
As asked by @HashUnlimited, I updated the code and added compatibility with Bitcoin 0.16:

#2714

**Comment by TheSerapher** [comment]
Already merged into Development, I'll close this and happy testing guys.
