### ISSUE TITLE
MPOS PHP Warning failed to open stream: No such file or directory autoloader.inc.php

### ISSUE THREAD

**Issue by douglasdeodato** [MPOS/php-mpos#2707]
hey guys, I did follow the tutorial, but I got stuck running the MPOS in my localmachine, I am getting this error bellow, any ideas? thank you.

** [:error] [pid 9446] [client 127.0.0.1:35362] PHP Warning:  require_once(/var/www/html/MPOS/public/../include/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/MPOS/include/autoloader.inc.php on line 5**

**[:error] [pid 9446] [client 127.0.0.1:35362] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/MPOS/public/../include/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/MPOS/include/autoloader.inc.php on line 5**

tried use this command in my directory after search on google:

`composer install`
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 41 installs, 0 updates, 0 removals

                                                                      
```
  [RuntimeException]                                                  
  /var/www/html/MPOS/vendor does not exist and could not be created.  
```
                                                                      

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**EDIT**
**how I fixed:**

`chmod -R 777 /var/www`

in MPOS folder i did: `composer install`

**Comment by Widi92** [comment]
Had the same issue. Thanks ;)

**Comment by zimbo123** [comment]
I had this error after Update to the newest MPOS-Version. The older Version 1.0.8 works fine.

**Comment by TheSerapher** [comment]
Been a while, but off the top of my head:

```
php-mpos/templates/cache/
php-mpos/templates/compile/
php-mpos/logs/
```

And revert the file permissions you set earlier to something more sane.

**Comment by TheSerapher** [comment]
Sadly it's adding a step during upgrade that isn't documented but I think it's better than adding all libraries via a vendor folder into MPOS which makes all those files duplicates of upstream and static files. Hence keeping this open so people notice. Once upgrade and `composer install` is run, things should be fine.

**Comment by openbooknoobdeveloper** [comment]
I tried follow these steps with ubuntu 16 and I could not make the pool run at all

**Comment by zPools** [comment]
I updated the my pool on Ubuntu 16.04 like this:


- ``sudo git stash ``
- ``sudo git pull ``
- ``sudo chown -R www-data templates/compile ``
- ``sudo chown -R www-data templates/cache ``
- ``sudo chown -R www-data logs ``
- ``sudo apt install composer``
- ``sudo composer install``

I'm not sure if the ``chown`` was needed, but I went trough the installation guideline once again.

**Comment by HelloJasonZhang** [comment]
Thank you for you solution, it is works.
chmod -R 777 /var/www
# in MPOS folder i did: composer install
sudo composer.phar self-update

**Comment by TheSerapher** [comment]
And again, those permissions are dangerous.

**Comment by douglasdeodato** [comment]
@TheSerapher  do you have a better solution?

**Comment by TheSerapher** [comment]
It's outlined in this ticket regarding permissions. Only a few folders need them adjusted, see https://github.com/MPOS/php-mpos/issues/2707#issuecomment-384209060

**Comment by TheSerapher** [comment]
I have added a simple check during startup for this file and how to fix it. The Quick Start now includes the composer part as well. Hence closing this issue, won't be an issue going forward.
