### ISSUE TITLE
mobile access denied

### ISSUE THREAD

**Issue by tdsgit** [MPOS/php-mpos#2709]
On mobile browser 
https://max.thecoin.pw/index.php?page=api&action=getuserstatus&api_key=(my api key)&id=(id) gives Access denied. It however works on desktop browser. 
On poolwatch app too it says network error.
Do we need to add any more argument or pool op needs to enable for mobile.

**Comment by TheSerapher** [comment]
Ask the pool operator if they block mobile clients.
