### ISSUE TITLE
separated daemon

### ISSUE THREAD

**Issue by mabbas1975** [MPOS/php-mpos#2711]
Is it possible to let MPOS using a separated daemon other than the use used by NOMP or should i connect to the same daemon of NOMP

**Comment by TheSerapher** [comment]
You can, but it would still require proper rights to send coins from that wallet. You could also decide to point it at another wallet entirely which only holds a few coins to ensure transactions work, but at some point this may fail and you have to intervene and send new coins to that wallet to ensure transactions work.
