### ISSUE TITLE
User Transactions Filter Type in API

### ISSUE THREAD

**Issue by dan003400** [MPOS/php-mpos#2713]
Is it possible to filter the action=getusertransactions like you can do in the UI to "CREDIT" or "CREDIT_AE".

I have tried what the UI is doing:

`?filter[type]=Credit_AE`

But it is still returning all the transactions types.

Thanks in advance,

Dan

**Comment by TheSerapher** [comment]
It's not passed to the function - should be easy enough to add:

https://github.com/MPOS/php-mpos/blob/master/include/pages/api/getusertransactions.inc.php#L24

**Comment by dan003400** [comment]
Would be a great feature since its offered in the private api.

Thanks

**Comment by TheSerapher** [comment]
Implemented in above commit :)
