### ISSUE TITLE
Error when connecting my ASIC miner

### ISSUE THREAD

**Issue by sachinverma1** [MPOS/php-mpos#2715]
Hi,
I am running full node , and I have ASIC miner .. but when I try to connect my miner to my Wallet (full node)
It gives me error  CONNECTION SOCKET ERROR 127.0.0.1:4028 (FAILED).
I am running litecoin full node on VPS . I have static IP address And all required ports opened.

If anyone knows why I am getting this error please revert me back..

Best regards

**Comment by TheSerapher** [comment]
Not an MPOS issue.
