### ISSUE TITLE
Round progress a number larger than 100%

### ISSUE THREAD

**Issue by mabbas1975** [MPOS/php-mpos#2719]
Hello,
I am running MPOS in Litecoin with testnet=1 for testing purposes, the round progress gives me very
large number, around 678057% i am wondering what's wrong this number should be less than or equal 100%, when u checked the code i found it calculated from this part of code
// Round progress
  $iEstShares = $statistics->getEstimatedShares($dDifficulty);
  if ($iEstShares > 0 && $aRoundShares['valid'] > 0) {
    $dEstPercent = round(100 / $iEstShares * $aRoundShares['valid'], 2);
  } else {
    $dEstPercent = 0;
  }
in dashboard.inc.php

is that normal or i need to fine tune anything, i am actually confused with the round progress number, but i have noticed that it's always less than 0 in running pools with MPOS

**Comment by TheSerapher** [comment]
It's just an estimated based on block difficulty and number of shares found. Please keep in mind that for the latest Bitcoin RPC spec from Bitcoin 0.16 you may need to switch to the development branch or MPOS won't work properly/at all. This could result in no blocks being discovered by MPOS.

Please also check that your enabled your crons as described in the quick start guide or nothing will work and you rounds will just keep growing.
