### ISSUE TITLE
Increasing session timeout or disable auto logout

### ISSUE THREAD

**Issue by mabbas1975** [MPOS/php-mpos#2721]
Hello,

I want to increase the time of the session now it's a little small i want to increase it or even disable the auto
logout, i have checked the config files but i didn't found any directive for that, please help

**Comment by TheSerapher** [comment]
MPOS doesn't have much control over sessions since they are mostly handled by PHP. In general I'd recommend short sessions - there is money involved here so logging users out quickly isn't a bad thing.

**Comment by mabbas1975** [comment]
Thanks anyway for your response, for anyone wants to control the session time i have adjust it from php.ini
file by changing session.gc_maxlifetime = value in sec

**Comment by TheSerapher** [comment]
Quick search in the repo since I remember seeing it here: https://github.com/MPOS/php-mpos/wiki/Config-Setup#cookies
