### ISSUE TITLE
Sweep up coinbase rewards fees

### ISSUE THREAD

**Issue by mabbas1975** [MPOS/php-mpos#2723]
Hello,
i am working in a copy of MPOS that supports equihash coins, it's working now with Zencash, in this coin i couldn't spent the block reward till i transfer it to a zAddress and then transfer again to another tAddress in order to let MPOS doing payments, these transactions has a txfees, my issue is, i want to subtract these fees
from the rewards to avoid insufficient wallet credit, my idea is to subtract the fees from the block reward
before it inserted into the blocks db table, is that a right solution to solve this issue, please advice

**Comment by TheSerapher** [comment]
Transaction fees configured in MPOS are deducted at payout for each user with fixed values. The fee will show up as a transaction in the users ledger for transparency.

If you set the fee to 0 and deduct it by hand from the reward before transferring it into the wallet MPOS can access for payouts, you remove this transparency and blocks will show a lower value than users may expect. This is not want you want.

Apply the proper fee via config and let the system do it’s job.

**Comment by mabbas1975** [comment]
thanks very much for your advice
