### ISSUE TITLE
tx fees issue

### ISSUE THREAD

**Issue by mabbas1975** [MPOS/php-mpos#2725]
Hello,
i am try to configure MPOS with Bitcoingold, but i face an issue with tx fees in bitcoin gold the txfees increased after 50 coin so if the user has more than  50 coin the tx fees will be increased so i face insufficient credit, but if i could limit the amount of each transaction to be less than or equal 50 will solve this issue, so i set the $config['ap_threshold']['max'] = 50; but MPOS still send amounts larger than 50 in each transactions, please advice

**Comment by TheSerapher** [comment]
That's 50 coins per user max, It probably is a limit per sendmany transaction. There is no setting that would allow to limit that as well.
