### ISSUE TITLE
Undefined offsets in compiled theme files

### ISSUE THREAD

**Issue by r4sas** [MPOS/php-mpos#2726]
Every page opening PHP 5.6 writes in logs such message:
```
PHP Notice:  Undefined offset: 24 in templates/compile/bootstrap/<hash>.file.round_transactions.tpl.php on line 76
```

Offsets can be different.
Code on that line:
```php
<td><?php echo number_format($_smarty_tpl->tpl_vars['ROUNDSHARES']->value[$_smarty_tpl->tpl_vars['ROUNDTRANSACTIONS']->value[$_smarty_tpl->getVariable('smarty')->value['section']['txs']['index']]['uid']]['valid']);?>
```

Reference: https://github.com/MPOS/php-mpos/blob/master/templates/bootstrap/statistics/round/round_transactions.tpl#L23

**Comment by TheSerapher** [comment]
Looks like a typo in `$ROUNDTRANSACTIONS[txs].uid].valid`. Try `$ROUNDTRANSACTIONS[txs].[uid].valid` and see if it's gone?

**Comment by r4sas** [comment]
I dont think so:
```
<td>{$ROUNDSHARES[$ROUNDTRANSACTIONS[txs].uid].valid|number_format}</td>
                                     -1-
                 --------------2--------------
     ----------------------3------------------------
```
but will try.

**Comment by TheSerapher** [comment]
Then it's empty? Seems also strange, that means there are not valid shares? Maybe a broken miner?

**Comment by r4sas** [comment]
Maybe it got rounded to 0 shares  (< 1 full diff shares)?

**Comment by TheSerapher** [comment]
And for the rounding issue (very likely the case) there is another open issue. I'd think when that's fixed/adjusted this also should be fixed.
