### ISSUE TITLE
Round Shares and Round % not working....

### ISSUE THREAD

**Issue by TheCryptoServices** [MPOS/php-mpos#2731]
My Round Shares and Round transactions % are not showing up .
Also "statistics_shares" table in database is empty...

All the cronjobs are executing correctly and I cannot see any error in the statistics log file...

Any Idea what can be wrong?
Thanks

**Comment by cornac** [comment]
Change payout system to pplns or pps. There is no statistic on prop

**Comment by TheSerapher** [comment]
Do not use PPS unless you know what it does ...

Now round shares at all? Stratum isn’t working then since there should always be a share in the shares table.

**Comment by r4sas** [comment]
@cornac you're wrong. round stats are works on prop payout.

**Comment by r4sas** [comment]
@TheCryptoServices 
> All the cronjobs are executing correctly and I cannot see any error in the statistics log file...

Which cronjobs are you running? Can you say, how you configured them?

**Comment by TheSerapher** [comment]
It’s not a cronjob issue, either your miners are not working or stratum isn’t. It there are no shares in a round that means crons can’t do any work.

**Comment by TheCryptoServices** [comment]
@cornac 
That worked for me.
Changing to pplns seems to activate the cronjobs to add that statistic shares into the DB.
Working fine now.

**Comment by TheCryptoServices** [comment]
@TheSerapher 
The thing is stratum is working, and workers have shares.
All is working perfectly, but not Round Shares or Round Transactions info in the tables:

![round](https://user-images.githubusercontent.com/30536818/40220103-4a1805fe-5a78-11e8-838e-1d231b07816a.png)

**Comment by TheSerapher** [comment]
Are you running on Master or Development branch?

**Comment by TheCryptoServices** [comment]
Master!

**Comment by TheSerapher** [comment]
Coin in use? Did you check if it also happens with other coins?

**Comment by TheCryptoServices** [comment]
Yes, I’ve tried with several coins with same result....
Even with LTC,
Btw not a big deal ... system is working fine now with pplns
Just curiouse why it doesnt work on prop.

**Comment by TheSerapher** [comment]
Yeah that's weird, it should work. Those statistics should still be there in Prop, but I am not 100% sure :D

**Comment by TheCryptoServices** [comment]
It's ok :)
Thanks a lot for support.
Closing this issue !

**Comment by TheSerapher** [comment]
OK I tested this with my own setup ... running LTC Testnet and waited for a block than ran all the crons required (after patching my MySQL config as described in the FAQ): No issues.

```
mysql> select * from statistics_shares;
+----+------------+----------+-------+---------+-------------+---------------+
| id | account_id | block_id | valid | invalid | pplns_valid | pplns_invalid |
+----+------------+----------+-------+---------+-------------+---------------+
|  1 |          1 |        1 |  3552 |       0 |           0 |             0 |
+----+------------+----------+-------+---------+-------------+---------------+
```

<img width="1111" alt="screen shot 2018-05-23 at 22 30 25" src="https://user-images.githubusercontent.com/2376835/40449523-f472ac20-5ed8-11e8-9f45-036c7144da06.png">

Maybe you are not running a latest version or something? That screenshot also looks different compared to what I took (all text in Block Statistics is bold) but that may be browser related - haven't tested any others.

If you are fine with PPLNS use that, but the system behind the two is the same. So whatever it was, seems to be isolated to your setups.
