### ISSUE TITLE
MinerClaim.net Pool - Earnings seems to be reducing

### ISSUE THREAD

**Issue by Advocate-Sandeep-Prakash** [MPOS/php-mpos#2732]
Dears,

Firstly, I am not sure if this is the right place to raise and issue pertaining to xmg.minerclaim.net pool. I'm raising it here as is MPOS supports the pool and there is no exclusive email id to write into.

Since last 3 days, All Time - Credit under My Account > Earnings was not being updated. And today, I see that the value has decreased.
Kindly check the same.

Cheers

**Comment by TheSerapher** [comment]
Indeed the wrong place. We don’t support the pool, it just runs on this software. Any issues with a pool should be raised with a pool owner.
