### ISSUE TITLE
Any updates MPOS anytime soon?

### ISSUE THREAD

**Issue by ultra-pool** [MPOS/php-mpos#2734]
Has anyone updated any of the node module links? 

Iv got most of it already install. Also using NOMP. MPOS does boot up at BC of python errors. 

Does the MPOS DEV's plan on updating this at all?

Meanly to the Quick Start Guide.

**Comment by TheSerapher** [comment]
Node and python or not MPOS and MPOS has no “boot up” phase - the guide can be updated using PRs if I am not mistaken about how the wiki works.

**Comment by ultra-pool** [comment]
Any work arounds for php7? iv added php5 plugin fixes but it still does work MPOS.

**Comment by TheSerapher** [comment]
Works for me, wasn’t too hard using the error logs and figuring out missing packages. Maybe someone has a guide already?

**Comment by TheSerapher** [comment]
I checked the guide because I remember I added some PHP7 info there. Besides the packages not being named php5-* you need a few more so composer works. But after that it wasn’t a problem at all. Not sure where you are having issues, got it to work with those hints in the guide.

**Comment by ultra-pool** [comment]
Iv done alot of PHP work in the past and never ran into something like this. Im almost to the to pay someone to do a basic setup. 

Doesnt give me logs or anything. Do get a crap ton of warning and errors. But cant find any logs.
