### ISSUE TITLE
[-32601] getinfo This call was removed in version 0.16.0. Use the appropriate fields from: - getblockchaininfo

### ISSUE THREAD

**Issue by Widi92** [MPOS/php-mpos#2735]
I've tried to run "Globaltoken" (Sha256) on mpos but when I view the wallet info I'm getting this error:

"Unable to connect to wallet RPC service: RPC call did not return 200: HTTP error: 404 - JSON Response: [-32601] getinfo This call was removed in version 0.16.0. Use the appropriate fields from: - getblockchaininfo: blocks, difficulty, chain - getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings - getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion globaltoken-cli has the option -getinfo to collect and format these in the old format. "

I don't know how to fix it and I'm a little confused because i thought that this is already fixed with a previous mpos version.

Regards,
Widi92

**Comment by TheSerapher** [comment]
It should be fixed, did you try development? I ran on BTC without issues. Where does it happen and are you on the latest update?

**Comment by TheSerapher** [comment]
I am fairly sure that was already fixed. What does the admin dashboard say?

**Comment by Widi92** [comment]
http://prntscr.com/jkljpu

**Comment by Widi92** [comment]
Ok, so I'm currently facing the same problem with Digibyte Scrypt http://prntscr.com/jktvl4 other coins with the getwork api call are working perfectly fine.

**Comment by TheCryptoServices** [comment]
Same problem here....

**Comment by TheSerapher** [comment]
This is fixed in the `development` branch of MPOS. A merge to `master` isn't ready just yet but I will see if I can get it done in a few days.

**Comment by TheSerapher** [comment]
There you go: https://github.com/MPOS/php-mpos/pull/2738 - Still checking something which I can't tell when I am done, but this will fix the `getinfo` issues.

**Comment by TheSerapher** [comment]
Released MPOS 1.1.0 which includes the fix for 0.16 RPC servers.
