### ISSUE TITLE
Missing mining info in dashboard for mult-algo coins (Verge, Aurora, Digibyte, etc..)

### ISSUE THREAD

**Issue by TheCryptoServices** [MPOS/php-mpos#2737]
Dont know if it is related to the new wallets clients with some "getinfo" deprecated functions, but I cannot get mining info (network hash, next diff, etc..) into the dashboard.

Any solution?
Thanks

**Comment by TheSerapher** [comment]
It is and there is an open issue for that. Not sure why this isn’t working anymore but it should be fixable.
