### ISSUE TITLE
getting the right value for $target_bits

### ISSUE THREAD

**Issue by mabbas1975** [MPOS/php-mpos#2740]
i knowing it'e a repeated question, but there are known obvious answer, i am really don't know what's "target_bits" is, all what i know its important for calculation of hashrate, the point is there are no obvious something called target bits, maybe it has a different name but what is it, for example the target bits for
Litecoin (scrypt) is 16 so for the example of Litecoin, what's the characteristics of Litecoin has this value. kindly help, this really important when adding new coin

**Comment by TheSerapher** [comment]
Since it’s totally up to each and every coin you’ll have to check on the coin developers channels (Github, Forums, ...). That’s not in scope of the project, it just gives some tools to help.

**Comment by mabbas1975** [comment]
i am just want to know what is the keyword to use in search "target bits" returns nothing

**Comment by cornac** [comment]
Diff is part of block. 
Read https://en.bitcoin.it/wiki/Difficulty. 
And count bits in examples)
