### ISSUE TITLE
Admin wallet info shows blank page

### ISSUE THREAD

**Issue by Widi92** [MPOS/php-mpos#2741]
Hello there,
I'm about to setup a MPOS page for gulden (NLG) but when I try to view the admin wallet I'm getting a blank page. Everything else is working perfectly fine so far except the wallet page.
Apache2 error logs:
PHP Fatal error:  Uncaught Exception: RPC call did not return 200: HTTP error: 500 - JSON Response: [-11] Not a valid account UUID or label. in /var/www/gulden/include/lib/jsonRPCClient.php:120\nStack trace:\n#0 /var/www/gulden/include/pages/admin/wallet.inc.php(21): jsonRPCClient->__call('getaddressesbya...', Array)\n#1 /var/www/gulden/public/index.php(145): require_once('/var/www/gulden...')\n#2 {main}\n  thrown in /var/www/gulden/include/lib/jsonRPCClient.php on line 120

I hope anyone can help me out with this issue. Never had this before.

**Comment by milanojs** [comment]
Hello, @Widi92 when you are doing the json call there is a bad query and the elements, the error 500 its shown because there are issues in the query Cheers

**Comment by TheSerapher** [comment]
Probably something the coin handles differently than others when it comes to fetching coin balance. Ask the coin developers what needs to be adjusted for this specific coin to work.

**Comment by pmaccamp** [comment]
In case anyone else runs into this with Gulden it's because they changed the output of listaccounts from
``` 
{
    "" : 0.00000000
}
```

to
```
[
  {
    "UUID": "uuid",
    "label": "My account",
    "state": "Normal",
    "type": "Desktop",
    "HD_type": "HD",
    "HDindex": 12345
  }
]
```

If you change the code starting at line 13 in include/pages/admin/wallet.inc.php to this
```
$dBalance = $bitcoin->getrealbalance();

$dWalletAccounts = $bitcoin->listaccounts();
$dAddressCount = count($dWalletAccounts);

$dAccountAddresses = array();

foreach($dWalletAccounts as $walletAccountInfo)
{
  $key = $walletAccountInfo["UUID"];
  $dAccountAddresses[$key] = $bitcoin->getaddressesbyaccount((string)$key);
}
```

it will fix the 500 error on load.  Not sure yet if anything else is affected.
