### ISSUE TITLE
Customizable help section

### ISSUE THREAD

**Issue by HashUnlimited** [MPOS/php-mpos#2742]
The "Getting Started" section is a little bit dated. TBH I'm quite annoyed by admin mails dropping in all the time because the info there is just not useful/valid for what the pool is mining. 

A nice feature would be to be able to either choose from the default help (at least in terms of miner config) or create some pool-specific information from the admin page. Displaying the corrected info as MOTD is the common way to do it but newbies still rely on the help info.

**Comment by TheSerapher** [comment]
You can always copy a layout, rename it and us edit or just edit the template file which is mostly static anyway. That’s how pool operators usually do it so the feature is already there.

Templating files within MPOS has been removed for a while due to the large security impact.
