### ISSUE TITLE
Net Hashrate for XVG (and some other coins) not working.

### ISSUE THREAD

**Issue by TheCryptoServices** [MPOS/php-mpos#2749]
Hi! I know this was already asked here few weeks ago, but I'm using last mpos version and still cannot get the Net Hashrate working on some coins with "new" wallets with multi algo like Verge or Digibyte.

Is there any way to show NetHashrate ?
I see some pools using mpos where able to to that (for example mining-dutch https://www.mining-dutch.nl/pools/verge.php?page=dashboard).

Thanks for your help!

**Comment by TheSerapher** [comment]
If they changed their API, I would think pool ops simply adjusted MPOS to reflect that change and fetch the data from the proper place. You can run a test instance of MPOS (nothing live) and try fiddling here to get the proper data:

https://github.com/MPOS/php-mpos/blob/master/include/classes/bitcoinwrapper.class.php#L98-L125
