### ISSUE TITLE
Setting difficulty for the Stratum against Digibyte pool

### ISSUE THREAD

**Issue by imrecsoka** [MPOS/php-mpos#2750]
Hello, i have tried ccminer and sgminer with -u username.worker -p sd=3 or -p d=3 it does not work, it keeps defaulting to 8.

The help page on the Digibyte pool page says use sd=xxx

I mean i dont get this it is not working,. why is this roket science.

**Comment by r4sas** [comment]
Not MPOS issue. Write directly to your pool administrator.

**Comment by TheSerapher** [comment]
@r4sas got my back ;-) And he‘s right. Closing.
