### ISSUE TITLE
[SSO] login/PIN issues

### ISSUE THREAD

**Issue by HashUnlimited** [MPOS/php-mpos#2752]
I might be too stupid for getting that properly - so sorry if this turns into a support issue.

Now that I have consolidated the databases into one single host, I'm trying to get SSO logon working, so far without any success. Currently playing with development branch. 

$config['db']['shared']['accounts'] = 'shared';
$config['db']['shared']['workers'] = 'shared';
$config['db']['shared']['news'] = 'shared';

in all configs. All of the databases are accessed with the same user and pass. 

Cookie settings:

$config['cookie']['duration'] = '1440';
$config['cookie']['domain'] = '.pool.hashunlimited.com';
$config['cookie']['path'] = '/';
$config['cookie']['httponly'] = true;
$config['cookie']['secure'] = true;

because we want to access https://ltc.pool.hashunlimited.com, https://dash.pool.hashunlimited.com,...

So when I'm resetting the password on one instance, it will refuse the login on the next one. BUT I can reset the counter from there and it will instantly log in. Logging out will result in not being able to log back in. Browser cache cleaned before trying to log in. 

I'm really not good at this web stuff...

**Comment by TheSerapher** [comment]
Strings should be in format of `database.table` not just the database. Then it should work.

**Comment by HashUnlimited** [comment]
Thanks for the answer, like that it wasn't working at all, obviously it couldn't find the user (mysql 5.7?)

Instead, I had to set SALT and SALTY equally in all databases (somehow logical in the aftermath)

**Comment by HashUnlimited** [comment]
another note here for update of the documentation (will get to that later):

$config['db']['shared']['workers'] may not be used since the stratum is supposed to update the diff in the specific db instance so there aren't any shared workers

**Comment by TheSerapher** [comment]
Feel free to update the Wiki! Shared workers indeed doesn’t work well with quite a few stratum implementations.
