### ISSUE TITLE
Проблема с адресом кошелька

### ISSUE THREAD

**Issue by Permyak178** [MPOS/php-mpos#2754]
Добрейшего времени суток, возникла проблема с выводом XMR, пишет адрес уже используется, подскажите как решит данную проблему, заранее +500 к карме...

**Comment by TheSerapher** [comment]
Please try to use English, but address in use just means that it's already in use somewhere else.

**Comment by Permyak178** [comment]
Из за этой проблемы я не могу монеты вывести,и кто может использовать мой кошелек

**Comment by cornac** [comment]
It’s issue of monero daemon not mpos. Attach demons logs.  
Это проблема демона монеро, а не MPOS. Приложи логи демона.

**Comment by TheSerapher** [comment]
Then ask there - wrong place to get help for a coin daemon.
