### ISSUE TITLE
pps no payments

### ISSUE THREAD

**Issue by pool-dataekb** [MPOS/php-mpos#2755]
Good afternoon. Help me to understand.
I set up a new pool of mpos + nomp. the main one chose the pps. started everything works but there are no payments. what am I doing wrong?

![pps_payout](https://user-images.githubusercontent.com/41615806/43126281-b31f02bc-8f45-11e8-8da5-018fc3e192e5.jpg)

**Comment by TheSerapher** [comment]
Please disable PPS if you are not aware what it does and re-create your pool. You pre-pay users for their shares even though no blocks are generated. You pay out of pocket until a block is found.

You can't pay out because there are no coins in the pool yet.

**Comment by pool-dataekb** [comment]
OK. is there a minimum amount that should be on the pool? if Yes how many?

**Comment by TheSerapher** [comment]
No, as much as you need to pay out users. If it gets low, add more.
