### ISSUE TITLE
[database] too many connections

### ISSUE THREAD

**Issue by HashUnlimited** [MPOS/php-mpos#2756]
After about one month running test branch in production, SQL started to refuse new connections. Maybe we don't drop expired ones somewhere?
There are two instances of MPOS running on that server, similar entries in the Apache log for both:

```
[Sun Aug 12 00:59:58.266883 2018] [:error] [pid 2424] [client 87.238.27.178:57284] PHP Warning:  mysqli::__construct(): (08004/1040): Too many connections in /var/www/MPOS_CHC/include/classes/mysqlims.class.php on line 26, referer: https://chc.pool.hashunlimited.com/index.php?page=dashboard
[Sun Aug 12 00:59:58.266921 2018] [:error] [pid 2424] [client 87.238.27.178:57284] PHP Fatal error:  Uncaught Exception: Failed to connect to MySQL: (1040) Too many connections in /var/www/MPOS_CHC/include/classes/mysqlims.class.php:48\nStack trace:\n#0 /var/www/MPOS_CHC/include/database.inc.php(6): mysqlims->__construct(Array, Array, true)\n#1 /var/www/MPOS_CHC/include/autoloader.inc.php(19): require_once('/var/www/MPOS_C...')\n#2 /var/www/MPOS_CHC/include/bootstrap.php(54): require_once('/var/www/MPOS_C...')\n#3 /var/www/MPOS_CHC/public/index.php(40): include_once('/var/www/MPOS_C...')\n#4 {main}\n  thrown in /var/www/MPOS_CHC/include/classes/mysqlims.class.php on line 48, referer: https://chc.pool.hashunlimited.com/index.php?page=dashboard
```

**Comment by TheSerapher** [comment]
Increase connection limit on the MySQL sever, not an MPOS issue.1

**Comment by HashUnlimited** [comment]
any advice to do some deeper troubleshooting? Thought about increasing limits as well but decided to report because those pools are VERY small (no more than 20 workers each) and we were running much larger ones before without ever running into that limit.

**Comment by TheSerapher** [comment]
Use MySQL tools and commands maybe create different users for each software and pool so you can figure out what initiated the connection by username.
