### ISSUE TITLE
Inconsistent values for pool hashrate 

### ISSUE THREAD

**Issue by lpellis** [MPOS/php-mpos#2759]
I'm trying to track the pool / network hashrate, but I'm getting differnet values depending on the api method used.
For example
https://zcl-api.suprnova.cc/index.php?page=api&action=public&api_key=969b5810b979407b41a1d9e673f57a65273fb0c6b62b47d21319c389368a6f9
`"hashrate":"6216637902.9941", "network_hashrate":49378025000000`
https://zcl-api.suprnova.cc/index.php?
while
page=api&action=getdashboarddata&api_key=969b5810b979407b41a1d9e673f57a65273fb0c6b62b47d21319c389368a6f91
raw:
`"hashrate":"6216637902.9941","network":{"hashrate":49378025000,"` << different from above
pool:
`"pool: :6216637.9029941, "network": 49378025`

Looking through the code it appears that the getdashboarddata['pool'] values are used in the actual dashboard, and if I knew the units they seem correct.  I just cant seem to find a reliable way to pull these data.
It seems to be doable though as sites like whattomine are tracking the data ( https://whattomine.com/coins/167-zcl-equihash ), my question is how do they manage to get the right info?

Thanks for any help.

**Comment by lpellis** [comment]
Same thing with X11 though for example.
https://dash.suprnova.cc/index.php?page=api&action=public&api_key=969b5810b979407b41a1d9e673f57a65273fb0c6b62b47d21319c389368a6f9

It returns the hashrate as `12720286610.321`, which is 12.7 Gh/s.  The real value though is 12.7 Th/s (which I can see when I look at the dashboard)

Somehow wtm is pulling the correct info though ( https://whattomine.com/coins/34-dash-x11 ), I'm confused how they manage that?

**Comment by TheSerapher** [comment]
If I am not mistaken it’s an RPC call getnetworkhashps and maybe it’s just off by a unit?  MPOS expects h/s (I think) but maybe they return kh/s. So it’s just a mater of displaying it differently.

**Comment by lpellis** [comment]
Its not consistent though.  suprnova might return the values in MH/s, while miningpoolhub (for the same coin/algorithm) returns KH/s
The only way I can see is to hardcode the factor for every coin on every pool, but that does not feel right.  Can you think of any way to figure out the value from the api?

Thanks for the help btw.

**Comment by TheSerapher** [comment]
No there is no indicator from the API telling you what unit it sends it in :-/ Wasn’t there a MPOS setting to chose the formatting? I don’t remember ...

**Comment by r4sas** [comment]
Admin Panel -> Settings -> Statistics
![image](https://user-images.githubusercontent.com/7023612/45865529-7de18880-bd86-11e8-995d-6eeffe554c19.png)

**Comment by lpellis** [comment]
Those are not exposed in the api though?  
I know the 'pool' values from the getdashboarddata will change if you update those settings, but will the 'raw' stay the same?  If it does then I guess the best way is to calculate the factor for the 'raw' values once (using the settings you posted above)

**Comment by r4sas** [comment]
Just check that.
Can you provide what really returns your wallet and pool at same time about network hashrate?

**Comment by TheSerapher** [comment]
Probably not an MPOS issue but setup problem of that specific pool.

**Comment by cornac** [comment]
for digibyte i change in bitcoinwrapper some strings
  public function getdifficulty() {
    $this->oDebug->append("STA " . __METHOD__, 4);
    if ($data = $this->memcache->get(__FUNCTION__)) return $data;
    $data = parent::getmininginfo();
    // Check for PoS/PoW coins
    if (is_array($data) && array_key_exists('difficulty', $data))
      $data = $data['difficulty'];
    return $this->memcache->setCache(__FUNCTION__, $data, 30);

 public function getnetworkhashps() {
    $this->oDebug->append("STA " . __METHOD__, 4);
    $dff=$this->getdifficulty();
    $dNetworkHashrate = $dff * pow(2, 32) /$this->config['cointarget'] ;
        return $this->memcache->setCache(__FUNCTION__, $dNetworkHashrate);
  }

**Comment by TheSerapher** [comment]
Sounds like a very coin specific issue. Thanks for posting the solutions for others to use! I don’t know if there is a generic way to add this so MPOS can auto detect to use it. Maybe with a coin class detection? Keeping this closed since you posted a solution.
