### ISSUE TITLE
[Idea] Implement better way to work with pool fee and donations

### ISSUE THREAD

**Issue by r4sas** [MPOS/php-mpos#2760]
Currently I cannot understand something about accumulating pool fee and donations.
As I know, overall accumulated pool fee now is only a digit in Admin Panel -> Funds -> Transactions. Same for donations.

Main idea is provide separated page in AP where you can set/save custom Address with ability to payout collected coins in manual/automatic mode.

Or here another way to use values only for showing about fee, but fee itself will be withdrawn by stratum software (NOMP have it, for example). For donations anyway needed page with that function.

**Comment by TheSerapher** [comment]
Donations and fees are simply not available for payouts and remain in the wallet. You can either accumulate these for bonus payouts to miners or do a call by hand to pay them out to an address of your choosing.

There are no plans to add an automatic option into moos.
