### ISSUE TITLE
wallet handling due to moving standards

### ISSUE THREAD

**Issue by HashUnlimited** [MPOS/php-mpos#2761]
The last two updates on the Bitcoin client came with significant changes in terms of the integrated wallet.

First of all, of course, most catching to the eye, there's the support for multiple wallets (been there for a while) and the innovation is on-the-fly wallet change. Well, this shouldn't concern us here, just a notice.

It becomes interesting when we are looking at the account handling. This one got deprecated and accounts are replaced by labels now. At the first step of depreciation - done in bitcoin 0.16 - they were somehow working in parallel and the user only experienced the name change. In the background though, things have already been changing, that time one noticed in MPOS already, that on the Admin panel the newly introduced labels have been showing up as accounts but transactions have been missing on the admin panel. 
Nowadays the logic has changed in another step, instead of binding an address to an account, a label is bound to an address now. Sounds trivial but that's basically elevating the whole level of MPOS's payment processor to wallet level rather than account level. Tbh I am not aware if and which deprecated RPC calls are currently being used by the processor, however, the whole visualisation is worth being adapted. 

Another interesting feature recently introduced is the rework of CoinControl. Those improvements we could possibly use to work for us in the background in conjunction with the changes described above. As node owner now can opt to chose coins to send grouped by address instead of total amount, I can see some privacy improvement there for the convenience of the pool owner as well as the miner.  This change is only concerning entities who re-use addresses like miners, exchanges and some conservative merchants.

As usual, this is not (yet) a bug report but a try to catch future issues early. It's a call to contributors out there, if you like to work on, I am always happy to assist in any way as a client guy, from Bitcoin to Shitcoin ;-)

**Comment by TheSerapher** [comment]
Nice find, but unless someone finds the time to adjust MPOS to support both new and all account systems, I don't know if we'll see it in the core here too :-/

**Comment by HashUnlimited** [comment]
It's a call for example to @lubuzzo as a very talented newcomer with deep understanding how things are working out ;-)

**Comment by lubuzzo** [comment]
I have a complicated test at college tonight, so I still didn't take a look on that. But I'll take a look this week, and see what I can do.

**Comment by HashUnlimited** [comment]
Here's an example of what we get on the latest Bitcoin code

```
[Thu Oct 04 09:53:05.075170 2018] [:error] [pid 7884] [client 89.144.203.13:9981] PHP Fatal error:  Uncaught Exception: RPC call did not return 200: HTTP error: 404 - JSON Response: [-32601] Method not found in /var/www/MPOS_OZC/include/lib/jsonRPCClient.php:120\nStack trace:\n#0 /var/www/MPOS_OZC/include/classes/bitcoinwrapper.class.php(58): jsonRPCClient->__call('listaccounts', Array)\n#1 /var/www/MPOS_OZC/include/pages/admin/wallet.inc.php(13): BitcoinWrapper->getrealbalance()\n#2 /var/www/MPOS_OZC/public/index.php(145): require_once('/var/www/MPOS_O...')\n#3 {main}\n  thrown in /var/www/MPOS_OZC/include/lib/jsonRPCClient.php on line 120, referer: https://ozc.pool.hashunlimited.com/index.php?page=dashboard
```

until now we were still able to use `deprecatedrpc=accounts` in the coin config but that's history....

**Comment by HashUnlimited** [comment]
Basically I am missing an idea what advantage the support of accounts could possibly have in MPOS, could that be entirely dropped?

While switching to labels would be a nice feature, the swap might not be straight forward as the output format has changed:
`getaddressesbyaccount`
```
  "CN872jALfKPxs2j4Amc2jALfKPxsCoJSfi1n2",
  "CQAmc2jALfKPxsG3UcAmc2jstXFFHcPfcH",
  "2fRRtu1yRnJPnY3vYarTf9VfQ9PPvogcm4",
  "2sBBaZAmc2jALfKPxs62jALfKPxsfQAzuddZ7",
  "chc1q8cfn447wt97myjmt3jgjayyg0drv27v639u8n4",
  "chc1q23f2jALfKPxs3xuhdx3sAmc2jALfKPxsc324as"
```

`getaddressesbylabel `
```
  "CN872jALfKPxs2j4Amc2jALfKPxsCoJSfi1n2": {
    "purpose": "receive"
  }
```

**Comment by chrysophylax69** [comment]
So what would be the 'beneficial' way of doing this?

Coding it to support both the old and new ways of daemon RPC access? How difficult would that be to do for a PHP coder? We would be happy to discuss and fix if we can with them.

In the BTC and new OZC daemons, there is literally NO access to the RPC at all via MPOS now. It can't actually 'see' the daemon at all.

#crysx

**Comment by TheSerapher** [comment]
It should be fairly easy to integrate for a good coder with knowledge about talking JSON RPC to a service. As mentioned the old accounts list should either return an error or not any satay, which would cause it to run the label call instead and parse the data differently. A wrapper function doing this automatically would be sufficient (probably in the bitcoin wrapper class).

**Comment by HashUnlimited** [comment]
I thinks it goes a bit deeper as we are not only looking at a change in the data structure but also at some basic MPOS functionality which needs to be adapted (and idk how flexible we are there).

Apart from structure change of labels and sendmany, we need to see how the payment processor is validating the balances. MPOS will always attempt to pay from the "default" account. Now applying the label structure onto that one isn't an issue but keep in mind that the change will always be on a new address unless explicitly defined in the `sendto`. So they are not going to be credited towards the balance unless we consider the wallet as "account".

**Comment by TheSerapher** [comment]
Maybe it makes sense to trace what needs to be adjusted and leave it in the ticket as a hint to people trying to implement this. Maybe at some point we get a proper PR out of this.

**Comment by lubuzzo** [comment]
@TheSerapher I made a PR, #2776.

I believe I fixed the problem with the compatibility with the latest Bitcoin's change.

When you have some time, take a look.

**Comment by HashUnlimited** [comment]
Closing here to tidy up, further discussion belongs to the referenced PR.
