### ISSUE TITLE
Merged mining

### ISSUE THREAD

**Issue by TheMike-V** [MPOS/php-mpos#2762]
I couldn't find any information in the FAQ about it. Is your Litecoin pool also merge mining Viacoin?

**Comment by TheSerapher** [comment]
Merged mining is not implemented in MPOS, at least when it would come to payouts. No experience with it at all so cant comment if it would work.

**Comment by TheSerapher** [comment]
You may want to ask the pool operator? Looks like a pool related question and you are mistaken this tracker for the pool contact?
