### ISSUE TITLE
- INFO --> Starting Payout...   no payout

### ISSUE THREAD

**Issue by shfamily** [MPOS/php-mpos#2765]
Good day 
we send some payments before and we got the error E0078: RPC method did not return 200

after that we modify the coin decimal 8 to 7 for LCC and the cronjob payouts Run OK apparently
and after we run scripts/validate_payouts.php we got the next 

| 71 | juancho637 | CTU2ABxtSQBwTHKVXj5LCSqoFPbMCQJ7zf | 40.13919973007882191 | MISSING | n/a |

ALL CRONJOBS RUN OK

![captura de pantalla 2018-10-13 a la s 7 54 24 p m](https://user-images.githubusercontent.com/43366410/46911451-e94fed80-cf21-11e8-901f-ab1b7bdcd334.png)
![photo_2018-10-13_19-56-56](https://user-images.githubusercontent.com/43366410/46911470-6d09da00-cf22-11e8-94b4-4170af3e58e9.jpg)

The Coin is Litecoincash LCC

we don't  know why the system didn't sent the payments and still said - INFO --> Starting Payout... and never sent the coins

- INFO --> Starting Payout...
- INFO --> Starting Payout...
- INFO --> Starting Payout...
- INFO --> Starting Payout...

any person know what can we do?

**Comment by shfamily** [comment]
After about 3 hours trying payout again, the pool show the cronjobs payout error
And E0078: RPC method did not return 200

**Comment by r4sas** [comment]
I think first and commor reason - too much digits after dot. Does your coin wallet **really** support more than 8 digits after dot?

**Comment by shfamily** [comment]
@r4sas LCC just suppor 7 decimals

**Comment by shfamily** [comment]
@r4sas and yes we check the transactions and some are automatics and others manual

How can I do to the payout just sent the payment with 7 digits decimals?

**Comment by r4sas** [comment]
Please show your coin config from `/include/classes/coins` directory.

**Comment by r4sas** [comment]
Prove of root of issue:
https://github.com/litecoincash-project/litecoincash/blob/1483a2ed5088f6f07264c1d0b6483bb5df1cf1ab/src/bitcoin-tx.cpp#L533-L534

**Comment by TheSerapher** [comment]
Not really into crypto’s much anymore but have you looked up the payout that was supposed to process and check the amount? I’d think it’s a simple transaction that’s too big for your coin and fails.

**Comment by shfamily** [comment]
@TheSerapher

Our pool got the next payouts request on scripts/validate_payouts.php

#!/usr/bin/php | TX-DB-ID | Username | Address | Amount | Status | TX-RPC-ID | | 35 | juancho637 | CTU2ABxtSQBwTHKVXj5LCSqoFPbMCQJ7zf | 174.2465403172927835 | MISSING | n/a | | 33 | shfamily | CdRTqFRcbExVDogy22VZ1DyAJBk8ByJnLh | 1218.019536032903033 | MISSING | n/a | | 91 | jonathangr30 | CZBKA5ixrJKiwdwWjdJAeFYq3m5mWfK2nN | 384.1269255911046229 | MISSING | n/a | | 89 | shfamily | CdRTqFRcbExVDogy22VZ1DyAJBk8ByJnLh | 769.7874043349619341 | MISSING | n/a | | 76 | shfamily | CdRTqFRcbExVDogy22VZ1DyAJBk8ByJnLh | 166.7517969284216690 | MISSING | n/a | | 71 | juancho637 | CTU2ABxtSQBwTHKVXj5LCSqoFPbMCQJ7zf | 40.13919973007882191 | MISSING | n/a | | 69 | jonathangr30 | CZBKA5ixrJKiwdwWjdJAeFYq3m5mWfK2nN | 307.4348992938726041 | MISSING | n/a | | 67 | shfamily | CdRTqFRcbExVDogy22VZ1DyAJBk8ByJnLh | 469.2410384154797498 | MISSING | n/a | | 62 | juancho637 | CTU2ABxtSQBwTHKVXj5LCSqoFPbMCQJ7zf | 20.99146453878844909 | MISSING | n/a | | 60 | shfamily | CdRTqFRcbExVDogy22VZ1DyAJBk8ByJnLh | 321.0608957485465566 | MISSING | n/a | | 55 | juancho637 | CTU2ABxtSQBwTHKVXj5LCSqoFPbMCQJ7zf | 18.86336525108541195 | MISSING | n/a | | 53 | jonathangr30 | CZBKA5ixrJKiwdwWjdJAeFYq3m5mWfK2nN | 658.8151897123875642 | MISSING | n/a | Please be aware that transaction prior to a transaction fee change may be marked as MISSING. See help on how to apply a custom transaction fee that can also be checked against. You can also enable verbose mode. Summary DB Debit Transaction Limit: 1000 RPC Transaction Limit: 10000 Custom TX Fee Checked: 0.1 Total Send TX Records: 0 Total Debit Records: 12 Total Records Found: 0


Some are lower 
20.99
18
40.1


How can I cancel all request payouts and run that’s again?

**Comment by TheSerapher** [comment]
You can’t cancel payouts, once the script runs its paid to the user.

No idea what’s the issue, maybe turn debug logging on in your coin daemon and see if the failed transaction shows up? Other than that it seems to be an issue with the RPC or an invalid or unimplemented call. Can’t say, too many coins out there ;-)

**Comment by r4sas** [comment]
@shfamily 
>is it ok?

No. You must somehow limit digits  after dot in MPOS.
And asking again: please show your coin class.

**Comment by shfamily** [comment]
@r4sas

I don’t understand your question
Where can I get the coin class information?
We checked information about how to reduce the digits after dot but we didn’t get any information

**Comment by r4sas** [comment]
@shfamily what you have here in your config?
https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/include/config/global.inc.dist.php#L33-L38

**Comment by shfamily** [comment]
@r4sas Said sha256d

**Comment by shfamily** [comment]
@r4sas 
![image](https://user-images.githubusercontent.com/43366410/46924378-bb35e080-cfe9-11e8-9032-186ab1600654.png)

**Comment by r4sas** [comment]
sha256d coin class has in it settings precision set to 20, what is not correct for you coin settings.

https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/include/classes/coins/coin_sha256d.class.php#L11

Please make copy of `include/classes/coins/coin_sha256d.class.php` to new file and change precision.

For example:
`cp include/classes/coins/coin_sha256d.class.php include/classes/coins/coin_lcc.class.php`

In coin_lcc.class.php change that value to 8
https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/include/classes/coins/coin_sha256d.class.php#L11

Change coin algo name to lcc
https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/include/config/global.inc.dist.php#L38

**Comment by shfamily** [comment]
@r4sas do you have telegram? Lcc

**Comment by r4sas** [comment]
@shfamily yes.

**Comment by shfamily** [comment]
@r4sas can you give me that to write to you directly?

**Comment by r4sas** [comment]
@shfamily join https://t.me/php_mpos

**Comment by r4sas** [comment]
@TheSerapher how you think about adding link to telegram for discussion and help purposes?

https://t.me/php_mpos

**Comment by TheSerapher** [comment]
Will do but it's a channel that has to be watched by the community :)
