### ISSUE TITLE
Email showing IP address.

### ISSUE THREAD

**Issue by bcmonster** [MPOS/php-mpos#2766]
The link is showing the IP address for registration or to unlock account but with all the port forwarding i am doing that does not work.   I have looked but can’t where to fix.  Any ideas?

**Comment by r4sas** [comment]
Please show example, because I cant understand about which IP you said: server or client.

**Comment by bcmonster** [comment]
You have created a new account. In order to complete the registration process please follow this link:

http://71.87.195.53/index.php?page=account&action=confirm&token=cced7b828a3db1f979f4df492c6d3b80dfb71147d146072e05295851a29ba7a7

Cheers,

lcc.bcmonster.com

**Comment by r4sas** [comment]
@bcmonster https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/include/config/global.inc.dist.php#L107

**Comment by bcmonster** [comment]
> @bcmonster
> 
> [php-mpos/include/config/global.inc.dist.php](https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/include/config/global.inc.dist.php#L107)
> 
> Line 107 in [236cccd](/MPOS/php-mpos/commit/236cccd5d3178e99504bf2665db8bddfed6aa176)
>  $config['gettingstarted']['stratumurl'] = '';

Thats the stratum address for the default getting started page....  I dont think that is what is pulls the web address from on the email template.

**Comment by r4sas** [comment]
According to Smarty documentation, `$smarty.server.SERVER_NAME` returns `$_SERVER['SERVER_NAME']`
Docs: https://www.smarty.net/docsv2/en/language.variables.smarty.tpl

https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/templates/mail/register/confirm_email.tpl#L5

So you need check your web server configuration.

**Comment by TheSerapher** [comment]
Yes, your Apache isn't properly configured to set a useable Server Name - which defaults to the IP address of the host.
