### ISSUE TITLE
E0081 Failed to insert new block into database

### ISSUE THREAD

**Issue by thespice** [MPOS/php-mpos#2768]
Hi,

I'm getting an E0081 error which is reporting that sql is failing as while trying to add a duplicate entry to the database.

`SQL Query failed: Duplicate entry '777507 - <hash>'  for key 'height'`

I've gone in to the db and deleted that block, run the findblocks cron, that block gets re-added to the db and then I get the duplicate error warning again.

Is this a blockchain issue or does findblocks have a cache somewhere that is storing this block height twice?

Any ideas how to fix this please?

**Comment by thespice** [comment]
If it helps to diagnose the issue, in the db entry for this block the `account_id`, `shares` and `shares_id` are all `NULL` and the `worker_name` is `undefined`.

This isn't right for sure, all mining is account based so somethings gone wrong here.

Is there anywhere else that I can delete this  particular record so that when I run findblocks it won't try to add this row again?

**Comment by cornac** [comment]
What version of MySQL?

**Comment by thespice** [comment]
Okay will try that. 

Also getting a ton of E0062 - Block has no share_id, not running payouts, error emails now too.

**Comment by thespice** [comment]
It was only that one block, changed it to 1 and re-ran` findblocks.php -f`

Same problem, still saying that this block is a duplicate?

**Comment by TheSerapher** [comment]
https://github.com/MPOS/php-mpos/wiki/Error-Codes#e0081-failed-to-insert-new-block-into-database

**Comment by thespice** [comment]
@TheSerapher Hey Sebastian, checked the BC and no, there are no duplicate blocks. Is the ref to this block being stored somewhere else in the db? Can I remove it completely?

**Comment by TheSerapher** [comment]
Been a while since I dealt with this so take this with a grain of salt. MPOS just scans your transactions for block creations, in that list seems to be that block twice in different transactions. Since the scan happens every time, it will keep re-adding this block. I am not sure what the best way to tackle this would be without breaking the pool to be honest. Maybe you can check your transactions again, find that duplicate block and set that as the only DB record and mark it is paid out (since shares are probably not available anymore). It should start finding new blocks past that one then and pick up from where it left before finding the duplicate.

**Comment by thespice** [comment]
Thanks for the reply. Will try that and let you now how I get on.

**Comment by linX-project** [comment]
Okay, so I removed all of the references I could find to block **777507** (and it's relative id) in the database. Forced `findblock` and it added a new block later than the trouble block, but also added **777507** again which broke it once more.

Also the new (later) block that was added has no `account_id`, `shares` or `share_id` values and the `worker_name` is unknown.

I seem to be stuck in a vicious loop here.

Can you let me know every table in the db that references a block please?

I know of `blocks`, `shares_archive`, `statistics_shares` and `transactions`. Am I missing something?

**Comment by thespice** [comment]
Okay, so I removed all of the references I could find to block **777507** (and it's relative id) in the database. Forced `findblock` and it added a new block later than the trouble block, but also added **777507** again which broke it once more. 

Also the new (later) block that was added has no `account_id`, `shares` or `share_id` values and the `worker_name` is unknown.

I seem to be stuck in a vicious loop here. 

Can you let me know every table in the db that references a block please? I know of `blocks`, `shares_archive`, `statistics_shares` and `transactions`. Am I missing something?

I just want to wipe this block completely from the db.

**Comment by TheSerapher** [comment]
You can't - it's not in the MPOS DB it's in side your wallet of your coin. To get rid of it, you have to wipe the wallet completely (losing transactions and all data) and resetting MPOS. That may be the only solution here since I have no insight into your transactions and if there was a hard fork.

**Comment by cornac** [comment]
Try to add manually missing rows such as workername, account_id, shares and mark it as accounted. Then run crons. I think that stratum not insert share that was block’s solution.

**Comment by thespice** [comment]
Thanks for the reply Cormac. Yes I'm using NOMP. Will try what you suggest and report back.

**Comment by thespice** [comment]
@TheSerapher there wasn't a hard fork but it appears that there was a 51% Time Warp attack on the chain. That's what has caused the issue. We have 2 completely separate pools (different servers, different wallets, different dbs, different stratums) and both are suffering from the same errors.

**Comment by cornac** [comment]
maybe try to resync your wallets???

**Comment by TheSerapher** [comment]
Great work everyone!

**Comment by TheSerapher** [comment]
Since a simple resync seemed to have helped I added this to the Error Code wiki page for this specific one :-)
