### ISSUE TITLE
How does MPOS communicate with stratum server?

### ISSUE THREAD

**Issue by xhliu** [MPOS/php-mpos#2771]
I'm setting up MPOS. There are 3 stratum server options: stratum-mining, NOMP, and CoiniumServ. How does MPOS talk with stratum server? AFAIK, MPOS does not speak stratum protocol. Is it through the shared mysql database, where stratum server writes to it (e.g., submitted shared) and MPOS retrieves from.

I'm trying to use a stratum server other than the 3 options above, thus trying to see how to make it compatible with MPOS.

**Comment by r4sas** [comment]
MPOS is not communicating with stratum directly. It only work with data which stored by stratum in MySQL database.

**Comment by xhliu** [comment]
What data needs to be saved for a stratum server to be MPOS compatible?

**Comment by r4sas** [comment]
See here:
https://github.com/zone117x/node-open-mining-portal/blob/master/libs/mposCompatibility.js

https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/sql/000_base_structure.sql#L10-L33

https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/sql/000_base_structure.sql#L125-L136

https://github.com/MPOS/php-mpos/blob/236cccd5d3178e99504bf2665db8bddfed6aa176/sql/000_base_structure.sql#L147-L163
