### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/mpos/public/index.php on line 91

### ISSUE THREAD

**Issue by jackmagooli** [MPOS/php-mpos#2774]
Site Works but this Warning....

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/mpos/public/index.php on line 91

line 91       if (count(@$_SESSION['last_ip_pop']) == 2) {

System
Ubuntu 18.04
Php7
Apache

**Comment by r4sas** [comment]
Work with PHP 7 is not guaranteed, so that can be. I think no one tested it with 7 version.

**Comment by KhryptorGraphics** [comment]
well that helps no one.

**Comment by r4sas** [comment]
Well...  Currently I installing MPOS on PHP7.2 and got that warning.

So I find in google that this happens because of empty variable passed to `count()`.
https://stackoverflow.com/a/56421524

So possible workaround is checking that `$_SESSION['last_ip_pop']` is not empty.

```php
if ((!is_array($_SESSION['last_ip_pop']) || !empty($_SESSION['last_ip_pop'])) && count(@$_SESSION['last_ip_pop']) == 2) {```
