### ISSUE TITLE
Balance only 0

### ISSUE THREAD

**Issue by jackmagooli** [MPOS/php-mpos#2775]
Hi first of all,
thanks for the nice work.

My question is:

My Balance is only at 0.0000000
Even i run the Cronjobs i have a Error
PHP Fatal error:  Class 'mysqli' not found in /var/www/mpos/include/classes/strict.class.php on line 4

mysqli ist enabled

I try with all php versions

**Comment by TheSerapher** [comment]
You need mysql-nd: https://github.com/MPOS/php-mpos/wiki/Quick-Start-Guide#requirements-1

**Comment by TheSerapher** [comment]
Also, if the class can't be found it isn't properly enabled. Setup issue on your end so something you'll need to check out :)
