### ISSUE TITLE
Any way to make mpos working with new 0.18 Core version?

### ISSUE THREAD

**Issue by TheCryptoServices** [MPOS/php-mpos#2780]
Trying to figure how to make mpos works with 0.18 core version.
Any progress on that? anyone looking for a fix?
Thanks!

**Comment by TheCryptoServices** [comment]
Nvm

**Comment by HashUnlimited** [comment]
The dev branch is working fine here since a few months... Any other test results?

I have just noticed that the payouts script fails to delete the active flag in the DB, happens every 3-5 weeks but I can't get any debugging info for looking at that in an issue. All the rest is stable here.
