### ISSUE TITLE
SQL Query prop_payout failed since upgrading MariaDB 10.1 to 10.2 / Strict Mode SQL Issue?

### ISSUE THREAD

**Issue by thomas2122** [MPOS/php-mpos#2785]
**What I did?**
Upgraded MariaDB 10.1 to 10.2. 

**Issue**
Since the update to mariadb10.2 the prop_payout cron log spams with:
`CRIT --> Failed to update share statistics for uses_xy: SQL Query failed: Field 'pplns_valid' doesn't have a default value`

The pool is running **prop payout** system.

Before the update I added the following options hard to the my.cnf. Doing a queries says that the options are active and working. (This was recommended by you guys when upgrading to mysql 5.7 which should be equivalent to mariadb10.2

`sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

Trying to set SQL_Mode to "TRADITIONAL" has no effect, I still gets the error. Other cron logs looks fine for now.

This must have something to do with changes of SQL Mode. So far I wasn't able to fix the issue by myself and I am not sure wether I am affectec and will run into issues by ignoring the cron errors.

Checking https://mariadb.com/kb/en/changes-improvements-in-mariadb-102/ shows:

**Incompatible Changes**

> SQL_MODE has been changed; in particular, NOT NULL fields with no default will no longer fall back to a dummy value for inserts which do not specify a value for that field.

What should I do? Reverting the database by using mysqldump would mean a downtime of 6+ hours since the database is 13GB big.

Thanks for any help here. Stay healthy!

**Comment by TheSerapher** [comment]
Try setting a default of 0 for that field would be my guess. Since it
s counting valid shares a default of 0 should be fine If nothing is passed on.

**Comment by thomas2122** [comment]
Thanks for the fast reply!

This here to 0 or "NULL"?
https://i.imgur.com/6UeBk2j.jpg

Do you expect any damage of payouts / coins for the last hours before these change for users or is this just "statistics"?

Thank you!

**Comment by TheSerapher** [comment]
That's nothing really, neither 0 nor NULL so I would think that should fix it. And it's only statistics so I doubt payouts are affected :)

**Comment by thomas2122** [comment]
Can confirm that it doesn't shows any new errors since changing the default value to "0". Perfect!

Now I can proceed to do the upgrade from mariadb 10.2 to 10.3 :-)
