### ISSUE TITLE
Unable to connect to wallet RPC service: RPC call failed: Failed to connect to 95.217.90.25 port 27486: Connection refused

### ISSUE THREAD

**Issue by alphatechitukltd** [MPOS/php-mpos#2788]
Hi there,

Please could you tell me what is wrong ?

I am using node stratum and I know the wallet is working as I tested with S-NOMP.

I am using Verus Coin.

Same as RPC - No firewall between servers 

$config['wallet']['type'] = 'http';
$config['wallet']['host'] = '95.217.90.25:27486';
$config['wallet']['username'] = 'verus';
$config['wallet']['password'] = 'HIDDEN';

Thanks

**Comment by TnTBass** [comment]
Check your wallet debug logs, this is unlikely to be a MPOS issue.
