### ISSUE TITLE
Share insert error for RAVEN coin 

### ISSUE THREAD

**Issue by kunalbarchha** [MPOS/php-mpos#2791]
Insert error when adding share, err = {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlMessage":"Unknown column 'unknown' in 'field list'","sqlState":"42S22","index":0,"sql":"INSERT INTO `shares` SET time = NOW(), rem_host = '::ffff:188.166.37.58', username = 'miningexpert.miner', our_result = 'Y', upstream_result = 'N', difficulty = 0.1, reason = `unknown` = 'check coin daemon logs', solution = '0000000605407e71fbfc35143fe052e89dac42499555605aef1f666bd31f1706'"}

**Comment by r4sas** [comment]
Not MPOS issue. Check you stratum.
