### ISSUE TITLE
Shares generating not blocks

### ISSUE THREAD

**Issue by cis-sabahat** [MPOS/php-mpos#2792]
I have configured the mining pool and stratum URL is generated. But When I am mining via cpuminer the blocks are not generating on the coin daemon but the share is being inserted in the share table. Can you please assist what's happening? I am configuring the pool on the main chain and coin is POW. Mining of the coin is already going on by solo mining. Now I am trying to configure the pool as well. But blocks are not generated by the pool coin daemon but the share is being inserted in the share table. Please assist.

**Comment by TheSerapher** [comment]
Please check for your coin daemon/coin - this has nothing to do with MPOS. If you switch from Solo mining to pooled mining create a new wallet too and use that instead of the solo mining one.

Blocks can take a while to be generated depending on the coin. Give it time.

**Comment by cis-sabahat** [comment]
I am not switching from solo to pool. Solo is also running and I am configuring pool. AlsoI have configured pool on new wallet not on solo mining walet. I have setup every thing new

**Comment by TheSerapher** [comment]
Then double check that your coin daemon and more importantly stratum are properly configured. If no blocks show up I your coin daemon that's not an issue with MPOS.
